// Generated by generate_beyond_infinity_ai.py; native areas, placement policy.
#pragma once
#include "../coo/native_combatant_authority.h"
namespace dawn::state::activity::beyond_infinity {
constexpr coo::native_combatant::TacticalGroup tactical_group(coo::Asset source) noexcept {
    if(source.registry!=0x0FF26BCCU || source.type!=1) { return {}; }
    switch(source.slot) {
    case 6: return {0x0FF26BCCU,0,0};
    case 7: return {0x0FF26BCCU,0,1};
    case 8: return {0x0FF26BCCU,0,2};
    case 9: return {0x0FF26BCCU,0,3};
    case 10: return {0x0FF26BCCU,0,4};
    case 11: return {0x0FF26BCCU,0,5};
    case 12: return {0x0FF26BCCU,0,6};
    case 13: return {0x0FF26BCCU,0,6};
    case 14: return {0x0FF26BCCU,0,6};
    default: return {};
    }
}
}
