#pragma once
#include "authored_registry.h"
#include <array>

namespace dawn::state::activity::coo::mercury::public_events {
// Package-derived metadata only. Generated by tools/testing/public_event_inventory.py.
// Recovered descriptors are not activation policy; no raw spawner requests are exposed.
namespace authored = state::activity::coo::registry;
inline constexpr std::array<authored::Slot,13> kSlots_85C38F77{{
    {0,4,0x80809927,0x8080992E,0x8080992F,0x80F5BF33}, // pf_public_event_rally_point.rally_flag
    {1,23,0x80804F45,0x80804F47,0x80804F48,0x80F5BF36}, // pf_public_event_rally_point.rally_flag_device
    {2,70,0x808094EE,0x808094F0,0x808094F1,0x80F5BF13}, // m_engagement_sensor
    {3,68,0x80804F53,0xFFFFFFFF,0x80804F67,0x80F5BF07}, // m_directive_sensor
    {4,53,0x80804F4B,0xFFFFFFFF,0x80804F77,0x80F5BF0A}, // m_dialog_sensor
    {5,11,0x80804E8E,0xFFFFFFFF,0x80804F58,0x80F5BF26}, // m_music_sensor
    {6,71,0x80804F49,0x80804F56,0x80804F57,0x80F5BF0D}, // m_public_event_sensor
    {7,32,0x80809556,0xFFFFFFFF,0x8080955A,0x80F5BF3C}, // rally_point_spawn_override_toggle_island_left
    {8,32,0x80809556,0xFFFFFFFF,0x8080955A,0x80F5BF3F}, // rally_point_spawn_override_toggle_island_right
    {9,32,0x80809556,0xFFFFFFFF,0x8080955A,0x80F5BF42}, // rally_point_spawn_override_toggle_island_left_to_right
    {10,32,0x80809556,0xFFFFFFFF,0x8080955A,0x80F5BF45}, // rally_point_spawn_override_toggle_island_right_to_left
    {11,32,0x80809556,0xFFFFFFFF,0x8080955A,0x80F5BF48}, // rally_point_spawn_override_toggle_center_left
    {12,32,0x80809556,0xFFFFFFFF,0x8080955A,0x80F5BF4B}, // rally_point_spawn_override_toggle_center_right
}};
inline constexpr std::array<authored::Slot,145> kSlots_C8229B2B{{
    {0,4,0x80809927,0x8080992E,0x8080992F,0x80F5E3C7}, // _o_sacrifice_object
    {1,4,0x80809927,0x8080992E,0x8080992F,0x80F5E3CA}, // _o_vortex
    {2,4,0x80809927,0x8080992E,0x8080992F,0x80F5E3CD}, // _o_event_beacon
    {3,4,0x80809927,0x8080992E,0x8080992F,0x80F5E3D0}, // _o_oracle_1
    {4,4,0x80809927,0x8080992E,0x8080992F,0x80F5E3D3}, // _o_oracle_2
    {5,4,0x80809927,0x8080992E,0x8080992F,0x80F5E3D6}, // _o_oracle_3
    {6,4,0x80809927,0x8080992E,0x8080992F,0x80F5E3D9}, // unresolved name
    {7,4,0x80809927,0x8080992E,0x8080992F,0x80F5E3DC}, // unresolved name
    {8,4,0x80809927,0x8080992E,0x8080992F,0x80F5E3DF}, // _o_arena_push_physics_left
    {9,4,0x80809927,0x8080992E,0x8080992F,0x80F5E3E2}, // _o_arena_push_physics_right
    {10,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E3E5}, // _d_event_beacon
    {11,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E3E8}, // _d_vortex
    {12,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E3EB}, // _d_arena_shield
    {13,4,0x80809927,0x8080992E,0x8080992F,0x80F5E3EE}, // _o_dunk_target_left_1
    {14,4,0x80809927,0x8080992E,0x8080992F,0x80F5E3F1}, // _o_dunk_interactable_left_1
    {15,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E3F4}, // _d_dunk_target_left_1
    {16,4,0x80809927,0x8080992E,0x8080992F,0x80F5E3F7}, // _o_dunk_target_left_2
    {17,4,0x80809927,0x8080992E,0x8080992F,0x80F5E3FA}, // _o_dunk_interactable_left_2
    {18,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E3FD}, // _d_dunk_target_left_2
    {19,4,0x80809927,0x8080992E,0x8080992F,0x80F5E400}, // _o_dunk_target_right_1
    {20,4,0x80809927,0x8080992E,0x8080992F,0x80F5E403}, // _o_dunk_interactable_right_1
    {21,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E406}, // _d_dunk_target_right_1
    {22,4,0x80809927,0x8080992E,0x8080992F,0x80F5E409}, // _o_dunk_target_right_2
    {23,4,0x80809927,0x8080992E,0x8080992F,0x80F5E40C}, // _o_dunk_interactable_right_2
    {24,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E40F}, // _d_dunk_target_right_2
    {25,4,0x80809927,0x8080992E,0x8080992F,0x80F5E412}, // _o_dunk_target_center
    {26,4,0x80809927,0x8080992E,0x8080992F,0x80F5E415}, // _o_dunk_interactable_center
    {27,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E418}, // _d_dunk_target_center
    {28,4,0x80809927,0x8080992E,0x8080992F,0x80F5E41B}, // _o_dunk_target_island_left
    {29,4,0x80809927,0x8080992E,0x8080992F,0x80F5E41E}, // _o_dunk_interactable_island_left
    {30,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E421}, // _d_dunk_target_island_left
    {31,4,0x80809927,0x8080992E,0x8080992F,0x80F5E424}, // _o_dunk_target_island_right
    {32,4,0x80809927,0x8080992E,0x8080992F,0x80F5E427}, // _o_dunk_interactable_island_right
    {33,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E42A}, // _d_dunk_target_island_right
    {34,4,0x80809927,0x8080992E,0x8080992F,0x80F5E42D}, // _o_carryable_left_1
    {35,4,0x80809927,0x8080992E,0x8080992F,0x80F5E430}, // _o_carryable_left_2
    {36,4,0x80809927,0x8080992E,0x8080992F,0x80F5E433}, // _o_carryable_right_1
    {37,4,0x80809927,0x8080992E,0x8080992F,0x80F5E436}, // _o_carryable_right_2
    {38,4,0x80809927,0x8080992E,0x8080992F,0x80F5E439}, // _o_carryable_left_1_no_phys
    {39,4,0x80809927,0x8080992E,0x8080992F,0x80F5E43C}, // _o_carryable_left_2_no_phys
    {40,4,0x80809927,0x8080992E,0x8080992F,0x80F5E43F}, // _o_carryable_right_1_no_phys
    {41,4,0x80809927,0x8080992E,0x8080992F,0x80F5E442}, // _o_carryable_right_2_no_phys
    {42,4,0x80809927,0x8080992E,0x8080992F,0x80F5E445}, // _o_carryable_bounds_island_left
    {43,4,0x80809927,0x8080992E,0x8080992F,0x80F5E448}, // _o_carryable_bounds_island_right
    {44,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5E3A4}, // _sq_pilgrims_left_travel
    {45,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5E3A7}, // _sq_pilgrims_left_defend
    {46,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5E3AA}, // _sq_pilgrims_right_travel
    {47,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5E3AD}, // _sq_pilgrims_right_defend
    {48,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5E3B0}, // _sq_gatekeeper_left
    {49,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5E3B3}, // _sq_gatekeeper_right
    {50,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5E3B6}, // _sq_sniper_left_1
    {51,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5E3C4}, // _sq_sniper_left_2
    {52,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5E44B}, // _sq_sniper_right_1
    {53,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5E44E}, // _sq_sniper_right_2
    {54,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5E451}, // _sq_pilgrim_harpy
    {55,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5E454}, // _sq_island_fodder_1
    {56,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5E457}, // _sq_island_fodder_2
    {57,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5E45A}, // _sq_boss
    {58,2,0x8080834E,0x80807DA2,0x80807DA1,0x80F5E475}, // _sq_boss__minotaur
    {59,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5E45D}, // _sq_boss_fodder_left
    {60,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5E460}, // _sq_boss_fodder_right
    {61,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5E463}, // _sq_boss_fodder_fanatics
    {62,4,0x80809927,0x8080992E,0x8080992F,0x80F5E481}, // unresolved name
    {63,4,0x80809927,0x8080992E,0x8080992F,0x80F5E484}, // unresolved name
    {64,4,0x80809927,0x8080992E,0x8080992F,0x80F5E487}, // unresolved name
    {65,4,0x80809927,0x8080992E,0x8080992F,0x80F5E48A}, // unresolved name
    {66,4,0x80809927,0x8080992E,0x8080992F,0x80F5E48D}, // unresolved name
    {67,4,0x80809927,0x8080992E,0x8080992F,0x80F5E490}, // unresolved name
    {68,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E493}, // _d_warpgates_island_left
    {69,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E496}, // _d_warpgates_island_right
    {70,4,0x80809927,0x8080992E,0x8080992F,0x80F5E499}, // _o_mancannon_main_to_island_left_launch
    {71,4,0x80809927,0x8080992E,0x8080992F,0x80F5E49C}, // _o_mancannon_main_to_island_left
    {72,4,0x80809927,0x8080992E,0x8080992F,0x80F5E49F}, // _o_mancannon_main_to_island_right_launch
    {73,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4A2}, // _o_mancannon_main_to_island_right
    {74,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4A5}, // _o_mancannon_center_right_launch
    {75,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4A8}, // _o_mancannon_center_right_catch
    {76,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4AB}, // _o_mancannon_center_left_launch
    {77,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4AE}, // _o_mancannon_center_left_catch
    {78,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4B1}, // _o_island_left_catch_geo
    {79,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4B4}, // _o_island_right_catch_geo
    {80,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E4B7}, // _d_island_left_catch_geo
    {81,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E4BA}, // _d_island_right_catch_geo
    {82,3,0x80808348,0x80807F04,0x80807F0C,0x80F5E4BD}, // _obj_center
    {83,3,0x80808348,0x80807F04,0x80807F0C,0x80F5E4C0}, // _obj_islands
    {84,3,0x80808348,0x80807F04,0x80807F0C,0x80F5E4C3}, // _obj_boss_fight
    {85,26,0x8080953F,0x8080954A,0x8080954B,0x80F5E4C6}, // _ho_boss_shield
    {86,26,0x8080953F,0x8080954A,0x8080954B,0x80F5E4C9}, // _ho_invincible
    {87,26,0x8080953F,0x8080954A,0x8080954B,0x80F5E4CC}, // _ho_carry_outer_bounds
    {88,5,0x80804F01,0xFFFFFFFF,0x80804F04,0x80F5E355}, // _seq_intro_behavior
    {89,5,0x80804F01,0xFFFFFFFF,0x80804F04,0x80F5E358}, // _seq_event_active_behavior
    {90,43,0x80806382,0x8080626A,0x8080626B,0x80F5E4CF}, // _scn_boss_heroic_shield
    {91,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4D2}, // _o_secondary_chest
    {92,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4D5}, // _o_chest_waypoint
    {93,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4D8}, // _pf_reward_chest.spawn_fx_object
    {94,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4DB}, // _pf_reward_chest.chest_convoy_object
    {95,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4DE}, // _pf_reward_chest.chest_cowardly_major_object
    {96,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4E1}, // _pf_reward_chest.chest_vex_prisoner_object
    {97,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4E4}, // _pf_reward_chest.chest_vex_cannon_object
    {98,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4E7}, // _pf_reward_chest.chest_fallen_refinery_object
    {99,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4EA}, // _pf_reward_chest.chest_ambient_ambush_object
    {100,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4ED}, // _pf_reward_chest.chest_tier0_object
    {101,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4F0}, // _pf_reward_chest.chest_tier1_object
    {102,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4F3}, // _pf_reward_chest.chest_tier2_object
    {103,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4F6}, // _pf_reward_chest.chest_tier3_object
    {104,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4F9}, // _pf_reward_chest.chest_tier4_object
    {105,4,0x80809927,0x8080992E,0x8080992F,0x80F5E4FC}, // _o_secondary_chest_spawn_fx
    {106,70,0x808094EE,0x808094F0,0x808094F1,0x80F5E466}, // m_engagement_sensor
    {107,68,0x80804F53,0xFFFFFFFF,0x80804F67,0x80F5E337}, // m_directive_sensor
    {108,53,0x80804F4B,0xFFFFFFFF,0x80804F77,0x80F5E33A}, // m_dialog_sensor
    {109,11,0x80804E8E,0xFFFFFFFF,0x80804F58,0x80F5E362}, // m_music_sensor
    {110,71,0x80804F49,0x80804F56,0x80804F57,0x80F5E33D}, // m_public_event_sensor
    {111,34,0x80809568,0xFFFFFFFF,0x8080956A,0x80F5E368}, // of_boss
    {112,34,0x80809568,0xFFFFFFFF,0x8080956A,0x80F5E36B}, // of_invincible
    {113,34,0x80809568,0xFFFFFFFF,0x8080956A,0x80F5E36E}, // of_all_carryables
    {114,34,0x80809568,0xFFFFFFFF,0x8080956A,0x80F5E371}, // of_all_players
    {115,31,0x80809522,0xFFFFFFFF,0x80809524,0x80F5E469}, // pt_phase_4_boss_arrival
    {116,31,0x80809522,0xFFFFFFFF,0x80809524,0x80F5E46C}, // pt_island_left
    {117,31,0x80809522,0xFFFFFFFF,0x80809524,0x80F5E46F}, // pt_island_right
    {118,30,0x8080952F,0x80809531,0x80809532,0x80F5E472}, // pm_island_left_heroic_jump
    {119,30,0x8080952F,0x80809531,0x80809532,0x80F5E478}, // pm_island_right_heroic_jump
    {120,31,0x80809522,0xFFFFFFFF,0x80809524,0x80F5E47B}, // pt_heroic_mancannon_left
    {121,31,0x80809522,0xFFFFFFFF,0x80809524,0x80F5E47E}, // pt_heroic_mancannon_right
    {132,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E340}, // sr_boss_fodder_right
    {146,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E343}, // sr_boss_fodder_fanatics_near
    {166,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E346}, // sr_boss_fodder_fanatics_far
    {172,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E349}, // sr_boss
    {174,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E34F}, // sr_pilgrims_left_all
    {175,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E35C}, // sr_pilgrims_left_side_1
    {176,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E35F}, // sr_pilgrims_left_side_2
    {239,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E365}, // sr_pilgrims_right_all
    {241,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E374}, // sr_pilgrims_right_side_1
    {242,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E377}, // sr_pilgrims_right_side_2
    {244,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E37A}, // sr_gatekeeper_left
    {245,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E37D}, // sr_gatekeeper_left_island
    {246,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E380}, // sr_gatekeeper_right
    {247,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E383}, // sr_gatekeeper_right_island
    {248,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E386}, // sr_gatekeeper_boss_left
    {249,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E389}, // sr_gatekeeper_boss_right
    {250,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E38C}, // sr_sniper_left_1
    {251,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E38F}, // sr_sniper_left_2
    {252,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E392}, // sr_sniper_right_1
    {253,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E395}, // sr_sniper_right_2
    {254,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E398}, // sr_gates_left_island
    {255,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E39B}, // sr_gates_right_island
    {256,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5E39E}, // sr_boss_fodder_left
}};
inline constexpr std::array<authored::Slot,37> kSlots_B1EAC5B6{{
    {0,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E5D4}, // _d_main_walls
    {1,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E5D7}, // _d_mancannon_main_left
    {2,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E5DA}, // _d_mancannon_main_right
    {3,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E5DD}, // _d_jump_platform_left_base
    {4,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E5E0}, // _d_jump_platform_left_path_a_1
    {5,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E5E3}, // _d_jump_platform_left_path_a_2
    {6,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E5E6}, // _d_jump_platform_left_path_a_3
    {7,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E5E9}, // _d_jump_platform_left_path_b_1
    {8,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E5EC}, // _d_jump_platform_left_path_b_2
    {9,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E5EF}, // _d_jump_platform_left_path_b_3
    {10,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E5F2}, // _d_jump_platform_right_base
    {11,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E5F5}, // _d_jump_platform_right_path_a_1
    {12,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E5F8}, // _d_jump_platform_right_path_a_2
    {13,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E5FB}, // _d_jump_platform_right_path_a_3
    {14,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E5FE}, // _d_jump_platform_right_path_b_1
    {15,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E601}, // _d_jump_platform_right_path_b_2
    {16,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E604}, // _d_jump_platform_right_path_b_3
    {17,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E607}, // _d_capture_plate_left
    {18,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E60A}, // _d_capture_plate_right
    {19,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E60D}, // _d_laser_left
    {20,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E610}, // _d_laser_right
    {21,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E613}, // _d_dunk_lines_left_1
    {22,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E616}, // _d_dunk_lines_left_2
    {23,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E619}, // _d_dunk_lines_right_1
    {24,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E61C}, // _d_dunk_lines_right_2
    {25,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E61F}, // _d_mancannon_ball_fx_ambient
    {26,23,0x80804F45,0x80804F47,0x80804F48,0x80F5E622}, // _d_mancannon_ball_fx_islands
    {27,4,0x80809927,0x8080992E,0x8080992F,0x80F5E625}, // _o_mancannon_main_left
    {28,4,0x80809927,0x8080992E,0x8080992F,0x80F5E628}, // _o_mancannon_main_right
    {29,4,0x80809927,0x8080992E,0x8080992F,0x80F5E62B}, // _o_capture_plate_island_left
    {30,4,0x80809927,0x8080992E,0x8080992F,0x80F5E62E}, // _o_capture_plate_island_right
    {31,4,0x80809927,0x8080992E,0x8080992F,0x80F5E631}, // _o_arena_escape_teleporter
    {32,70,0x808094EE,0x808094F0,0x808094F1,0x80F5E570}, // m_engagement_sensor
    {33,30,0x8080952F,0x80809531,0x80809532,0x80F5E582}, // pm_capture_tower_left
    {34,30,0x8080952F,0x80809531,0x80809532,0x80F5E597}, // pm_capture_tower_right
    {35,24,0x80804F3B,0x80804F3D,0x80804F40,0x80F5E5A0}, // ch_channel_mancannon_fx_left
    {36,24,0x80804F3B,0x80804F3D,0x80804F40,0x80F5E5A5}, // ch_channel_mancannon_fx_right
}};
inline constexpr std::array<authored::Definition,3> kRegistries{{
    {"mercury_freeroam",0x80F4696A,0x85C38F77,0x80F5BF4E,0xA83A9175,15,kSlots_85C38F77},
    {"mercury_freeroam",0x80F4696A,0xC8229B2B,0x80F5E517,0xA83A9175,15,kSlots_C8229B2B},
    {"mercury_freeroam",0x80F4696A,0xB1EAC5B6,0x80F5E643,0xA83A9175,15,kSlots_B1EAC5B6},
}};
// Every optional event registry must first exist in the runtime package
// catalog. Selecting only the encounter omits the separate cannon geometry.
[[nodiscard]] constexpr bool required(std::uint32_t scenario,std::uint32_t objectTag,
    std::uint32_t key,std::uint64_t explicitBubbleMask) noexcept {
    for(const auto& definition:kRegistries)
        if(authored::required(definition,scenario,objectTag,key,explicitBubbleMask))return true;
    return false;
}
} // namespace dawn::state::activity::coo::mercury::public_events
