// Generated by tools/coo/generate_deadly_trial.py.
#pragma once
#include <array>
#include <span>
#include <string_view>
#include "../coo/dialogue_service.h"
#include "../coo/native_combatant_authority.h"
namespace dawn::state::activity::deadly_trial {
inline constexpr std::uint32_t kScenario=0x80B2E043U,kRoot=0xC9BC773AU,kBank=0x80F1F086U,kAlleysA=0xEB7AF018U,kAlleysB=0xEB7AF01BU;
inline constexpr std::string_view kEvidenceSha256="63da29b6393fc3dbbdbaa4af15c705d762a5d6833c62a5bbf0ac65b6408703d9";
struct Slot { std::uint8_t type,flags;std::uint16_t index;std::uint32_t tag,offset,component,sense,auth; };
struct Group { std::uint32_t key,tag;std::size_t hint;bool topLevel;std::uint8_t bubble;std::span<const Slot> slots; };
inline constexpr Slot kSlots0[]{
    {68,2,0,0x80B2E706U,0x00000B88U,0x80804F53U,0xFFFFFFFFU,0x80804F67U}, // m_directive_sensor
    {11,2,1,0x80B2ED2AU,0x00000648U,0x80804E8EU,0xFFFFFFFFU,0x80804F58U}, // m_music_sensor
    {53,2,2,0x80B2E709U,0x00001408U,0x80804F4BU,0xFFFFFFFFU,0x80804F77U}, // m_dialog_sensor
};
inline constexpr Slot kSlots1[]{
    {3,3,0,0x80B2E2B8U,0x00000618U,0x80808348U,0x80807F04U,0x80807F0CU}, // hub_fallen_objective
    {1,3,1,0x80B2E2BCU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // hub_fallen_inf01a_squad
    {1,3,2,0x80B2E2BFU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // hub_fallen_inf01b_squad
    {1,3,3,0x80B2E2C3U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // hub_fallen_inf01c_squad
    {4,3,4,0x80B2E2C4U,0x000004C8U,0x80809927U,0x8080992EU,0x8080992FU}, // hub_playerpike_object[0]
    {4,3,5,0x80B2E2C7U,0x000004C8U,0x80809927U,0x8080992EU,0x8080992FU}, // hub_playerpike_object[1]
    {4,3,6,0x80B2E2CCU,0x000004C8U,0x80809927U,0x8080992EU,0x8080992FU}, // hub_playerpike_object[2]
    {3,3,7,0x80B2E2D0U,0x00000798U,0x80808348U,0x80807F04U,0x80807F0CU}, // streets_fallen_objective
    {1,3,8,0x80B2E2DAU,0x00000878U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // streets_fallen_spider01_squad
    {2,3,9,0x80B2E2DCU,0x00000B58U,0x8080834EU,0x80807DA2U,0x80807DA1U}, // streets_fallen_spider01_squad__tank
    {1,3,10,0x80B2E2E8U,0x00000878U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // streets_dropship_dummy01_squad
    {2,3,11,0x80B2E2EAU,0x00000B58U,0x8080834EU,0x80807DA2U,0x80807DA1U}, // streets_dropship_dummy01_squad__dropship
    {1,3,12,0x80B2E2F2U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // streets_fallen_inf01_squad
    {1,3,13,0x80B2E2F8U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // streets_fallen_first_sniper1_squad
    {1,3,14,0x80B2E2FEU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // streets_fallen_first_sniper2_squad
    {1,3,15,0x80B2E302U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // streets_fallen_shank_horde1_squad
    {1,3,16,0x80B2E308U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // streets_fallen_shank_horde2_squad
    {1,3,17,0x80B2E30EU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // streets_fallen_chokepoint_sniper01_squad
    {1,3,18,0x80B2E314U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // streets_fallen_chokepoint_sniper02_squad
    {1,3,19,0x80B2E318U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // streets_fallen_chokepoint_inf01_squad
    {1,3,20,0x80B2E31EU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // streets_fallen_chokepoint_inf02_squad
    {3,3,21,0x80B2E324U,0x00000818U,0x80808348U,0x80807F04U,0x80807F0CU}, // overpass_fallen_objective
    {43,3,22,0x80B2E326U,0x00000368U,0x80806382U,0x8080626AU,0x8080626BU}, // overpass_fallen_spider01_fallback_scene
    {1,3,23,0x80B2E330U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // overpass_fallen_spider01_squad
    {2,3,24,0x80B2E332U,0x00000B58U,0x8080834EU,0x80807DA2U,0x80807DA1U}, // overpass_fallen_spider01_squad__tank
    {1,3,25,0x80B2E33AU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // overpass_fallen_front01_squad
    {1,3,26,0x80B2E33EU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // overpass_fallen_bus01_squad
    {1,3,27,0x80B2E344U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // overpass_fallen_pit01_squad
    {1,3,28,0x80B2E34AU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // overpass_fallen_tunnel_defence01_squad
    {1,3,29,0x80B2E34EU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // overpass_fallen_reinf01_squad
    {1,3,30,0x80B2E354U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // overpass_fallen_reinf02_squad
    {1,3,31,0x80B2E35AU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // overpass_fallen_shanks01_squad
    {1,3,32,0x80B2E35FU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // overpass_fallen_pike01a_squad
    {1,3,33,0x80B2E363U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // overpass_fallen_pike01b_squad
    {1,3,34,0x80B2E368U,0x00000878U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // overpass_dropship_cliff01_squad
    {2,3,35,0x80B2E36AU,0x00000B58U,0x8080834EU,0x80807DA2U,0x80807DA1U}, // overpass_dropship_cliff01_squad__dropship
    {1,3,36,0x80B2E373U,0x00000878U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // overpass_dropship_reinf01_squad
    {2,3,37,0x80B2E375U,0x00000B58U,0x8080834EU,0x80807DA2U,0x80807DA1U}, // overpass_dropship_reinf01_squad__dropship
    {1,3,38,0x80B2E381U,0x00000878U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // overpass_dropship_reinf02_squad
    {2,3,39,0x80B2E383U,0x00000B58U,0x8080834EU,0x80807DA2U,0x80807DA1U}, // overpass_dropship_reinf02_squad__dropship
    {4,3,40,0x80B2E389U,0x000004C8U,0x80809927U,0x8080992EU,0x8080992FU}, // overpass_playerpike_object[0]
    {4,3,41,0x80B2E38FU,0x000004C8U,0x80809927U,0x8080992EU,0x8080992FU}, // overpass_playerpike_object[1]
    {4,3,42,0x80B2E394U,0x000004C8U,0x80809927U,0x8080992EU,0x8080992FU}, // overpass_playerpike_object[2]
    {4,3,43,0x80B2E399U,0x000004C8U,0x80809927U,0x8080992EU,0x8080992FU}, // spider_playerpike_object[0]
    {4,3,44,0x80B2E39EU,0x000004C8U,0x80809927U,0x8080992EU,0x8080992FU}, // spider_playerpike_object[1]
    {4,3,45,0x80B2E3A1U,0x000004C8U,0x80809927U,0x8080992EU,0x8080992FU}, // spider_playerpike_object[2]
    {23,3,46,0x80B2E3ADU,0x00000278U,0x80804F45U,0x80804F47U,0x80804F48U}, // overpass_fallen_barrier_shield_device
    {3,3,47,0x80B2E3B4U,0x00000868U,0x80808348U,0x80807F04U,0x80807F0CU}, // waterfront_fallen_objective
    {1,3,48,0x80B2E3B7U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // waterfront_fallen_pike01a_squad
    {1,3,49,0x80B2E3D2U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // waterfront_fallen_pike01b_squad
    {1,3,50,0x80B2E3D7U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // waterfront_fallen_spider01_squad
    {2,3,51,0x80B2E3D8U,0x00000B58U,0x8080834EU,0x80807DA2U,0x80807DA1U}, // waterfront_fallen_spider01_squad__tank
    {1,3,52,0x80B2E3DFU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // waterfront_fallen_wave01_inf01_squad
    {1,3,53,0x80B2E3E2U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // waterfront_fallen_wave01_inf02_squad
    {1,3,54,0x80B2E3E5U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // waterfront_fallen_wave02_inf01_squad
    {1,3,55,0x80B2E3E8U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // waterfront_fallen_wave02_inf02_squad
    {1,3,56,0x80B2E3EBU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // waterfront_dropship_spider01_squad
    {2,3,57,0x80B2E3ECU,0x00000B58U,0x8080834EU,0x80807DA2U,0x80807DA1U}, // waterfront_dropship_spider01_squad__dropship
    {1,3,58,0x80B2E3F4U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // waterfront_dropship_wave01_inf01_squad
    {2,3,59,0x80B2E3F5U,0x00000B58U,0x8080834EU,0x80807DA2U,0x80807DA1U}, // waterfront_dropship_wave01_inf01_squad__dropship
    {1,3,60,0x80B2E3FCU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // waterfront_dropship_wave01_inf02_squad
    {2,3,61,0x80B2E3FDU,0x00000B58U,0x8080834EU,0x80807DA2U,0x80807DA1U}, // waterfront_dropship_wave01_inf02_squad__dropship
    {1,3,62,0x80B2E424U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // waterfront_hawk_squad
    {2,3,63,0x80B2E425U,0x00000B58U,0x8080834EU,0x80807DA2U,0x80807DA1U}, // waterfront_hawk_squad__dropship
    {4,3,64,0x80B2E428U,0x000004C8U,0x80809927U,0x8080992EU,0x8080992FU}, // waterfront_playerpike_object[0]
    {4,3,65,0x80B2E42CU,0x000004C8U,0x80809927U,0x8080992EU,0x8080992FU}, // waterfront_playerpike_object[1]
    {4,3,66,0x80B2E434U,0x000004C8U,0x80809927U,0x8080992EU,0x8080992FU}, // waterfront_playerpike_object[2]
    {4,3,67,0x80B2E444U,0x000004C8U,0x80809927U,0x8080992EU,0x8080992FU}, // waterfront_guardian_tank1_object
    {70,3,68,0x80B2E438U,0x00000358U,0x808094EEU,0x808094F0U,0x808094F1U}, // m_engagement_sensor
    {30,3,69,0x80B2E43BU,0x00000218U,0x8080952FU,0x80809531U,0x80809532U}, // alleys_a_monitor
    {39,3,70,0x80B2E483U,0x00000208U,0x80804EE2U,0x80804EE4U,0x80804EE5U}, // streets_dropship_dummy01_passenger
    {39,3,71,0x80B2E48CU,0x00000208U,0x80804EE2U,0x80804EE4U,0x80804EE5U}, // waterfront_hawk_passenger
    {39,3,72,0x80B2E48FU,0x00000208U,0x80804EE2U,0x80804EE4U,0x80804EE5U}, // waterfront_dropship_spider01_passenger
    {30,3,73,0x80B2E43EU,0x00000218U,0x8080952FU,0x80809531U,0x80809532U}, // streets_dropship_dummy01_spawn_monitor
    {31,2,74,0x80B2E442U,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // streets_fallen_shank_horde1_spawn_trigger
    {31,2,75,0x80B2E447U,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // streets_fallen_shank_horde2_spawn_trigger
    {31,2,76,0x80B2E44AU,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // streets_fallen_inf01_spawn_trigger
    {31,2,77,0x80B2E44FU,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // streets_fallen_chokepoint01_spawn_trigger
    {31,2,78,0x80B2E452U,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // overpass_encounter_start_trigger
    {31,2,79,0x80B2E455U,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // overpass_encounter_dropship_spawn_trigger
    {30,3,80,0x80B2E459U,0x00000218U,0x8080952FU,0x80809531U,0x80809532U}, // overpass_fallen_spider01_fallback_monitor
    {31,2,81,0x80B2E45CU,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // waterfront_pikes_spawn_trigger
    {31,2,82,0x80B2E461U,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // waterfront_guardian_tank_drop_trigger
    {31,2,83,0x80B2E464U,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // waterfront_encounter_start_trigger
    {25,2,84,0x80B2E552U,0x00000218U,0x80804ED0U,0xFFFFFFFFU,0x80804ED3U}, // overpass_encounter_dropship_spawn_lookat
    {32,2,85,0x80B2E55BU,0x00000208U,0x80809556U,0xFFFFFFFFU,0x8080955AU}, // overpass_spawnoverridevolume_toggle
    {32,2,86,0x80B2E56BU,0x00000208U,0x80809556U,0xFFFFFFFFU,0x8080955AU}, // waterfront_spawnoverridevolume_toggle
    {30,3,87,0x80B2E467U,0x00000218U,0x8080952FU,0x80809531U,0x80809532U}, // spider_teleport_avoidance_monitor[0]
    {30,3,88,0x80B2E46BU,0x00000218U,0x8080952FU,0x80809531U,0x80809532U}, // spider_teleport_avoidance_monitor[1]
    {30,3,89,0x80B2E46EU,0x00000218U,0x8080952FU,0x80809531U,0x80809532U}, // spider_teleport_avoidance_monitor[2]
    {30,3,90,0x80B2E471U,0x00000218U,0x8080952FU,0x80809531U,0x80809532U}, // spider_teleport_avoidance_monitor[3]
    {30,3,91,0x80B2E474U,0x00000218U,0x8080952FU,0x80809531U,0x80809532U}, // spider_teleport_avoidance_monitor[4]
    {30,3,92,0x80B2E477U,0x00000218U,0x8080952FU,0x80809531U,0x80809532U}, // spider_teleport_avoidance_monitor[5]
    {66,0,93,0x80B2E093U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // overpass_fallen_spider01_squad_spawnrule
    {66,0,95,0x80B2E096U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // overpass_fallen_front01_squad_spawnrule
    {66,0,97,0x80B2E0B1U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // overpass_fallen_bus01_squad_spawnrule
    {66,0,99,0x80B2E0B4U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // overpass_fallen_pit01_squad_spawnrule
    {66,0,101,0x80B2E0B7U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // overpass_fallen_tunnel_defence01_squad_spawnrule
    {66,0,103,0x80B2E0BAU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // overpass_fallen_reinf01_squad_spawnrule
    {66,0,105,0x80B2E0DAU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // overpass_fallen_reinf02_squad_spawnrule
    {66,0,107,0x80B2E0E9U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // overpass_fallen_shanks01_squad_spawnrule
    {66,0,109,0x80B2E0ECU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // overpass_fallen_pike01a_squad_spawnrule
    {66,0,111,0x80B2E0F8U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // overpass_fallen_pike01b_squad_spawnrule
    {66,0,112,0x80B2E0FBU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // hub_fallen_inf01b_squad_spawnrule
    {66,0,114,0x80B2E10FU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // hub_fallen_inf01c_squad_spawnrule
    {58,0,115,0x80B2E113U,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // streets_dropship_dummy01_command
    {66,0,117,0x80B2E116U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // streets_fallen_inf01_squad_spawnrule
    {58,0,135,0x80B2E12CU,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // overpass_dropship_cliff01_enter_command
    {58,0,136,0x80B2E130U,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // overpass_dropship_cliff01_exit_command
    {58,0,137,0x80B2E13AU,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // overpass_dropship_reinf01_enter_command
    {58,0,138,0x80B2E13EU,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // overpass_dropship_reinf01_exit_command
    {58,0,139,0x80B2E142U,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // overpass_dropship_reinf02_enter_command
    {58,0,140,0x80B2E146U,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // overpass_dropship_reinf02_exit_command
    {66,0,143,0x80B2E149U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // streets_fallen_first_sniper1_squad_spawnrule
    {66,0,145,0x80B2E14CU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // streets_fallen_first_sniper2_squad_spawnrule
    {66,0,147,0x80B2E14FU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // streets_fallen_shank_horde1_squad_spawnrule
    {66,0,149,0x80B2E152U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // streets_fallen_shank_horde2_squad_spawnrule
    {66,0,164,0x80B2E158U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // waterfront_fallen_pike01a_squad_spawnrule
    {66,0,165,0x80B2E163U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // streets_fallen_chokepoint_sniper01_squad_spawnrule
    {66,0,166,0x80B2E166U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // waterfront_fallen_pike01b_squad_spawnrule
    {66,0,168,0x80B2E16FU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // streets_fallen_chokepoint_sniper02_squad_spawnrule
    {66,0,169,0x80B2E190U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // waterfront_fallen_spider01_squad_spawnrule
    {66,0,172,0x80B2E193U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // waterfront_fallen_wave01_inf01_squad_spawnrule
    {66,0,173,0x80B2E196U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // streets_fallen_chokepoint_inf01_squad_spawnrule
    {66,0,174,0x80B2E199U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // waterfront_fallen_wave01_inf02_squad_spawnrule
    {66,0,176,0x80B2E1B2U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // waterfront_fallen_wave02_inf01_squad_spawnrule
    {66,0,177,0x80B2E1B5U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // streets_fallen_chokepoint_inf02_squad_spawnrule
    {66,0,178,0x80B2E1C3U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // waterfront_fallen_wave02_inf02_squad_spawnrule
    {66,0,181,0x80B2E1E5U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // waterfront_dropship_spider01_squad_spawnrule
    {66,0,184,0x80B2E1E8U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // waterfront_dropship_wave01_inf01_squad_spawnrule
    {66,0,187,0x80B2E1EBU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // waterfront_dropship_wave01_inf02_squad_spawnrule
    {66,0,190,0x80B2E243U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // waterfront_hawk_squad_spawnrule
    {58,0,191,0x80B2E247U,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // waterfront_dropship_spider01_enter_command
    {58,0,192,0x80B2E24BU,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // waterfront_dropship_spider01_exit_command
    {58,0,193,0x80B2E24FU,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // waterfront_dropship_wave01_inf01_enter_command
    {58,0,194,0x80B2E279U,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // waterfront_dropship_wave01_inf01_exit_command
    {58,0,195,0x80B2E27DU,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // waterfront_dropship_wave01_inf02_enter_command
    {58,0,196,0x80B2E284U,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // waterfront_dropship_wave01_inf02_exit_command
    {58,0,197,0x80B2E289U,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // waterfront_hawk_exit_command
    {57,0,227,0x80B2E47AU,0x000001F8U,0x808094D7U,0xFFFFFFFFU,0xFFFFFFFFU}, // alleys_a
    {66,0,230,0x80B2E299U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // hub_fallen_inf01a_squad_spawnrule
};
inline constexpr Slot kSlots2[]{
    {31,2,0,0x80B2E481U,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // _directive_trigger
};
inline constexpr Slot kSlots3[]{
    {31,2,0,0x80B2E488U,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // ginger_alleys_a_goto_trigger
};
inline constexpr Slot kSlots4[]{
    {25,2,0,0x80B2E679U,0x00000218U,0x80804ED0U,0xFFFFFFFFU,0x80804ED3U}, // ginger_alleys_a_goto_tank_looktrigger
    {31,2,1,0x80B2E494U,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // objective_progress_trigger
};
inline constexpr Slot kSlots5[]{
    {31,2,0,0x80B2E49FU,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // objective_progress_trigger
};
inline constexpr Slot kSlots6[]{
    {3,3,0,0x80B2E578U,0x00000758U,0x80808348U,0x80807F04U,0x80807F0CU}, // cliffside_fallen_objective
    {1,3,1,0x80B2E57CU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // cliffside_fallen_sniper01_squad
    {1,3,2,0x80B2E57FU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // cliffside_fallen_sniper02_squad
    {1,3,3,0x80B2E59CU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // cliffside_fallen_inf01_squad
    {1,3,4,0x80B2E59FU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // cliffside_fallen_inf02a_squad
    {1,3,5,0x80B2E5A2U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // cliffside_fallen_inf02b_squad
    {1,3,6,0x80B2E5A5U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // cliffside_fallen_inf03_squad
    {1,3,7,0x80B2E5A9U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // cliffside_fallen_inf04_squad
    {1,3,8,0x80B2E5ACU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // cliffside_fallen_dropship_spectacle_squad
    {2,3,9,0x80B2EA9AU,0x00000B58U,0x8080834EU,0x80807DA2U,0x80807DA1U}, // cliffside_fallen_dropship_spectacle_squad__dropship
    {4,3,10,0x80B2EAA7U,0x000004C8U,0x80809927U,0x8080992EU,0x8080992FU}, // cliffside_playerpike_object[0]
    {4,3,11,0x80B2EAABU,0x000004C8U,0x80809927U,0x8080992EU,0x8080992FU}, // cliffside_playerpike_object[1]
    {4,3,12,0x80B2EAAEU,0x000004C8U,0x80809927U,0x8080992EU,0x8080992FU}, // cliffside_playerpike_object[2]
    {3,3,13,0x80B2EAC6U,0x00000618U,0x80808348U,0x80807F04U,0x80807F0CU}, // alleys_b_tunnel_2_ai_objective
    {23,3,14,0x80B2EAD0U,0x00000278U,0x80804F45U,0x80804F47U,0x80804F48U}, // waterfall_tripwires_group1_device
    {1,3,15,0x80B2E5BCU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // alleys_b_tunnel_2_shank_squad_1
    {1,3,16,0x80B2E5BFU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // alleys_b_tunnel_2_mid_squad
    {1,3,17,0x80B2E5C3U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // alleys_b_tunnel_2_shank_squad_2
    {3,3,18,0x80B2E5C7U,0x00000A28U,0x80808348U,0x80807F04U,0x80807F0CU}, // outpost_fallen_objective
    {3,3,19,0x80B2EAE8U,0x000005D8U,0x80808348U,0x80807F04U,0x80807F0CU}, // outpost_fallen_ambush_objective
    {4,3,20,0x80B2EAEBU,0x000004C8U,0x80809927U,0x8080992EU,0x8080992FU}, // outpost_alert_flare1_object
    {4,3,21,0x80B2EAEEU,0x000004C8U,0x80809927U,0x8080992EU,0x8080992FU}, // outpost_playerpike_object[0]
    {4,3,22,0x80B2EAF3U,0x000004C8U,0x80809927U,0x8080992EU,0x8080992FU}, // outpost_playerpike_object[1]
    {4,3,23,0x80B2EAF6U,0x000004C8U,0x80809927U,0x8080992EU,0x8080992FU}, // outpost_playerpike_object[2]
    {5,2,24,0x80B2E7DAU,0x00000658U,0x80804F01U,0xFFFFFFFFU,0x80804F04U}, // outpost_fallen_alarm_sequence
    {1,3,25,0x80B2E5CAU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_tunnel_exit01_squad
    {1,3,26,0x80B2E5CDU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_tunnel_exit02_squad
    {1,3,27,0x80B2E5D0U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_bowl_mid01_squad
    {1,3,28,0x80B2E5D3U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_bowl_mid02_squad
    {1,3,29,0x80B2E5F0U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_bowl_flank01_squad
    {1,3,30,0x80B2E5F3U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_tower_mid_sniper01_squad
    {1,3,31,0x80B2E5F6U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_tower_base_front_squad
    {1,3,32,0x80B2E5FAU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_tower_base_anchor_squad
    {1,3,33,0x80B2E5FDU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_tower_mid_front_squad
    {1,3,34,0x80B2E601U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_tower_mid_back_squad
    {1,3,35,0x80B2E605U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_tower_mid_anchor_squad
    {1,3,36,0x80B2E608U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_tower_lower_back_squad
    {1,3,37,0x80B2E60BU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_tower_stealth1_squad
    {1,3,38,0x80B2E612U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_tower_stealth2_squad
    {1,3,39,0x80B2E615U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_tower_stealth3_squad
    {1,3,40,0x80B2E618U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_wave2_squad
    {1,3,41,0x80B2E61CU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_assault_inf01_squad
    {1,3,42,0x80B2E61FU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_assault_pike01a_squad
    {1,3,43,0x80B2E622U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_assault_pike01b_squad
    {1,3,44,0x80B2E625U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_assault_inf02_squad
    {1,3,45,0x80B2E628U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_dropship01_squad
    {2,3,46,0x80B2EB4AU,0x00000B58U,0x8080834EU,0x80807DA2U,0x80807DA1U}, // outpost_fallen_dropship01_squad__dropship
    {1,3,47,0x80B2E62EU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_assault_dropship01_squad
    {2,3,48,0x80B2EB64U,0x00000B58U,0x8080834EU,0x80807DA2U,0x80807DA1U}, // outpost_fallen_assault_dropship01_squad__dropship
    {1,3,49,0x80B2E631U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // outpost_fallen_assault_dropship02_squad
    {2,3,50,0x80B2EB80U,0x00000B58U,0x8080834EU,0x80807DA2U,0x80807DA1U}, // outpost_fallen_assault_dropship02_squad__dropship
    {5,2,51,0x80B2E7DDU,0x00000658U,0x80804F01U,0xFFFFFFFFU,0x80804F04U}, // outpost_fallen_scream_sequence
    {3,3,52,0x80B2EB83U,0x000005D8U,0x80808348U,0x80807F04U,0x80807F0CU}, // lair_fallen_objective
    {1,3,53,0x80B2E636U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // lair_fallen_cloaked1_squad
    {2,3,54,0x80B2EB8AU,0x00000B58U,0x8080834EU,0x80807DA2U,0x80807DA1U}, // lair_fallen_cloaked1_squad__vandal
    {1,3,55,0x80B2E639U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // lair_fallen_cloaked2_squad
    {2,3,56,0x80B2EB9DU,0x00000B58U,0x8080834EU,0x80807DA2U,0x80807DA1U}, // lair_fallen_cloaked2_squad__vandal
    {1,3,57,0x80B2E63CU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // lair_fallen_cloaked3_squad
    {1,3,58,0x80B2E640U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // lair_fallen_inf01_squad
    {4,3,59,0x80B2EBA7U,0x000004C8U,0x80809927U,0x8080992EU,0x8080992FU}, // lair_revive_interact_object
    {26,3,60,0x80B2EBAAU,0x00000AC8U,0x8080953FU,0x8080954AU,0x8080954BU}, // weapon_down_hop_on
    {3,3,61,0x80B2E643U,0x00000818U,0x80808348U,0x80807F04U,0x80807F0CU}, // coastroad_fallen_objective
    {1,3,62,0x80B2E646U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // coastroad_fallen_hill01_squad
    {1,3,63,0x80B2E649U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // coastroad_fallen_pike01_squad
    {1,3,64,0x80B2E64CU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // coastroad_fallen_pike02a_squad
    {1,3,65,0x80B2E65CU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // coastroad_fallen_pike02b_squad
    {1,3,66,0x80B2E671U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // coastroad_fallen_bridge01_squad
    {1,3,67,0x80B2E674U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // coastroad_fallen_exittransition01_squad
    {1,3,68,0x80B2E677U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // coastroad_fallen_exittransition02_squad
    {1,3,69,0x80B2E67DU,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // coastroad_fallen_island01_squad
    {1,3,70,0x80B2E681U,0x00000728U,0x80809A3BU,0x80807ECCU,0x80807EC9U}, // coastroad_fallen_gunship01_squad
    {2,3,71,0x80B2EBCDU,0x00000B58U,0x8080834EU,0x80807DA2U,0x80807DA1U}, // coastroad_fallen_gunship01_squad__dropship
    {23,3,72,0x80B2EBD1U,0x00000278U,0x80804F45U,0x80804F47U,0x80804F48U}, // coastroad_fallen_shield_plane_device
    {23,3,73,0x80B2EBD5U,0x00000278U,0x80804F45U,0x80804F47U,0x80804F48U}, // coastroad_fallen_shield_emitter_device
    {43,3,74,0x80B2EBD9U,0x00000368U,0x80806382U,0x8080626AU,0x8080626BU}, // sc_sagira_revive
    {70,3,75,0x80B2E684U,0x00000358U,0x808094EEU,0x808094F0U,0x808094F1U}, // m_engagement_sensor
    {34,2,76,0x80B2E7E0U,0x00000388U,0x80809568U,0xFFFFFFFFU,0x8080956AU}, // weapon_down_filter
    {30,3,77,0x80B2E687U,0x00000218U,0x8080952FU,0x80809531U,0x80809532U}, // alleys_b_monitor
    {25,2,78,0x80B2EBE5U,0x00000218U,0x80804ED0U,0xFFFFFFFFU,0x80804ED3U}, // cliffside_fallen_dropship_spawn_look_trigger
    {31,2,79,0x80B2E68BU,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // cliffside_fallen_dropship_spawn_trigger
    {31,2,80,0x80B2E68FU,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // cliffside_fallen_spawn_trigger
    {31,2,81,0x80B2E692U,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // alleys_b_tunnel_2_spawn_front_ai_player_trigger
    {31,2,82,0x80B2E695U,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // alleys_b_tunnel_2_spawn_rear_ai_player_trigger
    {32,2,83,0x80B2EBF7U,0x00000208U,0x80809556U,0xFFFFFFFFU,0x8080955AU}, // alleys_b_top_spawn_override_toggle
    {31,2,84,0x80B2E699U,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // outpost_fallen_init_trigger
    {30,3,85,0x80B2E69DU,0x00000218U,0x8080952FU,0x80809531U,0x80809532U}, // outpost_fallen_ambush_monitor
    {31,2,86,0x80B2E6A0U,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // alleys_b_goto_observatory_end_player_trigger
    {30,3,87,0x80B2E6A3U,0x00000218U,0x8080952FU,0x80809531U,0x80809532U}, // outpsot_mid_back_expand_monitor
    {31,2,88,0x80B2E6A7U,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // outpost_fallback_volume_tower_trigger
    {29,3,89,0x80B2E6ACU,0x00000218U,0x808094E7U,0x808094E9U,0x808094EAU}, // outpost_fallen_tower_mid_anchor_monitor
    {34,2,90,0x80B2E7E3U,0x00000388U,0x80809568U,0xFFFFFFFFU,0x8080956AU}, // outpost_fallen_tower_mid_anchor_filter
    {31,2,91,0x80B2E6AFU,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // lair_fallen_spawn_trigger
    {31,2,92,0x80B2E6B4U,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // lair_fallen_advance_trigger
    {30,3,93,0x80B2E6B7U,0x00000218U,0x8080952FU,0x80809531U,0x80809532U}, // coastroad_fallen_pike01_monitor
    {31,2,94,0x80B2E6BAU,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // coastroad_fallen_gunship01_trigger
    {66,0,97,0x80B2E4A3U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // cliffside_fallen_sniper02_squad_spawnrule
    {66,0,99,0x80B2E4A6U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // cliffside_fallen_inf01_squad_spawnrule
    {58,0,128,0x80B2E4A9U,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_dropship01_enter_command
    {58,0,129,0x80B2E4ACU,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_dropship01_exit_command
    {58,0,130,0x80B2E4B1U,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_assault_dropship01_enter_command
    {58,0,131,0x80B2E4B4U,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_assault_dropship01_exit_command
    {58,0,132,0x80B2E4B7U,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_assault_dropship02_enter_command
    {58,0,133,0x80B2E4BAU,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_assault_dropship02_exit_command
    {66,0,137,0x80B2E4BDU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // cliffside_fallen_inf02a_squad_spawnrule
    {66,0,138,0x80B2E4C0U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_tunnel_exit01_squad_spawnrule
    {66,0,140,0x80B2E4C3U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_tunnel_exit02_squad_spawnrule
    {66,0,141,0x80B2E4C7U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // cliffside_fallen_inf02b_squad_spawnrule
    {66,0,142,0x80B2E4CCU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_bowl_mid01_squad_spawnrule
    {66,0,144,0x80B2E4CFU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_bowl_mid02_squad_spawnrule
    {66,0,145,0x80B2E4D2U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // cliffside_fallen_inf03_squad_spawnrule
    {66,0,146,0x80B2E4D5U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_bowl_flank01_squad_spawnrule
    {66,0,148,0x80B2E4D9U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_tower_mid_sniper01_squad_spawnrule
    {66,0,149,0x80B2E4DCU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // cliffside_fallen_inf04_squad_spawnrule
    {66,0,150,0x80B2E4DFU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_tower_base_front_squad_spawnrule
    {66,0,152,0x80B2E4E2U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_tower_base_anchor_squad_spawnrule
    {66,0,154,0x80B2E4E6U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_tower_mid_front_squad_spawnrule
    {66,0,155,0x80B2E4E9U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // cliffside_fallen_dropship_spectacle_squad_spawnrule
    {66,0,156,0x80B2E4ECU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_tower_mid_back_squad_spawnrule
    {66,0,158,0x80B2E4EFU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_tower_mid_anchor_squad_spawnrule
    {66,0,160,0x80B2E4F4U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_tower_lower_back_squad_spawnrule
    {66,0,164,0x80B2E4F7U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_tower_stealth_squad_spawnrule
    {66,0,166,0x80B2E4FAU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_wave2_squad_spawnrule
    {66,0,169,0x80B2E4FDU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_assault_pike01a_squad_spawnrule
    {66,0,171,0x80B2E500U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_assault_pike01b_squad_spawnrule
    {66,0,172,0x80B2E503U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_assault_inf01_squad_spawnrule
    {58,0,173,0x80B2E507U,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // cliffside_fallen_dropship_spectacle_enter_command
    {66,0,174,0x80B2E50AU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_assault_inf02_squad_spawnrule
    {66,0,177,0x80B2E50DU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_dropship01_squad_spawnrule
    {66,0,180,0x80B2E510U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_assault_dropship01_squad_spawnrule
    {66,0,183,0x80B2E513U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // outpost_fallen_assault_dropship02_squad_spawnrule
    {66,0,186,0x80B2E516U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // alleys_b_tunnel_2_shank_squad_1_spawnrule
    {66,0,198,0x80B2E51AU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // alleys_b_tunnel_2_mid_squad_spawnrule
    {66,0,199,0x80B2E52AU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // lair_fallen_cloaked1_squad_spawnrule
    {66,0,201,0x80B2E534U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // alleys_b_tunnel_2_shank_squad_2_spawnrule
    {66,0,202,0x80B2E537U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // lair_fallen_cloaked2_squad_spawnrule
    {66,0,204,0x80B2E53AU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // lair_fallen_cloaked3_squad_spawnrule
    {66,0,206,0x80B2E53DU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // lair_fallen_inf01_squad_spawnrule
    {66,0,224,0x80B2E540U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // coastroad_fallen_hill01_squad_spawnrule
    {66,0,226,0x80B2E544U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // coastroad_fallen_pike01_squad_spawnrule
    {66,0,228,0x80B2E547U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // coastroad_fallen_pike02a_squad_spawnrule
    {66,0,230,0x80B2E54AU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // coastroad_fallen_pike02b_squad_spawnrule
    {66,0,232,0x80B2E54DU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // coastroad_fallen_bridge01_squad_spawnrule
    {66,0,234,0x80B2E550U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // coastroad_fallen_exittransition01_squad_spawnrule
    {66,0,236,0x80B2E55EU,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // coastroad_fallen_exittransition02_squad_spawnrule
    {66,0,238,0x80B2E561U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // coastroad_fallen_island01_squad_spawnrule
    {66,0,241,0x80B2E564U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // coastroad_fallen_gunship01_squad_spawnrule
    {58,0,256,0x80B2E568U,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // coastroad_fallen_gunship01_enter_command
    {58,0,257,0x80B2E56FU,0x000001F8U,0x80807D9BU,0xFFFFFFFFU,0xFFFFFFFFU}, // coastroad_fallen_gunship01_exit_command
    {57,0,266,0x80B2E6BDU,0x000001F8U,0x808094D7U,0xFFFFFFFFU,0xFFFFFFFFU}, // alleys_b
    {66,0,289,0x80B2E572U,0x00000308U,0x808094CFU,0xFFFFFFFFU,0xFFFFFFFFU}, // cliffside_fallen_sniper01_squad_spawnrule
};
inline constexpr Slot kSlots7[]{
    {31,2,0,0x80B2E6C3U,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // _player_trigger
};
inline constexpr Slot kSlots8[]{
    {31,2,0,0x80B2E6CBU,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // ginger_alleys_b_goto_observatory_trigger
};
inline constexpr Slot kSlots9[]{
    {31,2,0,0x80B2E6D1U,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // _directive_trigger
};
inline constexpr Slot kSlots10[]{
    {65,3,0,0x80B2E6D7U,0x00000258U,0x80804D31U,0x80804D3EU,0x80804D3FU}, // osiris_ghost_revive_ghostlink
};
inline constexpr Slot kSlots11[]{
    {31,2,0,0x80B2E6F7U,0x00000218U,0x80809522U,0xFFFFFFFFU,0x80809524U}, // ginger_town_goto_alleys_a_trigger
};
inline constexpr Group kGroups[]{
    {0xC9BC773AU,0x80B2ED51U,649,true,0,kSlots0},
    {0xEB7AF018U,0x80B2E5F8U,650,false,0,kSlots1},
    {0x4DDB8242U,0x80B2E62AU,651,false,0,kSlots2},
    {0x40ADE010U,0x80B2E66AU,652,false,0,kSlots3},
    {0x38C174BBU,0x80B2E67FU,653,false,0,kSlots4},
    {0xECC3696FU,0x80B2E716U,654,false,0,kSlots5},
    {0xEB7AF01BU,0x80B2EC34U,655,false,1,kSlots6},
    {0x9F8CA248U,0x80B2EC45U,656,false,1,kSlots7},
    {0xC91BDFF0U,0x80B2EC52U,657,false,1,kSlots8},
    {0xBC1C972BU,0x80B2EC61U,658,false,1,kSlots9},
    {0x27660927U,0x80B2EC6CU,659,false,1,kSlots10},
    {0x3A62993FU,0x80B2ECF3U,660,false,51,kSlots11},
};
struct Point { float x,y,z; };
struct Volume { std::uint32_t registry,tag;std::uint16_t slot;std::string_view name;Point min,max;std::span<const Point> vertices; };
inline constexpr Point kVertices0[]{{896.478088F,391.296539F,138.897247F},{966.506287F,313.954071F,138.897247F},{1005.26294F,349.78009F,138.897247F},{1033.44019F,450.699005F,138.897247F},{979.219177F,479.737366F,138.897247F},{940.142517F,494.271423F,138.897247F},{903.249939F,467.000519F,138.897247F},{888.018677F,444.159241F,138.897247F},{878.767639F,412.604736F,138.897247F}};
inline constexpr Point kVertices1[]{{835.426392F,489.091217F,127.115784F},{802.921326F,460.019409F,127.115784F},{840.648193F,439.021332F,127.115784F},{856.866333F,454.989716F,127.115784F},{863.553406F,485.413818F,127.115784F}};
inline constexpr Point kVertices2[]{{886.184814F,482.667664F,127.115784F},{864.112915F,444.342041F,127.115784F},{890.324707F,418.785492F,127.115784F},{916.055115F,464.523438F,127.115784F}};
inline constexpr Point kVertices3[]{{925.370911F,479.352844F,137.625534F},{883.46344F,429.274323F,137.625534F},{909.005249F,401.960083F,137.625534F},{952.170288F,473.058624F,137.625534F}};
inline constexpr Point kVertices4[]{{800.667542F,462.085236F,123.914017F},{841.625183F,438.507629F,123.914017F},{863.208008F,404.270538F,123.914017F},{966.051025F,300.67041F,123.914017F},{1023.67474F,331.043518F,123.914017F},{1007.44067F,378.209076F,123.914017F},{1053.95105F,457.782501F,123.914017F},{956.80127F,523.607666F,123.914032F},{824.978699F,502.235474F,123.914017F}};
inline constexpr Point kVertices5[]{{704.183167F,168.471588F,82.1107788F},{729.818604F,166.969696F,82.1107788F},{752.206909F,158.880859F,82.1107788F},{790.461548F,191.062897F,82.1107788F},{763.452759F,222.915009F,82.1107788F},{685.931885F,217.340897F,82.1107788F},{685.86615F,184.011612F,82.1107788F},{690.621338F,175.171539F,82.1107788F}};
inline constexpr Point kVertices6[]{{803.246216F,132.363922F,77.5656281F},{822.814331F,110.135231F,77.5656281F},{865.71582F,78.7446823F,77.5656281F},{945.406433F,80.0869827F,77.5656281F},{955.947449F,209.028641F,77.5656281F},{871.514099F,290.543854F,77.5656281F},{841.728516F,242.017838F,77.5656281F},{859.270813F,209.654816F,77.5656433F},{823.162292F,188.913666F,77.5656281F}};
inline constexpr Point kVertices7[]{{732.479614F,317.107635F,91.3189087F},{702.671204F,315.763031F,91.3189087F},{702.831909F,284.481995F,91.3189087F},{732.753784F,283.659546F,91.3189087F}};
inline constexpr Point kVertices8[]{{730.603943F,287.090973F,82.5816574F},{700.795532F,285.746368F,82.5816574F},{702.831909F,212.885269F,82.5816574F},{732.753784F,212.06282F,82.5816574F}};
inline constexpr Point kVertices9[]{{926.103271F,239.554779F,97.061348F},{946.499634F,282.653839F,97.061348F},{896.928528F,291.661713F,97.061348F},{893.288574F,273.628662F,97.061348F}};
inline constexpr Point kVertices10[]{{877.260986F,219.929138F,97.061348F},{909.242798F,235.756866F,97.061348F},{890.605103F,274.66748F,97.061348F},{858.596191F,259.565247F,97.061348F}};
inline constexpr Point kVertices11[]{{865.686157F,205.26445F,97.061348F},{904.353638F,228.258224F,97.061348F},{890.256226F,235.456131F,97.061348F},{893.633728F,274.674957F,97.061348F},{848.832886F,247.096207F,97.061348F}};
inline constexpr Point kVertices12[]{{942.845642F,269.740784F,96.0448151F},{951.349182F,308.659149F,96.0448151F},{905.822327F,326.174957F,96.0448151F},{884.939697F,293.2117F,96.0448151F}};
inline constexpr Point kVertices13[]{{894.253052F,280.569061F,94.298027F},{836.585205F,252.371613F,94.298027F},{873.590393F,176.85907F,94.298027F},{887.85144F,176.43248F,94.298027F},{898.276917F,183.617981F,94.298027F},{900.389343F,197.745499F,94.298027F},{898.302185F,216.752808F,94.298027F},{900.987F,248.200562F,94.298027F}};
inline constexpr Point kVertices14[]{{839.620667F,156.345718F,94.298027F},{839.368774F,147.352158F,94.298027F},{846.323059F,137.389053F,94.298027F},{856.908691F,136.971024F,94.298027F},{864.634766F,145.212463F,94.298027F},{865.272522F,158.150146F,94.298027F},{856.484131F,167.375702F,94.298027F},{846.00647F,166.799637F,94.298027F}};
inline constexpr Point kVertices15[]{{832.17627F,128.348541F,94.298027F},{831.482605F,107.442436F,94.298027F},{856.976257F,103.00177F,94.298027F},{857.007874F,82.0511932F,94.298027F},{875.165588F,82.405899F,94.298027F},{875.082886F,128.872009F,94.298027F},{864.13739F,137.314026F,94.298027F},{852.732361F,136.185989F,94.298027F}};
inline constexpr Point kVertices16[]{{897.420654F,130.912903F,91.6211548F},{897.168762F,121.919342F,91.6211548F},{906.751465F,115.917709F,91.6211548F},{914.723083F,114.54425F,91.6211548F},{924.516052F,119.631622F,91.6211548F},{925.153809F,132.569305F,91.6211548F},{914.898315F,140.954559F,91.6211548F},{905.973816F,140.567383F,91.6211548F}};
inline constexpr Point kVertices17[]{{903.8302F,157.687881F,91.6211548F},{903.578308F,148.694321F,91.6211548F},{912.773071F,138.81308F,91.6211548F},{920.74469F,138.731277F,91.6211548F},{930.154541F,146.406601F,91.6211548F},{930.16687F,159.344284F,91.6211548F},{920.919922F,167.605896F,91.6211548F},{911.995422F,167.218719F,91.6211548F}};
inline constexpr Point kVertices18[]{{873.12793F,154.614487F,91.6211548F},{872.876038F,145.620926F,91.6211548F},{882.070801F,135.739685F,91.6211548F},{890.042419F,135.657883F,91.6211548F},{899.452271F,143.333206F,91.6211548F},{899.4646F,156.270889F,91.6211548F},{890.217651F,164.532501F,91.6211548F},{881.293152F,164.145325F,91.6211548F}};
inline constexpr Point kVertices19[]{{855.551697F,323.274109F,109.384033F},{843.435608F,311.066284F,109.384033F},{867.868042F,282.889008F,109.384033F},{880.873047F,294.781433F,109.384033F}};
inline constexpr Point kVertices20[]{{761.471008F,312.490295F,92.7057495F},{741.963379F,311.208191F,92.7057495F},{741.661804F,286.960663F,92.7057495F},{761.282898F,286.075714F,92.7057495F}};
inline constexpr Point kVertices21[]{{889.46344F,342.588043F,109.875183F},{833.242981F,341.305939F,109.875183F},{851.777954F,319.57785F,109.875183F},{887.98761F,316.173462F,109.875183F}};
inline constexpr Point kVertices22[]{{1136.5719F,342.014893F,144.122223F},{1116.45032F,317.83313F,144.122223F},{1137.2594F,297.711853F,144.122223F},{1161.79895F,326.109314F,144.122223F}};
inline constexpr Point kVertices23[]{{1005.07629F,418.629578F,149.235992F},{996.264221F,403.510193F,149.235992F},{1012.82776F,393.553894F,149.235992F},{1022.07764F,411.477386F,149.235992F}};
inline constexpr Point kVertices24[]{{665.950623F,233.108704F,81.5798111F},{665.944031F,161.473694F,81.5798111F},{674.62262F,161.757782F,81.5798111F},{675.745239F,135.638611F,81.5798111F},{785.949097F,140.011963F,81.5798111F},{784.384094F,233.113419F,81.5798111F}};
inline constexpr Point kVertices25[]{{679.586548F,313.13504F,86.265976F},{683.368835F,231.450714F,86.265976F},{736.133423F,231.171616F,86.265976F},{736.242004F,312.600922F,86.265976F}};
inline constexpr Point kVertices26[]{{862.226318F,483.064056F,135.185867F},{860.673645F,461.135712F,135.185867F},{871.776184F,448.425415F,135.185867F},{889.74884F,477.71405F,135.185867F}};
inline constexpr Point kVertices27[]{{1011.86993F,383.924469F,119.62056F},{1026.73132F,475.052246F,119.62056F},{868.329163F,528.815002F,119.62056F},{855.472351F,426.292542F,119.62056F},{944.62854F,330.24118F,119.62056F}};
inline constexpr Point kVertices28[]{{664.89563F,158.635544F,79.958313F},{681.830688F,158.842239F,79.958313F},{682.170532F,138.178024F,79.958313F},{759.753296F,136.944183F,79.958313F},{796.880859F,199.559464F,79.958313F},{741.340393F,240.84729F,79.958313F},{703.337952F,240.85466F,79.958313F},{674.826904F,213.606323F,79.958313F},{664.762512F,170.049255F,79.958313F}};
inline constexpr Point kVertices29[]{{701.35553F,252.806763F,82.7563934F},{705.137817F,230.733856F,82.7563934F},{736.133423F,230.454758F,82.7563934F},{736.242004F,252.272644F,82.7563934F}};
inline constexpr Point kVertices30[]{{1319.40955F,539.242798F,165.739685F},{1373.2937F,508.759796F,165.739685F},{1523.07092F,547.49115F,165.739685F},{1532.94519F,592.003662F,165.739685F},{1477.69849F,715.684143F,165.73967F},{1290.76379F,706.381958F,165.73967F},{1306.34839F,681.907227F,165.73967F},{1348.16907F,658.273499F,165.73967F}};
inline constexpr Point kVertices31[]{{1372.30188F,549.746643F,172.083481F},{1376.63477F,556.230103F,172.083481F},{1385.53162F,550.286621F,172.083481F},{1381.19873F,543.803162F,172.083481F},{1388.43311F,539.028564F,172.083481F},{1398.64587F,527.838745F,172.083481F},{1525.94409F,607.999207F,172.083481F},{1472.73877F,707.908936F,172.083481F},{1393.71094F,715.159729F,172.083481F},{1351.37683F,680.785522F,172.083481F},{1339.72717F,571.661499F,172.083481F}};
inline constexpr Point kVertices32[]{{1420.92273F,572.474243F,186.580582F},{1407.81885F,593.85376F,186.580582F},{1383.60413F,598.351318F,186.580582F},{1352.9126F,583.130188F,186.580582F},{1336.80273F,558.31958F,186.580582F},{1390.33899F,523.786926F,186.580582F},{1410.5321F,549.723267F,186.580582F}};
inline constexpr Point kVertices33[]{{1406.3584F,560.478149F,191.772095F},{1377.56543F,581.093628F,191.772095F},{1353.79639F,579.575623F,191.772095F},{1334.97925F,548.431458F,191.772095F},{1379.30505F,518.906982F,191.772095F}};
inline constexpr Point kVertices34[]{{1398.08569F,557.471375F,204.168015F},{1376.61401F,571.332397F,204.168015F},{1352.76624F,537.222778F,204.168015F},{1375.34094F,522.360474F,204.168015F}};
inline constexpr Point kVertices35[]{{1375.41309F,522.649231F,204.547165F},{1385.30103F,537.922302F,204.547165F},{1364.55273F,552.688843F,204.547165F},{1353.52258F,537.469177F,204.547165F}};
inline constexpr Point kVertices36[]{{1379.78162F,535.022827F,209.291733F},{1387.72095F,547.424011F,209.291733F},{1370.77661F,559.14386F,209.291733F},{1361.91846F,546.592163F,209.291733F}};
inline constexpr Point kVertices37[]{{1407.18994F,532.919861F,180.861588F},{1447.14062F,586.858643F,180.861588F},{1452.38794F,603.670349F,180.861588F},{1473.53284F,659.651489F,180.861588F},{1434.22705F,693.180481F,180.861588F},{1382.85461F,703.568481F,180.861588F},{1357.53137F,671.034241F,180.861588F},{1325.3877F,558.151245F,180.861588F},{1387.83972F,514.32428F,180.861588F}};
inline constexpr Point kVertices38[]{{1156.68079F,409.182495F,149.148834F},{1132.35132F,420.432831F,149.148834F},{1112.84399F,365.45575F,149.148834F},{1121.91956F,338.454651F,149.148834F},{1157.9967F,357.53363F,149.148834F}};
inline constexpr Point kVertices39[]{{1168.53003F,425.240143F,149.148834F},{1135.81873F,438.802704F,149.148834F},{1128.5603F,417.24295F,149.148834F},{1160.06982F,403.986877F,149.148834F}};
inline constexpr Point kVertices40[]{{1140.24597F,551.492004F,159.816376F},{1113.05322F,534.475342F,159.816376F},{1165.54016F,493.787384F,159.816376F},{1197.95081F,510.347473F,159.816376F}};
inline constexpr Point kVertices41[]{{1176.96655F,551.63916F,159.816376F},{1143.30322F,537.94574F,159.816376F},{1163.02832F,494.904114F,159.816376F},{1201.29285F,518.288269F,159.816376F}};
inline constexpr Point kVertices42[]{{1132.67834F,435.225403F,154.453857F},{1099.01501F,421.531982F,154.453857F},{1132.45618F,388.165405F,154.453857F},{1170.7207F,411.549561F,154.453857F}};
inline constexpr Point kVertices43[]{{1565.62939F,480.158936F,79.4263458F},{1286.29834F,660.27594F,79.4263458F},{1116.28333F,540.178467F,79.4263458F},{1433.47729F,287.638702F,79.4263458F}};
inline constexpr Point kVertices44[]{{1399.31567F,568.245422F,174.115417F},{1387.34851F,576.241394F,174.115417F},{1379.38794F,564.219421F,174.115417F},{1391.35437F,556.367004F,174.115417F}};
inline constexpr Point kVertices45[]{{1408.177F,581.08429F,174.115417F},{1396.20984F,589.080261F,174.115417F},{1382.0647F,567.78186F,174.115417F},{1394.03113F,559.929443F,174.115417F}};
inline constexpr Point kVertices46[]{{1410.04578F,603.317627F,171.558319F},{1399.17957F,586.939697F,171.558319F},{1415.33899F,576.573792F,171.558319F},{1426.02148F,592.9776F,171.558319F}};
inline constexpr Point kVertices47[]{{1211.68677F,568.917419F,167.747269F},{1206.07153F,561.953979F,167.747269F},{1217.17102F,553.078735F,167.747269F},{1222.07593F,558.072693F,167.747269F}};
inline constexpr Point kVertices48[]{{1291.20557F,700.958191F,181.147278F},{1286.45752F,695.078979F,181.147278F},{1297.4386F,686.196838F,181.147278F},{1301.47632F,690.106567F,181.147278F}};
inline constexpr Point kVertices49[]{{1314.51343F,567.088623F,120.489609F},{1277.74512F,514.196411F,120.489609F},{1365.51465F,429.33252F,120.489609F},{1503.96082F,416.796234F,120.489609F},{1512.74023F,453.426819F,120.489609F},{1477.66541F,466.368195F,120.489609F},{1449.71777F,515.177246F,120.489609F},{1436.78284F,515.729126F,120.489609F},{1394.98462F,518.622437F,120.489609F}};
inline constexpr Point kVertices50[]{{1228.7157F,274.805603F,103.727386F},{1359.58435F,339.911194F,103.727386F},{1383.02258F,489.145874F,103.727386F},{1370.5033F,507.514465F,103.727386F},{1309.48718F,488.899475F,103.727386F},{1161.81152F,374.414978F,103.727386F}};
inline constexpr Point kVertices51[]{{1230.40771F,323.131958F,93.9551849F},{1223.07068F,334.328369F,93.9551849F},{1223.67249F,347.332275F,93.9551849F},{1199.12646F,369.398468F,93.9551849F},{1174.10071F,348.40033F,93.9551849F},{1206.78149F,304.021881F,93.9551849F}};
inline constexpr Point kVertices52[]{{1277.73474F,304.708405F,87.798378F},{1247.95227F,378.146759F,87.798378F},{1256.42236F,384.916687F,87.798378F},{1249.10046F,393.526581F,87.798378F},{1234.33667F,381.829742F,87.798378F},{1208.83276F,390.289276F,87.798378F},{1176.34644F,350.562744F,87.798378F},{1228.19824F,280.688538F,87.798378F}};
inline constexpr Point kVertices53[]{{1071.90381F,709.331299F,69.6288605F},{1165.51794F,94.7795715F,69.6288605F},{2010.29114F,226.116257F,69.6288605F},{2025.41199F,933.804077F,69.6288605F}};
inline constexpr Point kVertices54[]{{1409.99878F,603.946106F,171.305817F},{1397.65247F,585.215393F,171.305817F},{1414.42639F,573.977295F,171.305817F},{1426.85461F,592.935791F,171.305817F}};
inline constexpr Point kVertices55[]{{1407.61707F,580.996155F,173.337051F},{1410.40173F,585.203003F,173.337051F},{1406.02686F,588.086548F,173.337051F},{1403.177F,583.903809F,173.337051F}};
inline constexpr Point kVertices56[]{{1377.14319F,538.527466F,186.749451F},{1383.73669F,548.501831F,186.749451F},{1375.61328F,553.893982F,186.749451F},{1368.95459F,543.943726F,186.749451F}};
inline constexpr Point kVertices57[]{{1376.36206F,698.468872F,180.219269F},{1356.24048F,674.287109F,180.219269F},{1377.04956F,654.165833F,180.219269F},{1401.58911F,682.563293F,180.219269F}};
inline constexpr Point kVertices58[]{{1312.99683F,566.875366F,182.103668F},{1405.74438F,503.131897F,182.103668F},{1532.27905F,571.757629F,182.103668F},{1463.72559F,684.139343F,182.103668F},{1386.953F,708.554993F,182.103668F},{1354.03101F,664.360413F,182.103668F}};
inline constexpr Point kVertices59[]{{1499.86609F,577.859131F,185.341827F},{1512.42017F,678.321777F,185.341843F},{1414.33936F,688.350708F,185.341843F},{1395.48633F,607.632812F,185.341843F},{1386.67407F,604.236511F,185.341843F},{1383.99695F,593.924561F,185.341843F},{1374.3783F,598.52478F,185.341843F},{1351.01575F,598.127075F,185.341843F},{1326.66101F,557.569824F,185.341843F},{1376.41235F,514.265686F,185.341843F}};
inline constexpr Point kVertices60[]{{1377.45862F,539.277832F,193.662613F},{1382.9176F,547.829956F,193.662613F},{1375.23352F,553.15979F,193.662613F},{1369.56812F,544.631104F,193.662613F}};
inline constexpr Point kVertices61[]{{1409.99878F,603.946106F,171.305817F},{1397.65247F,585.215393F,171.305817F},{1414.42639F,573.977295F,171.305817F},{1426.85461F,592.935791F,171.305817F}};
inline constexpr Point kVertices62[]{{1409.99878F,603.946106F,171.305817F},{1398.50403F,586.486267F,171.305817F},{1415.27795F,575.248169F,171.305817F},{1426.85461F,592.935791F,171.305817F}};
inline constexpr Point kVertices63[]{{1409.99878F,603.946106F,171.305817F},{1398.50403F,586.486267F,171.305817F},{1415.27795F,575.248169F,171.305817F},{1426.85461F,592.935791F,171.305817F}};
inline constexpr Point kVertices64[]{{596.036316F,145.692001F,72.6515198F},{596.408264F,142.239334F,72.6515198F},{595.023132F,142.203522F,72.6515198F},{594.642761F,145.49028F,72.6515198F},{596.004578F,145.715118F,72.6515198F},{599.127991F,147.571457F,72.6515198F},{591.244873F,146.483383F,72.6515198F},{591.682556F,139.412872F,72.6515198F},{600.397888F,139.343552F,72.6515198F},{599.152771F,147.479294F,72.6515198F}};
inline constexpr Point kVertices65[]{{679.686523F,109.798843F,80.0033264F},{679.686523F,105.444206F,80.0033264F},{684.206299F,105.444206F,80.0033264F},{684.206299F,109.798843F,80.0033264F}};
inline constexpr Point kVertices66[]{{652.898254F,156.478165F,81.5798111F},{652.865173F,133.624878F,81.5798111F},{678.664368F,133.924759F,81.5798111F},{678.640808F,156.498672F,81.5798111F}};
inline constexpr Volume kVolumes[]{
    {0xEB7AF018U,0x80B2E2B5U,130,"overpass_fallen_spider01_fallback_volume",{878.767639F,313.954071F,138.897247F},{1033.44019F,494.271423F,160.2603F},kVertices0},
    {0xEB7AF018U,0x80B2E2B5U,131,"overpass_encounter_start_volume",{802.921326F,439.021332F,127.115784F},{863.553406F,489.091217F,150.663559F},kVertices1},
    {0xEB7AF018U,0x80B2E2B5U,132,"overpass_encounter_dropship_spawn_volume",{864.112915F,418.785492F,127.115784F},{916.055115F,482.667664F,150.663559F},kVertices2},
    {0xEB7AF018U,0x80B2E2B5U,134,"overpass_encounter_front_fallback_volume",{883.46344F,401.960083F,137.625534F},{952.170288F,479.352844F,161.173309F},kVertices3},
    {0xEB7AF018U,0x80B2E2B5U,141,"overpass_spawnoverridevolume",{800.667542F,300.67041F,123.914017F},{1053.95105F,523.607666F,163.914032F},kVertices4},
    {0xEB7AF018U,0x80B2E2B5U,175,"hub_fallen_inf01a_fallback_volume",{685.86615F,158.880859F,82.1107788F},{790.461548F,222.915009F,95.5538177F},kVertices5},
    {0xEB7AF018U,0x80B2E2B5U,211,"waterfront_spawnoverridevolume",{803.246216F,78.7446823F,77.5656281F},{955.947449F,290.543854F,117.565643F},kVertices6},
    {0xEB7AF018U,0x80B2E2B5U,214,"streets_fallen_shank_horde1_spawn_volume",{702.671204F,283.659546F,91.3189087F},{732.753784F,317.107635F,112.318909F},kVertices7},
    {0xEB7AF018U,0x80B2E2B5U,215,"streets_dropship_dummy01_spawn_volume",{700.795532F,212.06282F,82.5816574F},{732.753784F,287.090973F,103.581657F},kVertices8},
    {0xEB7AF018U,0x80B2E2B5U,216,"waterfront_pikes_spawn_volume",{893.288574F,239.554779F,97.061348F},{946.499634F,291.661713F,118.061348F},kVertices9},
    {0xEB7AF018U,0x80B2E2B5U,217,"waterfront_pikes_fallback_volume",{858.596191F,219.929138F,97.061348F},{909.242798F,274.66748F,118.061348F},kVertices10},
    {0xEB7AF018U,0x80B2E2B5U,218,"waterfront_encounter_start_volume",{848.832886F,205.26445F,97.061348F},{904.353638F,274.674957F,118.061348F},kVertices11},
    {0xEB7AF018U,0x80B2E2B5U,219,"waterfront_guardian_tank_drop_volume",{884.939697F,269.740784F,96.0448151F},{951.349182F,326.174957F,118.044815F},kVertices12},
    {0xEB7AF018U,0x80B2E2B5U,220,"spider_teleport_avoidance_volume[0]",{836.585205F,176.43248F,94.298027F},{900.987F,280.569061F,111.298027F},kVertices13},
    {0xEB7AF018U,0x80B2E2B5U,221,"spider_teleport_avoidance_volume[1]",{839.368774F,136.971024F,94.298027F},{865.272522F,167.375702F,111.298027F},kVertices14},
    {0xEB7AF018U,0x80B2E2B5U,222,"spider_teleport_avoidance_volume[2]",{831.482605F,82.0511932F,94.298027F},{875.165588F,137.314026F,111.298027F},kVertices15},
    {0xEB7AF018U,0x80B2E2B5U,223,"spider_teleport_avoidance_volume[3]",{897.168762F,114.54425F,91.6211548F},{925.153809F,140.954559F,108.621155F},kVertices16},
    {0xEB7AF018U,0x80B2E2B5U,224,"spider_teleport_avoidance_volume[4]",{903.578308F,138.731277F,91.6211548F},{930.16687F,167.605896F,108.621155F},kVertices17},
    {0xEB7AF018U,0x80B2E2B5U,225,"spider_teleport_avoidance_volume[5]",{872.876038F,135.657883F,91.6211548F},{899.4646F,164.532501F,108.621155F},kVertices18},
    {0xEB7AF018U,0x80B2E2B5U,226,"streets_fallen_shank_horde2_spawn_volume",{843.435608F,282.889008F,109.384033F},{880.873047F,323.274109F,130.384033F},kVertices19},
    {0xEB7AF018U,0x80B2E2B5U,228,"streets_fallen_inf01_spawn_volume",{741.661804F,286.075714F,92.7057495F},{761.471008F,312.490295F,113.70575F},kVertices20},
    {0xEB7AF018U,0x80B2E2B5U,229,"streets_fallen_chokepoint01_spawn_volume",{833.242981F,316.173462F,109.875183F},{889.46344F,342.588043F,130.875183F},kVertices21},
    {0x4DDB8242U,0x80B2E47DU,1,"_directive_volume",{1116.45032F,297.711853F,144.122223F},{1161.79895F,342.014893F,165.740067F},kVertices22},
    {0x4DDB8242U,0x80B2E47DU,2,"edz_a_ginger_alleys_a_060_filter",{996.264221F,393.553894F,149.235992F},{1022.07764F,418.629578F,162.501816F},kVertices23},
    {0x40ADE010U,0x80B2E485U,3,"ginger_alleys_a_goto_volume",{665.944031F,135.638611F,81.5798111F},{785.949097F,233.113419F,111.579811F},kVertices24},
    {0x38C174BBU,0x80B2E491U,2,"edz_a_ginger_town_020_filter",{679.586548F,231.171616F,86.265976F},{736.242004F,313.13504F,107.265976F},kVertices25},
    {0x38C174BBU,0x80B2E491U,4,"ginger_alleys_a_goto_tank_volume",{860.673645F,448.425415F,135.185867F},{889.74884F,483.064056F,155.185867F},kVertices26},
    {0xE4BA2E54U,0x80B2E499U,1,"ginger_alleys_a_kill_tank_waypoint_volume",{855.472351F,330.24118F,119.62056F},{1026.73132F,528.815002F,179.62056F},kVertices27},
    {0xECC3696FU,0x80B2E49CU,2,"_waypoint_volume",{664.762512F,136.944183F,79.958313F},{796.880859F,240.85466F,109.958313F},kVertices28},
    {0xECC3696FU,0x80B2E49CU,5,"ginger_alleys_a_steal_pikes_trigger_volume",{701.35553F,230.454758F,82.7563934F},{736.242004F,252.806763F,103.756393F},kVertices29},
    {0xEB7AF01BU,0x80B2E575U,121,"outpost_fallen_init_volume",{1290.76379F,508.759796F,165.73967F},{1532.94519F,715.684143F,215.739685F},kVertices30},
    {0xEB7AF01BU,0x80B2E575U,122,"outpost_fallen_ambush_volume",{1339.72717F,527.838745F,172.083481F},{1525.94409F,715.159729F,224.488541F},kVertices31},
    {0xEB7AF01BU,0x80B2E575U,123,"outpost_fallback_volume_mid",{1336.80273F,523.786926F,186.580582F},{1420.92273F,598.351318F,206.580582F},kVertices32},
    {0xEB7AF01BU,0x80B2E575U,124,"outpost_fallback_volume_tower",{1334.97925F,518.906982F,191.772095F},{1406.3584F,581.093628F,211.772095F},kVertices33},
    {0xEB7AF01BU,0x80B2E575U,125,"outpost_fallback_volume_tower_mid",{1352.76624F,522.360474F,204.168015F},{1398.08569F,571.332397F,224.168015F},kVertices34},
    {0xEB7AF01BU,0x80B2E575U,126,"outpsot_fallback_front_volume",{1353.52258F,522.649231F,204.547165F},{1385.30103F,552.688843F,224.547165F},kVertices35},
    {0xEB7AF01BU,0x80B2E575U,127,"outpsot_mid_back_expand_volume",{1361.91846F,535.022827F,209.291733F},{1387.72095F,559.14386F,219.291733F},kVertices36},
    {0xEB7AF01BU,0x80B2E575U,136,"alleys_b_top_spawn_override_volume",{1325.3877F,514.32428F,180.861588F},{1473.53284F,703.568481F,225.861588F},kVertices37},
    {0xEB7AF01BU,0x80B2E575U,157,"cliffside_fallen_spawn_volume",{1112.84399F,338.454651F,149.148834F},{1157.9967F,420.432831F,170.766663F},kVertices38},
    {0xEB7AF01BU,0x80B2E575U,159,"cliffside_fallen_dropship_spawn_volume",{1128.5603F,403.986877F,149.148834F},{1168.53003F,438.802704F,170.766663F},kVertices39},
    {0xEB7AF01BU,0x80B2E575U,162,"cliffside_fallen_inf02_fallback_volume",{1113.05322F,493.787384F,159.816376F},{1197.95081F,551.492004F,181.434204F},kVertices40},
    {0xEB7AF01BU,0x80B2E575U,163,"cliffside_fallen_inf04_fallback_volume",{1143.30322F,494.904114F,159.816376F},{1201.29285F,551.63916F,181.434204F},kVertices41},
    {0xEB7AF01BU,0x80B2E575U,165,"alleys_b_goto_observatory_end_trigger_volume",{1099.01501F,388.165405F,154.453857F},{1170.7207F,435.225403F,176.071686F},kVertices42},
    {0xEB7AF01BU,0x80B2E575U,185,"outpost_fallen_tower_mid_anchor_volume",{1116.28333F,287.638702F,79.4263458F},{1565.62939F,660.27594F,169.426346F},kVertices43},
    {0xEB7AF01BU,0x80B2E575U,195,"lair_fallen_spawn_volume",{1379.38794F,556.367004F,174.115417F},{1399.31567F,576.241394F,185.115417F},kVertices44},
    {0xEB7AF01BU,0x80B2E575U,196,"lair_fallen_advance_volume",{1382.0647F,559.929443F,174.115417F},{1408.177F,589.080261F,185.115417F},kVertices45},
    {0xEB7AF01BU,0x80B2E575U,209,"weapon_down_volume",{1399.17957F,576.573792F,171.558319F},{1426.02148F,603.317627F,186.558319F},kVertices46},
    {0xEB7AF01BU,0x80B2E575U,223,"alleys_b_tunnel_2_spawn_front_ai_trigger_volume",{1206.07153F,553.078735F,167.747269F},{1222.07593F,568.917419F,178.747269F},kVertices47},
    {0xEB7AF01BU,0x80B2E575U,225,"alleys_b_tunnel_2_spawn_rear_ai_trigger_volume",{1286.45752F,686.196838F,181.147278F},{1301.47632F,700.958191F,192.147278F},kVertices48},
    {0xEB7AF01BU,0x80B2E575U,252,"coastroad_fallen_pike01_volume",{1277.74512F,416.796234F,120.489609F},{1512.74023F,567.088623F,180.489609F},kVertices49},
    {0xEB7AF01BU,0x80B2E575U,253,"coastroad_fallen_gunship01_volume",{1161.81152F,274.805603F,103.727386F},{1383.02258F,507.514465F,143.727386F},kVertices50},
    {0xEB7AF01BU,0x80B2E575U,254,"coastroad_fallen_fallback_tunnel01_volume",{1174.10071F,304.021881F,93.9551849F},{1230.40771F,369.398468F,133.955185F},kVertices51},
    {0xEB7AF01BU,0x80B2E575U,255,"coastroad_fallen_fallback_sniper01_volume",{1176.34644F,280.688538F,87.798378F},{1277.73474F,393.526581F,127.798378F},kVertices52},
    {0xEB7AF01BU,0x80B2E575U,260,"killvolume",{1071.90381F,94.7795715F,69.6288605F},{2025.41199F,933.804077F,79.6288605F},kVertices53},
    {0x9F8CA248U,0x80B2E6C0U,1,"_directive_waypoint_volume",{1397.65247F,573.977295F,171.305817F},{1426.85461F,603.946106F,186.305817F},kVertices54},
    {0x9F8CA248U,0x80B2E6C0U,2,"_trigger_volume",{1403.177F,580.996155F,173.337051F},{1410.40173F,588.086548F,179.337051F},kVertices55},
    {0x9F8CA248U,0x80B2E6C0U,3,"drop_down_elevator_music_filter",{1368.95459F,538.527466F,186.749451F},{1383.73669F,553.893982F,192.749451F},kVertices56},
    {0xC91BDFF0U,0x80B2E6C7U,1,"ginger_alleys_b_goto_observatory_volume",{1356.24048F,654.165833F,180.219269F},{1401.58911F,698.468872F,201.837097F},kVertices57},
    {0xBC1C972BU,0x80B2E6CEU,1,"ginger_alleys_b_observatory_destroy_waypoint_volume",{1312.99683F,503.131897F,182.103668F},{1532.27905F,708.554993F,222.103668F},kVertices58},
    {0xBC1C972BU,0x80B2E6CEU,2,"edz_a_ginger_alleys_b_030_filter",{1326.66101F,514.265686F,185.341827F},{1512.42017F,688.350708F,225.341843F},kVertices59},
    {0xBC1C972BU,0x80B2E6CEU,3,"_directive_volume",{1369.56812F,539.277832F,193.662613F},{1382.9176F,553.15979F,203.662613F},kVertices60},
    {0x27660927U,0x80B2E6D4U,1,"_directive_waypoint_volume",{1397.65247F,573.977295F,171.305817F},{1426.85461F,603.946106F,186.305817F},kVertices61},
    {0x27660927U,0x80B2E6D4U,2,"edz_a_ginger_alleys_b_090_filter",{1398.50403F,575.248169F,171.305817F},{1426.85461F,603.946106F,186.305817F},kVertices62},
    {0x27660927U,0x80B2E6D4U,3,"edz_a_ginger_alleys_b_100_filter",{1398.50403F,575.248169F,171.305817F},{1426.85461F,603.946106F,186.305817F},kVertices63},
    {0x3A62993FU,0x80B2E6F3U,2,"edz_a_ginger_town_010_filter",{591.244873F,139.343552F,72.6515198F},{600.397888F,147.571457F,89.6515198F},kVertices64},
    {0x3A62993FU,0x80B2E6F3U,3,"edz_a_ginger_town_020_filter",{679.686523F,105.444206F,80.0033264F},{684.206299F,109.798843F,85.0033264F},kVertices65},
    {0x3A62993FU,0x80B2E6F3U,7,"ginger_town_goto_alleys_a_volume",{652.865173F,133.624878F,81.5798111F},{678.664368F,156.498672F,111.579811F},kVertices66},
};
inline constexpr coo::DialogueRow kDialogueRows[]{
    {0x58AB97A6U,13902,0,false},
    {0x840B83B9U,16542,0,false},
    {0xC68397C7U,10321,0,false},
    {0x5A59F546U,0,0,false},
    {0x84E4694BU,8292,0,false},
    {0xCD1C8D84U,3007,0,false},
    {0x5FAA450CU,0,0,false},
    {0x8AD28A71U,3751,0,false},
    {0x6ED5A777U,3497,0,false},
    {0xE053D662U,9086,0,true},
    {0xA9C6FB55U,38675,0,true},
};
inline constexpr coo::DialogueDefinition kDialogue{kBank,kDialogueRows,{}};
inline constexpr std::uint32_t kObjectives[]{0xEC217779U,0xC908B416U,0xDA95AE49U,0x183F9715U,0x6FB8A85AU,0xE58BB2F6U,0x882DD31EU,0x708B9351U,0x2686525DU};
struct Spawn { std::uint16_t source;std::uint32_t registry,definition,offset;std::uint16_t rule;std::uint8_t count,categories,cohort;coo::native_combatant::TacticalGroup tactical;bool required; };
inline constexpr std::array<Spawn,47> kSpawns{{
    {1,0xEB7AF018U,0x80B2E2BCU,0x00000728U,230,1,1,1,{0xEB7AF018U,0,0},true}, // hub_fallen_inf01a_squad
    {2,0xEB7AF018U,0x80B2E2BFU,0x00000728U,112,1,1,1,{0xEB7AF018U,0,0},true}, // hub_fallen_inf01b_squad
    {3,0xEB7AF018U,0x80B2E2C3U,0x00000728U,114,1,1,1,{0xEB7AF018U,0,2},true}, // hub_fallen_inf01c_squad
    {12,0xEB7AF018U,0x80B2E2F2U,0x00000728U,117,2,2,2,{0xEB7AF018U,7,4},false}, // streets_fallen_inf01_squad
    {13,0xEB7AF018U,0x80B2E2F8U,0x00000728U,143,1,1,2,{0xEB7AF018U,7,0},false}, // streets_fallen_first_sniper1_squad
    {14,0xEB7AF018U,0x80B2E2FEU,0x00000728U,145,1,1,2,{0xEB7AF018U,7,1},false}, // streets_fallen_first_sniper2_squad
    {15,0xEB7AF018U,0x80B2E302U,0x00000728U,147,1,1,2,{0xEB7AF018U,7,2},false}, // streets_fallen_shank_horde1_squad
    {16,0xEB7AF018U,0x80B2E308U,0x00000728U,149,1,1,2,{0xEB7AF018U,7,8},false}, // streets_fallen_shank_horde2_squad
    {17,0xEB7AF018U,0x80B2E30EU,0x00000728U,165,1,1,3,{0xEB7AF018U,7,7},false}, // streets_fallen_chokepoint_sniper01_squad
    {18,0xEB7AF018U,0x80B2E314U,0x00000728U,168,1,1,3,{0xEB7AF018U,7,8},false}, // streets_fallen_chokepoint_sniper02_squad
    {19,0xEB7AF018U,0x80B2E318U,0x00000728U,173,1,1,3,{0xEB7AF018U,7,6},false}, // streets_fallen_chokepoint_inf01_squad
    {20,0xEB7AF018U,0x80B2E31EU,0x00000728U,177,1,1,3,{0xEB7AF018U,7,9},false}, // streets_fallen_chokepoint_inf02_squad
    {23,0xEB7AF018U,0x80B2E330U,0x00000728U,93,1,1,4,{0xEB7AF018U,21,1},true}, // overpass_fallen_spider01_squad
    {25,0xEB7AF018U,0x80B2E33AU,0x00000728U,95,2,2,5,{0xEB7AF018U,21,6},false}, // overpass_fallen_front01_squad
    {26,0xEB7AF018U,0x80B2E33EU,0x00000728U,97,2,2,5,{0xEB7AF018U,21,6},false}, // overpass_fallen_bus01_squad
    {27,0xEB7AF018U,0x80B2E344U,0x00000728U,99,1,1,5,{0xEB7AF018U,21,7},false}, // overpass_fallen_pit01_squad
    {28,0xEB7AF018U,0x80B2E34AU,0x00000728U,101,2,2,5,{0xEB7AF018U,21,7},false}, // overpass_fallen_tunnel_defence01_squad
    {31,0xEB7AF018U,0x80B2E35AU,0x00000728U,107,1,1,5,{0xEB7AF018U,21,7},false}, // overpass_fallen_shanks01_squad
    {1,0xEB7AF01BU,0x80B2E57CU,0x00000728U,289,1,1,6,{0xEB7AF01BU,0,0},false}, // cliffside_fallen_sniper01_squad
    {2,0xEB7AF01BU,0x80B2E57FU,0x00000728U,97,1,1,6,{0xEB7AF01BU,0,4},false}, // cliffside_fallen_sniper02_squad
    {3,0xEB7AF01BU,0x80B2E59CU,0x00000728U,99,1,1,6,{0xEB7AF01BU,0,1},false}, // cliffside_fallen_inf01_squad
    {4,0xEB7AF01BU,0x80B2E59FU,0x00000728U,137,1,1,6,{0xEB7AF01BU,0,2},false}, // cliffside_fallen_inf02a_squad
    {5,0xEB7AF01BU,0x80B2E5A2U,0x00000728U,141,1,1,6,{0xEB7AF01BU,0,3},false}, // cliffside_fallen_inf02b_squad
    {6,0xEB7AF01BU,0x80B2E5A5U,0x00000728U,145,2,2,6,{0xEB7AF01BU,0,8},false}, // cliffside_fallen_inf03_squad
    {7,0xEB7AF01BU,0x80B2E5A9U,0x00000728U,149,1,1,6,{0xEB7AF01BU,0,7},false}, // cliffside_fallen_inf04_squad
    {15,0xEB7AF01BU,0x80B2E5BCU,0x00000728U,186,1,1,7,{0xEB7AF01BU,13,0},false}, // alleys_b_tunnel_2_shank_squad_1
    {16,0xEB7AF01BU,0x80B2E5BFU,0x00000728U,198,2,2,7,{0xEB7AF01BU,13,1},false}, // alleys_b_tunnel_2_mid_squad
    {17,0xEB7AF01BU,0x80B2E5C3U,0x00000728U,201,1,1,7,{0xEB7AF01BU,13,2},false}, // alleys_b_tunnel_2_shank_squad_2
    {25,0xEB7AF01BU,0x80B2E5CAU,0x00000728U,138,1,1,8,{0xEB7AF01BU,18,2},true}, // outpost_fallen_tunnel_exit01_squad
    {26,0xEB7AF01BU,0x80B2E5CDU,0x00000728U,140,1,1,8,{0xEB7AF01BU,18,3},true}, // outpost_fallen_tunnel_exit02_squad
    {27,0xEB7AF01BU,0x80B2E5D0U,0x00000728U,142,1,1,8,{0xEB7AF01BU,18,0},true}, // outpost_fallen_bowl_mid01_squad
    {28,0xEB7AF01BU,0x80B2E5D3U,0x00000728U,144,2,2,8,{0xEB7AF01BU,18,0},true}, // outpost_fallen_bowl_mid02_squad
    {29,0xEB7AF01BU,0x80B2E5F0U,0x00000728U,146,2,2,8,{0xEB7AF01BU,18,4},true}, // outpost_fallen_bowl_flank01_squad
    {30,0xEB7AF01BU,0x80B2E5F3U,0x00000728U,148,1,1,8,{0xEB7AF01BU,18,16},true}, // outpost_fallen_tower_mid_sniper01_squad
    {31,0xEB7AF01BU,0x80B2E5F6U,0x00000728U,150,2,2,8,{0xEB7AF01BU,18,15},true}, // outpost_fallen_tower_base_front_squad
    {32,0xEB7AF01BU,0x80B2E5FAU,0x00000728U,152,2,2,8,{0xEB7AF01BU,18,5},true}, // outpost_fallen_tower_base_anchor_squad
    {33,0xEB7AF01BU,0x80B2E5FDU,0x00000728U,154,2,2,8,{0xEB7AF01BU,18,10},true}, // outpost_fallen_tower_mid_front_squad
    {34,0xEB7AF01BU,0x80B2E601U,0x00000728U,156,1,1,8,{0xEB7AF01BU,18,7},true}, // outpost_fallen_tower_mid_back_squad
    {35,0xEB7AF01BU,0x80B2E605U,0x00000728U,156,1,1,8,{0xEB7AF01BU,18,7},true}, // outpost_fallen_tower_mid_anchor_squad
    {36,0xEB7AF01BU,0x80B2E608U,0x00000728U,160,1,1,8,{0xEB7AF01BU,18,12},true}, // outpost_fallen_tower_lower_back_squad
    {37,0xEB7AF01BU,0x80B2E60BU,0x00000728U,164,1,1,8,{0xEB7AF01BU,18,12},true}, // outpost_fallen_tower_stealth1_squad
    {38,0xEB7AF01BU,0x80B2E612U,0x00000728U,164,1,1,8,{0xEB7AF01BU,18,12},true}, // outpost_fallen_tower_stealth2_squad
    {39,0xEB7AF01BU,0x80B2E615U,0x00000728U,164,1,1,8,{0xEB7AF01BU,18,12},true}, // outpost_fallen_tower_stealth3_squad
    {53,0xEB7AF01BU,0x80B2E636U,0x00000728U,199,1,1,9,{0xEB7AF01BU,52,2},true}, // lair_fallen_cloaked1_squad
    {55,0xEB7AF01BU,0x80B2E639U,0x00000728U,202,1,1,9,{0xEB7AF01BU,52,2},true}, // lair_fallen_cloaked2_squad
    {57,0xEB7AF01BU,0x80B2E63CU,0x00000728U,204,1,1,9,{0xEB7AF01BU,52,0},true}, // lair_fallen_cloaked3_squad
    {58,0xEB7AF01BU,0x80B2E640U,0x00000728U,204,1,1,9,{0xEB7AF01BU,52,0},true}, // lair_fallen_inf01_squad
}};
constexpr const Spawn* spawn(std::uint32_t registry,std::uint16_t slot) noexcept { for(const auto& s:kSpawns) { if(s.registry==registry && s.source==slot) { return &s; } } return nullptr; }
struct EnemyReceipt { std::uint64_t run{};std::uint32_t actor{},owner{},generation{};std::uint16_t source{};std::uint32_t registry{};bool valid() const noexcept { return run && generation && actor!=UINT32_MAX && owner!=UINT32_MAX && spawn(registry,source); } bool operator==(const EnemyReceipt&) const noexcept=default; };
}
