<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <ClCompile Include="$(MSBuildThisFileDirectory)src\state\activity\coo\script_lua.cpp"><AdditionalIncludeDirectories>$(MSBuildThisFileDirectory)vendor\lua\src;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories><ExceptionHandling>Sync</ExceptionHandling></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\lapi.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\lcode.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\lctype.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\ldebug.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\ldo.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\ldump.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\lfunc.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\lgc.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\llex.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\lmem.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\lobject.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\lopcodes.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\lparser.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\lstate.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\lstring.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\ltable.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\ltm.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\lundump.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\lvm.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\lzio.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\lauxlib.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
    <ClCompile Include="$(MSBuildThisFileDirectory)vendor\lua\src\lbaselib.c"><CompileAs>CompileAsCpp</CompileAs><ExceptionHandling>Sync</ExceptionHandling><WarningLevel>TurnOffAllWarnings</WarningLevel><PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions><ObjectFileName>$(IntDir)lua\</ObjectFileName></ClCompile>
  </ItemGroup>
</Project>
