"""Generate the explicit local activity-hash release/group table. No network input."""
from pathlib import Path
import argparse
import json


def generate(ledger):
    if ledger.get("schema") != 2:
        raise ValueError("Expected local release ledger schema 2")
    rows = ledger["rows"]
    releases = ledger["releases"]
    hashes = set()
    for index, row in enumerate(rows):
        if set(row) != {"index", "hash", "release", "kind", "experience"}:
            raise ValueError("Release rules accept only explicit identity/group fields")
        identity = int(row["hash"], 16)
        if row["index"] != index or identity in hashes or not 0 < identity <= 0xFFFFFFFF:
            raise ValueError("Release identities must have unique hashes and contiguous native indices")
        if not 0 < row["release"] < len(releases) or not 0 <= row["experience"] < len(rows):
            raise ValueError("Invalid release or experience anchor")
        if not 0 <= row["kind"] <= 255:
            raise ValueError("Invalid native experience kind")
        hashes.add(identity)
    lines = [
        "// Generated by tools/testing/mission_launch_release_index.py from the explicit local JSON map.",
        "#pragma once", "#include <array>", "#include <cstdint>", '#include "activity_catalog.h"',
        "", "namespace dawn::state::build_data::activities::releases {",
        f"inline constexpr std::size_t contentCount = {len(releases)};",
        "inline constexpr auto unresolved = contentCount - 1;",
        "static_assert(contentCount == kContentCount);",
        "struct Rule { std::uint32_t hash; std::uint16_t nativeIndex, experience; std::uint8_t release, kind; };",
        f"inline constexpr std::array<Rule, {len(rows)}> rules{{{{",
    ]
    for row in sorted(rows, key=lambda rule: int(rule["hash"], 16)):
        lines.append(f'    {{0x{row["hash"]}U, {row["index"]}, {row["experience"]}, {row["release"]}, {row["kind"]}}},')
    lines.extend([
        "}};",
        "[[nodiscard]] inline const Rule* lookup_hash(std::uint32_t hash) noexcept {",
        "    std::size_t first{}, last{rules.size()};",
        "    while (first < last) {",
        "        const auto middle = first + (last - first) / 2;",
        "        if (rules[middle].hash < hash) { first = middle + 1; } else { last = middle; }",
        "    }",
        "    return first < rules.size() && rules[first].hash == hash ? &rules[first] : nullptr;",
        "}",
        "[[nodiscard]] inline const Rule* lookup(const Definition& row) noexcept {",
        "    const auto* rule = lookup_hash(row.hash);",
        "    // Experience anchors use native catalog ordinals, so a different catalog layout must be reviewed.",
        "    return rule != nullptr && rule->nativeIndex == row.index ? rule : nullptr;",
        "}",
        "} // namespace dawn::state::build_data::activities::releases", "",
    ])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2] / "Dawn"
    ledger = json.loads((root / "analysis/mission_launch_release_index.json").read_text(encoding="utf8"))
    generated = generate(ledger)
    target = root / "src/state/build_data/activities/activity_releases.h"
    if args.check:
        if target.read_text(encoding="utf8") != generated:
            raise ValueError("Regenerate activity_releases.h")
    else:
        target.write_text(generated, encoding="utf8", newline="\n")
    print(f'{len(ledger["rows"])} explicit native hashes; '
          f'{len({row["experience"] for row in ledger["rows"]})} experience groups; local index checked')


if __name__ == "__main__":
    main()
