"""Recover exact Eater cranium Carry bindings from installed package metadata."""
from __future__ import annotations

import argparse
import hashlib
import json
import struct
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "docs/raids/eater-of-worlds/tools"))
import extract_eater_of_worlds as eater

INPUT = ROOT / "docs/raids/eater-of-worlds/evidence/runtime-bindings.json"
EVIDENCE = ROOT / "docs/raids/eater-of-worlds/evidence/carry-bindings.json"
HEADER = ROOT / "Dawn/src/state/activity/eater_of_worlds/carry_bindings.h"
ENTITY_CLASS = 0x80809C0F
CONFIG_CLASS = 0x80809C36
CARRY_SUBTYPE = 0x80803E70
CARRY_INTERFACE = 0x80803F6A
CARRY_KIND = 0x80804221
CARRY_OFFSET = 0x598


def recover() -> dict:
    raw = INPUT.read_bytes()
    inventory = json.loads(raw)
    names = {}
    for group in inventory["groups"]:
        registry = int(group["registryKey"], 16)
        for descriptor in group["descriptors"]:
            if descriptor["type"] == 4:
                names[(registry, descriptor["index"], int(descriptor["sourceTag"], 16))] = (
                    descriptor["name"]
                )

    bindings = []
    for entity in inventory["entities"]:
        assert entity["entityClass"] == ENTITY_CLASS
        identity = (entity["registry"], entity["slot"], entity["source"])
        name = names.get(identity, "")
        if not (name.startswith("relics[") and ".o_relic[" in name):
            continue
        matches = []
        for resource in entity["resources"]:
            cls, blob = eater.packages.read(resource)
            if cls != CONFIG_CLASS or len(blob) < 0x90:
                continue
            subtype = struct.unpack_from("<I", blob, 0x7C)[0]
            config, kind, offset = struct.unpack_from("<IIQ", blob, 0x80)
            if config == resource and subtype == CARRY_SUBTYPE and kind == CARRY_KIND:
                assert offset == CARRY_OFFSET and len(blob) >= offset + 16
                matches.append((config, offset))
        assert len(matches) == 1, (identity, name, matches)
        config, offset = matches[0]
        bindings.append({
            "registry": entity["registry"], "slot": entity["slot"],
            "source": entity["source"], "entity": entity["entity"],
            "config": config, "offset": offset,
        })

    bindings.sort(key=lambda binding: (binding["registry"], binding["slot"], binding["source"]))
    identities = [(b["registry"], b["slot"], b["source"]) for b in bindings]
    assert len(bindings) == 120 and len(set(identities)) == len(bindings)
    assert Counter(b["registry"] for b in bindings) == {0x91264981: 60, 0xE8D290A0: 60}
    assert Counter((b["entity"], b["config"]) for b in bindings) == {
        (0x80F42EFE, 0x80F42EEB): 30,
        (0x80F42EDC, 0x80F42EA4): 30,
        (0x80F42F3A, 0x80F42F0B): 30,
        (0x80F42E8A, 0x80F42E86): 30,
    }
    return {
        "schema": "eater-cranium-carry-bindings-v1",
        "runtimeBindingsSha256": hashlib.sha256(raw).hexdigest(),
        "runtimeSubtype": f"0x{CARRY_SUBTYPE:08X}",
        "runtimeInterface": f"0x{CARRY_INTERFACE:08X}",
        "runtimeKind": f"0x{CARRY_KIND:08X}",
        "bindings": [{
            key: (f"0x{value:08X}" if key not in ("slot", "offset") else
                  (f"0x{value:X}" if key == "offset" else value))
            for key, value in binding.items()
        } for binding in bindings],
    }


def render_header(data: dict) -> str:
    lines = [
        "// Generated by tools/coo/extract_eater_carry_bindings.py. Do not edit by hand.",
        "#pragma once", "#include <cstddef>", "#include <cstdint>",
        '#include "catalog.h"', '#include "../coo/lifecycle_service.h"',
        "namespace dawn::state::activity::eater_of_worlds {",
        "inline constexpr std::uint32_t kCraniumCarryInterface=0x80803F6AU;",
        "inline constexpr std::uint32_t kCraniumCarryKind=0x80804221U;",
        "struct CraniumBinding { coo::Asset source; std::uint32_t entity,config; std::uint64_t offset; };",
        "struct CraniumReceipt { coo::Generation generation{}; coo::Asset source{}; std::uintptr_t sourcePointer{}; std::uint32_t entity{UINT32_MAX},serial{UINT32_MAX},component{UINT32_MAX}; };",
        "inline constexpr CraniumBinding kCraniumBindings[]{",
    ]
    for value in data["bindings"]:
        lines.append(
            f"    {{{{{value['registry']}U,{value['source']}U,4,{value['slot']}}},"
            f"{value['entity']}U,{value['config']}U,{value['offset']}ULL}},")
    lines += [
        "};",
        "constexpr std::size_t cranium_index(coo::Asset source) noexcept {",
        "    for(std::size_t i=0;i<std::size(kCraniumBindings);++i) if(kCraniumBindings[i].source==source) return i;",
        "    return std::size(kCraniumBindings);",
        "}",
        "} // namespace dawn::state::activity::eater_of_worlds", "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = recover()
    evidence = json.dumps(data, indent=2) + "\n"
    header = render_header(data)
    if args.check:
        if not EVIDENCE.is_file() or EVIDENCE.read_text() != evidence:
            raise SystemExit(f"stale generated evidence: {EVIDENCE}")
        if not HEADER.is_file() or HEADER.read_text() != header:
            raise SystemExit(f"stale generated header: {HEADER}")
        print(f"PASS: {len(data['bindings'])} exact Eater cranium Carry bindings")
        return
    EVIDENCE.write_text(evidence)
    HEADER.write_text(header)
    print(f"wrote {EVIDENCE} and {HEADER}")


if __name__ == "__main__":
    main()
