#pragma once
#include "authored_registry.h"
#include <array>

// Generated by tools/testing/mercury_ambient_inventory.py from package bytes.
// Reachable candidates only: no admission, initial counts or retail scheduling implied.
namespace sunrise::state::activity::coo::mercury::ambient {
struct Source final { std::uint16_t slot, primaryRule, fallbackRule; std::uint32_t definition; };
struct Group final { std::string_view name; const registry::Definition* registry;
    std::span<const Source> sources; std::uint16_t monitorSlot, triggerSlot, tacticalSlot;
    std::uint8_t tacticalRows; bool hotspot; };

inline constexpr std::array<registry::Slot,7> kSlots_B3CBA385{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B4B9},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B4BC},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B4CC},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B4C3},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B4C6},
    {8,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B4AB},
    {9,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B4AE},
}};
inline constexpr std::array<Source,2> kSources_B3CBA385{{
    {0,8,9,0x80F5B4B9},
    {1,8,9,0x80F5B4BC},
}};

inline constexpr std::array<registry::Slot,7> kSlots_11A229B9{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B4D9},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B4DC},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B4EB},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B4E2},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B4E5},
    {8,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B4C9},
    {9,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B4CF},
}};
inline constexpr std::array<Source,2> kSources_11A229B9{{
    {0,8,9,0x80F5B4D9},
    {1,8,9,0x80F5B4DC},
}};

inline constexpr std::array<registry::Slot,7> kSlots_2571C34D{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B4F7},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B4FA},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B50A},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B501},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B504},
    {8,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B4E8},
    {9,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B4EE},
}};
inline constexpr std::array<Source,2> kSources_2571C34D{{
    {0,8,9,0x80F5B4F7},
    {1,8,9,0x80F5B4FA},
}};

inline constexpr std::array<registry::Slot,7> kSlots_2571C34E{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B516},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B519},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B528},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B51F},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B522},
    {8,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B507},
    {9,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B50D},
}};
inline constexpr std::array<Source,2> kSources_2571C34E{{
    {0,8,9,0x80F5B516},
    {1,8,9,0x80F5B519},
}};

inline constexpr std::array<registry::Slot,7> kSlots_CF4C43A4{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B534},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B537},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B547},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B53E},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B541},
    {6,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B525},
    {7,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B52B},
}};
inline constexpr std::array<Source,2> kSources_CF4C43A4{{
    {0,6,7,0x80F5B534},
    {1,6,7,0x80F5B537},
}};

inline constexpr std::array<registry::Slot,7> kSlots_90EFDE28{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B553},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B556},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B565},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B55C},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B55F},
    {6,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B544},
    {7,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B54A},
}};
inline constexpr std::array<Source,2> kSources_90EFDE28{{
    {0,6,7,0x80F5B553},
    {1,6,7,0x80F5B556},
}};

inline constexpr std::array<registry::Slot,8> kSlots_CF4C43A7{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B571},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B574},
    {2,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B57B},
    {3,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B587},
    {4,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B57E},
    {5,30,0x8080952F,0x80809531,0x80809532,0x80F5B581},
    {11,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B562},
    {12,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B568},
}};
inline constexpr std::array<Source,3> kSources_CF4C43A7{{
    {0,11,12,0x80F5B571},
    {1,11,12,0x80F5B574},
    {2,11,12,0x80F5B57B},
}};

inline constexpr std::array<registry::Slot,7> kSlots_9D083869{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B593},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B596},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B5A6},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B59D},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B5A0},
    {8,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B584},
    {9,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B58A},
}};
inline constexpr std::array<Source,2> kSources_9D083869{{
    {0,8,9,0x80F5B593},
    {1,8,9,0x80F5B596},
}};

inline constexpr std::array<registry::Slot,7> kSlots_DC79C5E5{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B5B2},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B5B5},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B5C4},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B5BB},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B5BE},
    {8,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B5A3},
    {9,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B5A9},
}};
inline constexpr std::array<Source,2> kSources_DC79C5E5{{
    {0,8,9,0x80F5B5B2},
    {1,8,9,0x80F5B5B5},
}};

inline constexpr std::array<registry::Slot,7> kSlots_0775116F{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B5D1},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B5D4},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B5E4},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B5DB},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B5DE},
    {8,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B5C1},
    {9,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B5C7},
}};
inline constexpr std::array<Source,2> kSources_0775116F{{
    {0,8,9,0x80F5B5D1},
    {1,8,9,0x80F5B5D4},
}};

inline constexpr std::array<registry::Slot,7> kSlots_8C756CC3{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B5F1},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B5F4},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B603},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B5FA},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B5FD},
    {8,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B5E1},
    {9,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B5E7},
}};
inline constexpr std::array<Source,2> kSources_8C756CC3{{
    {0,8,9,0x80F5B5F1},
    {1,8,9,0x80F5B5F4},
}};

inline constexpr std::array<registry::Slot,7> kSlots_9692BB5E{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B60F},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B612},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B622},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B619},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B61C},
    {8,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B600},
    {9,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B606},
}};
inline constexpr std::array<Source,2> kSources_9692BB5E{{
    {0,8,9,0x80F5B60F},
    {1,8,9,0x80F5B612},
}};

inline constexpr std::array<registry::Slot,7> kSlots_BB43DE9A{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B62E},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B631},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B640},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B637},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B63A},
    {8,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B61F},
    {9,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B625},
}};
inline constexpr std::array<Source,2> kSources_BB43DE9A{{
    {0,8,9,0x80F5B62E},
    {1,8,9,0x80F5B631},
}};

inline constexpr std::array<registry::Slot,7> kSlots_3163853F{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B64D},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B650},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B660},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B657},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B65A},
    {6,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B63D},
    {7,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B643},
}};
inline constexpr std::array<Source,2> kSources_3163853F{{
    {0,6,7,0x80F5B64D},
    {1,6,7,0x80F5B650},
}};

inline constexpr std::array<registry::Slot,7> kSlots_9B219BF3{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B66D},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B670},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B67F},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B676},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B679},
    {6,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B65D},
    {7,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B663},
}};
inline constexpr std::array<Source,2> kSources_9B219BF3{{
    {0,6,7,0x80F5B66D},
    {1,6,7,0x80F5B670},
}};

inline constexpr std::array<registry::Slot,7> kSlots_74337EDD{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B68B},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B68E},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B69E},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B695},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B698},
    {8,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B67C},
    {9,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B682},
}};
inline constexpr std::array<Source,2> kSources_74337EDD{{
    {0,8,9,0x80F5B68B},
    {1,8,9,0x80F5B68E},
}};

inline constexpr std::array<registry::Slot,7> kSlots_C751ACF1{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B6AA},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B6AD},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B6BC},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B6B3},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B6B6},
    {8,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B69B},
    {9,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B6A1},
}};
inline constexpr std::array<Source,2> kSources_C751ACF1{{
    {0,8,9,0x80F5B6AA},
    {1,8,9,0x80F5B6AD},
}};

inline constexpr std::array<registry::Slot,6> kSlots_9FA0CEF3{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B6C8},
    {1,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B6D8},
    {2,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B6CB},
    {3,30,0x8080952F,0x80809531,0x80809532,0x80F5B6D2},
    {5,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B6B9},
    {6,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B6BF},
}};
inline constexpr std::array<Source,1> kSources_9FA0CEF3{{
    {0,5,6,0x80F5B6C8},
}};

inline constexpr std::array<registry::Slot,7> kSlots_1152544E{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B6E4},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B6E7},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B6F7},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B6EE},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B6F1},
    {6,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B6D5},
    {7,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B6DB},
}};
inline constexpr std::array<Source,2> kSources_1152544E{{
    {0,6,7,0x80F5B6E4},
    {1,6,7,0x80F5B6E7},
}};

inline constexpr std::array<registry::Slot,7> kSlots_CF2196EA{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B703},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B706},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B715},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B70C},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B70F},
    {6,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B6F4},
    {7,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B6FA},
}};
inline constexpr std::array<Source,2> kSources_CF2196EA{{
    {0,6,7,0x80F5B703},
    {1,6,7,0x80F5B706},
}};

inline constexpr std::array<registry::Slot,7> kSlots_1152544D{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B721},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B724},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B734},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B72B},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B72E},
    {8,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B712},
    {9,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B718},
}};
inline constexpr std::array<Source,2> kSources_1152544D{{
    {0,8,9,0x80F5B721},
    {1,8,9,0x80F5B724},
}};

inline constexpr std::array<registry::Slot,7> kSlots_715568C1{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B740},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B743},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B752},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B749},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B74C},
    {8,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B731},
    {9,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B737},
}};
inline constexpr std::array<Source,2> kSources_715568C1{{
    {0,8,9,0x80F5B740},
    {1,8,9,0x80F5B743},
}};

inline constexpr std::array<registry::Slot,7> kSlots_EB1E8937{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B75F},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B762},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B772},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B769},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B76C},
    {9,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B74F},
    {10,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B755},
}};
inline constexpr std::array<Source,2> kSources_EB1E8937{{
    {0,9,10,0x80F5B75F},
    {1,9,10,0x80F5B762},
}};

inline constexpr std::array<registry::Slot,6> kSlots_EB1E8934{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B77F},
    {1,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B78E},
    {2,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B782},
    {3,30,0x8080952F,0x80809531,0x80809532,0x80F5B788},
    {5,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B76F},
    {6,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B775},
}};
inline constexpr std::array<Source,1> kSources_EB1E8934{{
    {0,5,6,0x80F5B77F},
}};

inline constexpr std::array<registry::Slot,6> kSlots_736F7158{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B79A},
    {1,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B7A9},
    {2,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B79D},
    {3,30,0x8080952F,0x80809531,0x80809532,0x80F5B7A3},
    {5,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B78B},
    {6,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B791},
}};
inline constexpr std::array<Source,1> kSources_736F7158{{
    {0,5,6,0x80F5B79A},
}};

inline constexpr std::array<registry::Slot,7> kSlots_1ED6087A{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B7B5},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B7B8},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B7C8},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B7BF},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B7C2},
    {8,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B7A6},
    {9,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B7AC},
}};
inline constexpr std::array<Source,2> kSources_1ED6087A{{
    {0,8,9,0x80F5B7B5},
    {1,8,9,0x80F5B7B8},
}};

inline constexpr std::array<registry::Slot,6> kSlots_1ED60879{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B7D4},
    {1,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B7E3},
    {2,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B7D7},
    {3,30,0x8080952F,0x80809531,0x80809532,0x80F5B7DD},
    {5,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B7C5},
    {6,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B7CB},
}};
inline constexpr std::array<Source,1> kSources_1ED60879{{
    {0,5,6,0x80F5B7D4},
}};

inline constexpr std::array<registry::Slot,6> kSlots_2B614515{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B7EF},
    {1,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B7FE},
    {2,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B7F2},
    {3,30,0x8080952F,0x80809531,0x80809532,0x80F5B7F8},
    {5,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B7E0},
    {6,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B7E6},
}};
inline constexpr std::array<Source,1> kSources_2B614515{{
    {0,5,6,0x80F5B7EF},
}};

inline constexpr std::array<registry::Slot,7> kSlots_FB7F2889{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B843},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B846},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B855},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B84C},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B84F},
    {6,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B830},
    {7,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B833},
}};
inline constexpr std::array<Source,2> kSources_FB7F2889{{
    {0,6,7,0x80F5B843},
    {1,6,7,0x80F5B846},
}};

inline constexpr std::array<registry::Slot,7> kSlots_EA95B97D{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B861},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B864},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B874},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B86B},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B86E},
    {6,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B852},
    {7,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B858},
}};
inline constexpr std::array<Source,2> kSources_EA95B97D{{
    {0,6,7,0x80F5B861},
    {1,6,7,0x80F5B864},
}};

inline constexpr std::array<registry::Slot,7> kSlots_BBF1BA51{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B880},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B883},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B892},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B889},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B88C},
    {6,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B871},
    {7,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B877},
}};
inline constexpr std::array<Source,2> kSources_BBF1BA51{{
    {0,6,7,0x80F5B880},
    {1,6,7,0x80F5B883},
}};

inline constexpr std::array<registry::Slot,8> kSlots_40BC3C51{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B89F},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B8A2},
    {2,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B8A9},
    {3,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B8B5},
    {4,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B8AC},
    {5,30,0x8080952F,0x80809531,0x80809532,0x80F5B8AF},
    {8,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B88F},
    {9,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B895},
}};
inline constexpr std::array<Source,3> kSources_40BC3C51{{
    {0,8,9,0x80F5B89F},
    {1,8,9,0x80F5B8A2},
    {2,8,9,0x80F5B8A9},
}};

inline constexpr std::array<registry::Slot,8> kSlots_CCF03E8D{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B8C2},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B8C5},
    {2,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B8CB},
    {3,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B8D7},
    {4,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B8CE},
    {5,30,0x8080952F,0x80809531,0x80809532,0x80F5B8D1},
    {8,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B8B2},
    {9,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B8B8},
}};
inline constexpr std::array<Source,3> kSources_CCF03E8D{{
    {0,8,9,0x80F5B8C2},
    {1,8,9,0x80F5B8C5},
    {2,8,9,0x80F5B8CB},
}};

inline constexpr std::array<registry::Slot,7> kSlots_85938DB7{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B8E3},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B8E6},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B8F6},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B8ED},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B8F0},
    {8,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B8D4},
    {9,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B8DA},
}};
inline constexpr std::array<Source,2> kSources_85938DB7{{
    {0,8,9,0x80F5B8E3},
    {1,8,9,0x80F5B8E6},
}};

inline constexpr std::array<registry::Slot,7> kSlots_0EFE61CB{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B902},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B905},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B914},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B90B},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B90E},
    {8,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B8F3},
    {9,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B8F9},
}};
inline constexpr std::array<Source,2> kSources_0EFE61CB{{
    {0,8,9,0x80F5B902},
    {1,8,9,0x80F5B905},
}};

inline constexpr std::array<registry::Slot,7> kSlots_1780D86F{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B921},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B924},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B934},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B92B},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B92E},
    {7,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B911},
    {8,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B917},
}};
inline constexpr std::array<Source,2> kSources_1780D86F{{
    {0,7,8,0x80F5B921},
    {1,7,8,0x80F5B924},
}};

inline constexpr std::array<registry::Slot,7> kSlots_63D313C3{{
    {0,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B941},
    {1,1,0x80809A3B,0x80807ECC,0x80807EC9,0x80F5B944},
    {2,3,0x80808348,0x80807F04,0x80807F0C,0x80F5B953},
    {3,70,0x808094EE,0x808094F0,0x808094F1,0x80F5B94A},
    {4,30,0x8080952F,0x80809531,0x80809532,0x80F5B94D},
    {7,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B931},
    {8,66,0x808094CF,0xFFFFFFFF,0xFFFFFFFF,0x80F5B937},
}};
inline constexpr std::array<Source,2> kSources_63D313C3{{
    {0,7,8,0x80F5B941},
    {1,7,8,0x80F5B944},
}};

inline constexpr std::array<registry::Definition,37> kRegistries{{
    {"mercury_freeroam",0x80F4696A,0xB3CBA385,0x80F5B4D5,0xA83A9175,15,kSlots_B3CBA385},
    {"mercury_freeroam",0x80F4696A,0x11A229B9,0x80F5B4F4,0xA83A9175,15,kSlots_11A229B9},
    {"mercury_freeroam",0x80F4696A,0x2571C34D,0x80F5B513,0xA83A9175,15,kSlots_2571C34D},
    {"mercury_freeroam",0x80F4696A,0x2571C34E,0x80F5B531,0xA83A9175,15,kSlots_2571C34E},
    {"mercury_freeroam",0x80F4696A,0xCF4C43A4,0x80F5B550,0xA83A9175,15,kSlots_CF4C43A4},
    {"mercury_freeroam",0x80F4696A,0x90EFDE28,0x80F5B56E,0xA83A9175,15,kSlots_90EFDE28},
    {"mercury_freeroam",0x80F4696A,0xCF4C43A7,0x80F5B590,0xA83A9175,15,kSlots_CF4C43A7},
    {"mercury_freeroam",0x80F4696A,0x9D083869,0x80F5B5AF,0xA83A9175,15,kSlots_9D083869},
    {"mercury_freeroam",0x80F4696A,0xDC79C5E5,0x80F5B5CD,0xA83A9175,15,kSlots_DC79C5E5},
    {"mercury_freeroam",0x80F4696A,0x0775116F,0x80F5B5ED,0xA83A9175,15,kSlots_0775116F},
    {"mercury_freeroam",0x80F4696A,0x8C756CC3,0x80F5B60C,0xA83A9175,15,kSlots_8C756CC3},
    {"mercury_freeroam",0x80F4696A,0x9692BB5E,0x80F5B62B,0xA83A9175,15,kSlots_9692BB5E},
    {"mercury_freeroam",0x80F4696A,0xBB43DE9A,0x80F5B649,0xA83A9175,15,kSlots_BB43DE9A},
    {"mercury_freeroam",0x80F4696A,0x3163853F,0x80F5B669,0xA83A9175,15,kSlots_3163853F},
    {"mercury_freeroam",0x80F4696A,0x9B219BF3,0x80F5B688,0xA83A9175,15,kSlots_9B219BF3},
    {"mercury_freeroam",0x80F4696A,0x74337EDD,0x80F5B6A7,0xA83A9175,15,kSlots_74337EDD},
    {"mercury_freeroam",0x80F4696A,0xC751ACF1,0x80F5B6C5,0xA83A9175,15,kSlots_C751ACF1},
    {"mercury_freeroam",0x80F4696A,0x9FA0CEF3,0x80F5B6E1,0xA83A9175,15,kSlots_9FA0CEF3},
    {"mercury_freeroam",0x80F4696A,0x1152544E,0x80F5B700,0xA83A9175,15,kSlots_1152544E},
    {"mercury_freeroam",0x80F4696A,0xCF2196EA,0x80F5B71E,0xA83A9175,15,kSlots_CF2196EA},
    {"mercury_freeroam",0x80F4696A,0x1152544D,0x80F5B73D,0xA83A9175,15,kSlots_1152544D},
    {"mercury_freeroam",0x80F4696A,0x715568C1,0x80F5B75B,0xA83A9175,15,kSlots_715568C1},
    {"mercury_freeroam",0x80F4696A,0xEB1E8937,0x80F5B77B,0xA83A9175,15,kSlots_EB1E8937},
    {"mercury_freeroam",0x80F4696A,0xEB1E8934,0x80F5B797,0xA83A9175,15,kSlots_EB1E8934},
    {"mercury_freeroam",0x80F4696A,0x736F7158,0x80F5B7B2,0xA83A9175,15,kSlots_736F7158},
    {"mercury_freeroam",0x80F4696A,0x1ED6087A,0x80F5B7D1,0xA83A9175,15,kSlots_1ED6087A},
    {"mercury_freeroam",0x80F4696A,0x1ED60879,0x80F5B7EC,0xA83A9175,15,kSlots_1ED60879},
    {"mercury_freeroam",0x80F4696A,0x2B614515,0x80F5B807,0xA83A9175,15,kSlots_2B614515},
    {"mercury_freeroam",0x80F4696A,0xFB7F2889,0x80F5B85E,0xA83A9175,15,kSlots_FB7F2889},
    {"mercury_freeroam",0x80F4696A,0xEA95B97D,0x80F5B87D,0xA83A9175,15,kSlots_EA95B97D},
    {"mercury_freeroam",0x80F4696A,0xBBF1BA51,0x80F5B89B,0xA83A9175,15,kSlots_BBF1BA51},
    {"mercury_freeroam",0x80F4696A,0x40BC3C51,0x80F5B8BE,0xA83A9175,15,kSlots_40BC3C51},
    {"mercury_freeroam",0x80F4696A,0xCCF03E8D,0x80F5B8E0,0xA83A9175,15,kSlots_CCF03E8D},
    {"mercury_freeroam",0x80F4696A,0x85938DB7,0x80F5B8FF,0xA83A9175,15,kSlots_85938DB7},
    {"mercury_freeroam",0x80F4696A,0x0EFE61CB,0x80F5B91D,0xA83A9175,15,kSlots_0EFE61CB},
    {"mercury_freeroam",0x80F4696A,0x1780D86F,0x80F5B93D,0xA83A9175,15,kSlots_1780D86F},
    {"mercury_freeroam",0x80F4696A,0x63D313C3,0x80F5B95C,0xA83A9175,15,kSlots_63D313C3},
}};
inline constexpr std::array<Group,37> kGroups{{
    {"pf_lighthouse_ca_blocks_right_a",&kRegistries[0],kSources_B3CBA385,4,14,2,4,false},
    {"pf_lighthouse_ca_blocks_right_a_hotspot",&kRegistries[1],kSources_11A229B9,4,14,2,4,true},
    {"pf_lighthouse_ca_cannon_forest_a",&kRegistries[2],kSources_2571C34D,4,15,2,4,false},
    {"pf_lighthouse_ca_cannon_forest_b",&kRegistries[3],kSources_2571C34E,4,14,2,4,false},
    {"pf_lighthouse_ca_cannon_mid_a",&kRegistries[4],kSources_CF4C43A4,4,10,2,2,false},
    {"pf_lighthouse_ca_cannon_mid_a_hotspot",&kRegistries[5],kSources_90EFDE28,4,10,2,2,true},
    {"pf_lighthouse_ca_cannon_mid_b",&kRegistries[6],kSources_CF4C43A7,5,18,3,6,false},
    {"pf_lighthouse_ca_cannon_tower_a",&kRegistries[7],kSources_9D083869,4,13,2,4,false},
    {"pf_lighthouse_ca_cannon_tower_a_hotspot",&kRegistries[8],kSources_DC79C5E5,4,13,2,4,true},
    {"pf_lighthouse_ca_crater_cannon_a",&kRegistries[9],kSources_0775116F,4,14,2,4,false},
    {"pf_lighthouse_ca_crater_cannon_a_hotspot",&kRegistries[10],kSources_8C756CC3,4,14,2,4,true},
    {"pf_lighthouse_ca_crater_right_a",&kRegistries[11],kSources_9692BB5E,4,13,2,4,false},
    {"pf_lighthouse_ca_crater_right_a_hotspot",&kRegistries[12],kSources_BB43DE9A,4,13,2,4,true},
    {"pf_lighthouse_ca_forest_a",&kRegistries[13],kSources_3163853F,4,11,2,2,false},
    {"pf_lighthouse_ca_forest_a_hotspot",&kRegistries[14],kSources_9B219BF3,4,11,2,2,true},
    {"pf_lighthouse_ca_pond_a",&kRegistries[15],kSources_74337EDD,4,13,2,4,false},
    {"pf_lighthouse_ca_pond_a_hotspot",&kRegistries[16],kSources_C751ACF1,4,13,2,4,true},
    {"pf_lighthouse_ca_tower_back_a",&kRegistries[17],kSources_9FA0CEF3,3,9,1,2,false},
    {"pf_lighthouse_vx_cannon_mid_a",&kRegistries[18],kSources_1152544E,4,10,2,2,false},
    {"pf_lighthouse_vx_cannon_mid_a_hotspot",&kRegistries[19],kSources_CF2196EA,4,10,2,2,true},
    {"pf_lighthouse_vx_cannon_mid_b",&kRegistries[20],kSources_1152544D,4,13,2,4,false},
    {"pf_lighthouse_vx_cannon_mid_b_hotspot",&kRegistries[21],kSources_715568C1,4,13,2,4,true},
    {"pf_lighthouse_vx_center_left_a",&kRegistries[22],kSources_EB1E8937,4,18,2,4,false},
    {"pf_lighthouse_vx_center_left_b",&kRegistries[23],kSources_EB1E8934,3,10,1,2,false},
    {"pf_lighthouse_vx_center_left_b_hotspot",&kRegistries[24],kSources_736F7158,3,10,1,2,true},
    {"pf_lighthouse_vx_center_right_a",&kRegistries[25],kSources_1ED6087A,4,18,2,4,false},
    {"pf_lighthouse_vx_center_right_b",&kRegistries[26],kSources_1ED60879,3,9,1,2,false},
    {"pf_lighthouse_vx_center_right_b_hotspot",&kRegistries[27],kSources_2B614515,3,9,1,2,true},
    {"pf_lighthouse_vx_crater_cannon_a",&kRegistries[28],kSources_FB7F2889,4,10,2,2,false},
    {"pf_lighthouse_vx_crater_left_a",&kRegistries[29],kSources_EA95B97D,4,10,2,2,false},
    {"pf_lighthouse_vx_crater_left_a_hotspot",&kRegistries[30],kSources_BBF1BA51,4,10,2,2,true},
    {"pf_lighthouse_vx_forest_a",&kRegistries[31],kSources_40BC3C51,5,14,3,3,false},
    {"pf_lighthouse_vx_forest_a_hotspot",&kRegistries[32],kSources_CCF03E8D,5,14,3,3,true},
    {"pf_lighthouse_vx_pond_a",&kRegistries[33],kSources_85938DB7,4,15,2,4,false},
    {"pf_lighthouse_vx_pond_a_hotspot",&kRegistries[34],kSources_0EFE61CB,4,15,2,4,true},
    {"pf_lighthouse_vx_steps_a",&kRegistries[35],kSources_1780D86F,4,12,2,3,false},
    {"pf_lighthouse_vx_steps_a_hotspot",&kRegistries[36],kSources_63D313C3,4,12,2,3,true},
}};
[[nodiscard]] constexpr const Group* find(std::uint32_t key) noexcept {
    for(const auto& group:kGroups) if(group.registry->key==key) return &group;
    return nullptr;
}
} // namespace sunrise::state::activity::coo::mercury::ambient
