// Read-only cache layout metadata, compiled against the current native record types.
// Used by inventory.py; no guessed binary offsets or runtime publication.
#include "state/build_data/inventory/buckets/definition.h"
#include "state/build_data/socket_entry_lists/definition.h"
#include "state/build_data/cache/records/format.h"
#include <cstddef>
#include <iostream>
namespace r = dawn::state::build_data::cache::records;
#define FIELD(T, M) std::cout << "\"" #M "\":[" << offsetof(r::T, M) << ',' << sizeof(((r::T*)nullptr)->M) << ']'
int main() {
    std::cout << "{\"version\":" << r::kCacheFormatVersion << ",\"records\":{";
    std::cout << "\"Header\":{\"size\":" << sizeof(r::Header) << ",\"fields\":{";
    FIELD(Header, magic);
    std::cout << ",";
    FIELD(Header, version);
    std::cout << ",";
    FIELD(Header, imageTimestamp);
    std::cout << ",";
    FIELD(Header, imageSize);
    std::cout << ",";
    FIELD(Header, configuredEquipmentHash);
    std::cout << ",";
    FIELD(Header, producerSourceSha256);
    std::cout << ",";
    FIELD(Header, producerImageSha256);
    std::cout << ",";
    FIELD(Header, namedCount);
    std::cout << ",";
    FIELD(Header, itemCount);
    std::cout << ",";
    FIELD(Header, collectibleCount);
    std::cout << ",";
    FIELD(Header, materialRequirementSetCount);
    std::cout << ",";
    FIELD(Header, itemDetailCount);
    std::cout << ",";
    FIELD(Header, socketPlugRuleCount);
    std::cout << ",";
    FIELD(Header, socketPlugPoolCount);
    std::cout << ",";
    FIELD(Header, socketPlugMemberCount);
    std::cout << ",";
    FIELD(Header, inventoryBucketCount);
    std::cout << ",";
    FIELD(Header, socketEntryListCount);
    std::cout << ",";
    FIELD(Header, socketEntryTableCount);
    std::cout << ",";
    FIELD(Header, abilityBucketCount);
    std::cout << ",";
    FIELD(Header, progressionCount);
    std::cout << ",";
    FIELD(Header, scenarioCount);
    std::cout << ",";
    FIELD(Header, rosterGroupCount);
    std::cout << ",";
    FIELD(Header, spawnStemCount);
    std::cout << ",";
    FIELD(Header, spawnNameHashCount);
    std::cout << ",";
    FIELD(Header, spawnPointCount);
    std::cout << ",";
    FIELD(Header, hashNameCount);
    std::cout << ",";
    FIELD(Header, vendorIndexCount);
    std::cout << ",";
    FIELD(Header, vendorDefinitionCount);
    std::cout << ",";
    FIELD(Header, vendorSaleRowCount);
    std::cout << ",";
    FIELD(Header, vendorInstalledRowCount);
    std::cout << ",";
    FIELD(Header, constants);
    std::cout << ",";
    FIELD(Header, payloadChecksum);
    std::cout << "}}";
    std::cout << ",";
    std::cout << "\"NamedRecord\":{\"size\":" << sizeof(r::NamedRecord) << ",\"fields\":{";
    FIELD(NamedRecord, name);
    std::cout << ",";
    FIELD(NamedRecord, nameLength);
    std::cout << ",";
    FIELD(NamedRecord, reserved);
    std::cout << ",";
    FIELD(NamedRecord, tag);
    std::cout << ",";
    FIELD(NamedRecord, classId);
    std::cout << "}}";
    std::cout << ",";
    std::cout << "\"ScenarioRecord\":{\"size\":" << sizeof(r::ScenarioRecord) << ",\"fields\":{";
    FIELD(ScenarioRecord, name);
    std::cout << ",";
    FIELD(ScenarioRecord, tag);
    std::cout << ",";
    FIELD(ScenarioRecord, nameLength);
    std::cout << ",";
    FIELD(ScenarioRecord, bubbleCount);
    std::cout << ",";
    FIELD(ScenarioRecord, truncated);
    std::cout << ",";
    FIELD(ScenarioRecord, rosterGroupCount);
    std::cout << ",";
    FIELD(ScenarioRecord, spawnStemLength);
    std::cout << ",";
    FIELD(ScenarioRecord, bubbleGroupCount);
    std::cout << ",";
    FIELD(ScenarioRecord, reserved);
    std::cout << ",";
    FIELD(ScenarioRecord, spawnStem);
    std::cout << ",";
    FIELD(ScenarioRecord, bubbleStates);
    std::cout << ",";
    FIELD(ScenarioRecord, bubbleHashes);
    std::cout << ",";
    FIELD(ScenarioRecord, bubbleStateCounts);
    std::cout << ",";
    FIELD(ScenarioRecord, rosterGroups);
    std::cout << ",";
    FIELD(ScenarioRecord, bubbleGroups);
    std::cout << ",";
    FIELD(ScenarioRecord, bubbleGroupMasks);
    std::cout << ",";
    FIELD(ScenarioRecord, authoredGroupCounts);
    std::cout << ",";
    FIELD(ScenarioRecord, authoredGroups);
    std::cout << ",";
    FIELD(ScenarioRecord, bubbleMapIndices);
    std::cout << ",";
    FIELD(ScenarioRecord, packageCount);
    std::cout << ",";
    FIELD(ScenarioRecord, packageReserved);
    std::cout << ",";
    FIELD(ScenarioRecord, packages);
    std::cout << "}}";
    std::cout << ",";
    std::cout << "\"RosterGroupRecord\":{\"size\":" << sizeof(r::RosterGroupRecord) << ",\"fields\":{";
    FIELD(RosterGroupRecord, registryKey);
    std::cout << ",";
    FIELD(RosterGroupRecord, objectTag);
    std::cout << ",";
    FIELD(RosterGroupRecord, slotCount);
    std::cout << ",";
    FIELD(RosterGroupRecord, slotTypes);
    std::cout << ",";
    FIELD(RosterGroupRecord, slotFlags);
    std::cout << ",";
    FIELD(RosterGroupRecord, slotIndices);
    std::cout << ",";
    FIELD(RosterGroupRecord, descriptorTags);
    std::cout << ",";
    FIELD(RosterGroupRecord, descriptorOffsets);
    std::cout << ",";
    FIELD(RosterGroupRecord, componentClasses);
    std::cout << ",";
    FIELD(RosterGroupRecord, senseSchemas);
    std::cout << ",";
    FIELD(RosterGroupRecord, authSchemas);
    std::cout << "}}";
    std::cout << ",";
    std::cout << "\"SpawnStemRecord\":{\"size\":" << sizeof(r::SpawnStemRecord) << ",\"fields\":{";
    FIELD(SpawnStemRecord, name);
    std::cout << ",";
    FIELD(SpawnStemRecord, pointCount);
    std::cout << ",";
    FIELD(SpawnStemRecord, setCount);
    std::cout << ",";
    FIELD(SpawnStemRecord, nameHashOffset);
    std::cout << ",";
    FIELD(SpawnStemRecord, nameHashCount);
    std::cout << ",";
    FIELD(SpawnStemRecord, nameLength);
    std::cout << ",";
    FIELD(SpawnStemRecord, reserved);
    std::cout << "}}";
    std::cout << ",";
    std::cout << "\"SpawnNameHashRecord\":{\"size\":" << sizeof(r::SpawnNameHashRecord) << ",\"fields\":{";
    FIELD(SpawnNameHashRecord, value);
    std::cout << ",";
    FIELD(SpawnNameHashRecord, pointCount);
    std::cout << ",";
    FIELD(SpawnNameHashRecord, stemIndex);
    std::cout << ",";
    FIELD(SpawnNameHashRecord, reserved);
    std::cout << ",";
    FIELD(SpawnNameHashRecord, bubbleMask);
    std::cout << ",";
    FIELD(SpawnNameHashRecord, unbound);
    std::cout << ",";
    FIELD(SpawnNameHashRecord, inMapPackage);
    std::cout << ",";
    FIELD(SpawnNameHashRecord, activityPackageCount);
    std::cout << ",";
    FIELD(SpawnNameHashRecord, activityPackageOverflow);
    std::cout << ",";
    FIELD(SpawnNameHashRecord, activityPackages);
    std::cout << "}}";
    std::cout << ",";
    std::cout << "\"SpawnPointRecord\":{\"size\":" << sizeof(r::SpawnPointRecord) << ",\"fields\":{";
    FIELD(SpawnPointRecord, position);
    std::cout << ",";
    FIELD(SpawnPointRecord, nameHash);
    std::cout << ",";
    FIELD(SpawnPointRecord, stemIndex);
    std::cout << ",";
    FIELD(SpawnPointRecord, reserved);
    std::cout << "}}";
    std::cout << ",";
    std::cout << "\"HashNameRecord\":{\"size\":" << sizeof(r::HashNameRecord) << ",\"fields\":{";
    FIELD(HashNameRecord, name);
    std::cout << ",";
    FIELD(HashNameRecord, hash);
    std::cout << ",";
    FIELD(HashNameRecord, nameLength);
    std::cout << ",";
    FIELD(HashNameRecord, reserved);
    std::cout << "}}";
    std::cout << "},\"domains\":[";
    std::cout << "{\"count\":\"namedCount\",\"record\":\"NamedRecord\",\"size\":" << sizeof(r::NamedRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"itemCount\",\"record\":\"ItemRecord\",\"size\":" << sizeof(r::ItemRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"collectibleCount\",\"record\":\"CollectibleRecord\",\"size\":" << sizeof(r::CollectibleRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"materialRequirementSetCount\",\"record\":\"MaterialRequirementSetRecord\",\"size\":" << sizeof(r::MaterialRequirementSetRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"itemDetailCount\",\"record\":\"ItemDetailRecord\",\"size\":" << sizeof(r::ItemDetailRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"socketPlugRuleCount\",\"record\":\"SocketPlugRuleRecord\",\"size\":" << sizeof(r::SocketPlugRuleRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"socketPlugPoolCount\",\"record\":\"SocketPlugPoolRecord\",\"size\":" << sizeof(r::SocketPlugPoolRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"socketPlugMemberCount\",\"record\":\"SocketPlugMemberRecord\",\"size\":" << sizeof(r::SocketPlugMemberRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"inventoryBucketCount\",\"record\":\"InventoryBucketRecord\",\"size\":" << sizeof(r::InventoryBucketRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"socketEntryListCount\",\"record\":\"SocketEntryListRecord\",\"size\":" << sizeof(r::SocketEntryListRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"socketEntryTableCount\",\"record\":\"SocketEntryTableRecord\",\"size\":" << sizeof(r::SocketEntryTableRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"abilityBucketCount\",\"record\":\"AbilityBucketRecord\",\"size\":" << sizeof(r::AbilityBucketRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"progressionCount\",\"record\":\"ProgressionRecord\",\"size\":" << sizeof(r::ProgressionRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"scenarioCount\",\"record\":\"ScenarioRecord\",\"size\":" << sizeof(r::ScenarioRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"rosterGroupCount\",\"record\":\"RosterGroupRecord\",\"size\":" << sizeof(r::RosterGroupRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"spawnStemCount\",\"record\":\"SpawnStemRecord\",\"size\":" << sizeof(r::SpawnStemRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"spawnNameHashCount\",\"record\":\"SpawnNameHashRecord\",\"size\":" << sizeof(r::SpawnNameHashRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"spawnPointCount\",\"record\":\"SpawnPointRecord\",\"size\":" << sizeof(r::SpawnPointRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"hashNameCount\",\"record\":\"HashNameRecord\",\"size\":" << sizeof(r::HashNameRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"vendorIndexCount\",\"record\":\"VendorIndexRecord\",\"size\":" << sizeof(r::VendorIndexRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"vendorDefinitionCount\",\"record\":\"VendorDefinitionRecord\",\"size\":" << sizeof(r::VendorDefinitionRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"vendorSaleRowCount\",\"record\":\"VendorSaleRowRecord\",\"size\":" << sizeof(r::VendorSaleRowRecord) << "}";
    std::cout << ",";
    std::cout << "{\"count\":\"vendorInstalledRowCount\",\"record\":\"VendorInstalledRowRecord\",\"size\":" << sizeof(r::VendorInstalledRowRecord) << "}";
    std::cout << "]}\n";
}
