"""Recover Eater type-4 health bindings from installed package metadata only."""
from __future__ import annotations

import argparse
import hashlib
import json
import struct
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "docs/raids/eater-of-worlds/tools"))
import extract_eater_of_worlds as eater

INPUT = ROOT / "docs/raids/eater-of-worlds/evidence/runtime-bindings.json"
EVIDENCE = ROOT / "docs/raids/eater-of-worlds/evidence/health-bindings.json"
HEADER = ROOT / "Sunrise/src/state/activity/eater_of_worlds/health_bindings.h"
ENTITY_CLASS = 0x80809C0F
CONFIG_CLASS = 0x80809C36
HEALTH_KIND = 0x80804B8A


def recover() -> dict:
    raw = INPUT.read_bytes()
    inventory = json.loads(raw)
    bindings = []
    for entity in inventory["entities"]:
        assert entity["entityClass"] == ENTITY_CLASS
        matches = []
        for resource in entity["resources"]:
            cls, blob = eater.packages.read(resource)
            if cls != CONFIG_CLASS or len(blob) < 0xA0:
                continue
            config, kind, offset = struct.unpack_from("<IIQ", blob, 0x90)
            if config == resource and kind == HEALTH_KIND:
                assert 0x340 <= offset <= len(blob) - 16
                matches.append((config, offset))
        assert len(matches) <= 1, (hex(entity["source"]), matches)
        if matches:
            config, offset = matches[0]
            bindings.append({
                "registry": entity["registry"], "slot": entity["slot"],
                "source": entity["source"], "entity": entity["entity"],
                "config": config, "offset": offset,
            })
    bindings.sort(key=lambda b: (b["registry"], b["slot"], b["source"]))
    identities = [(b["registry"], b["slot"], b["source"]) for b in bindings]
    assert len(bindings) == 201 and len(set(identities)) == len(bindings)
    counts = Counter((b["config"], b["entity"], b["offset"]) for b in bindings)
    assert sorted(counts.values()) == [9, 9, 9, 18, 18, 18, 30, 30, 30, 30]
    return {
        "schema": "eater-health-bindings-v1",
        "runtimeBindingsSha256": hashlib.sha256(raw).hexdigest(),
        "runtimeKind": f"0x{HEALTH_KIND:08X}",
        "bindings": [{k: (f"0x{v:08X}" if k not in ("slot", "offset") else
                           (f"0x{v:X}" if k == "offset" else v))
                      for k, v in b.items()} for b in bindings],
    }


def render_header(data: dict) -> str:
    lines = [
        "// Generated by tools/coo/extract_eater_health_bindings.py. Do not edit by hand.",
        "#pragma once", "#include <cstddef>", "#include <cstdint>",
        '#include "catalog.h"', '#include "../coo/lifecycle_service.h"',
        "namespace sunrise::state::activity::eater_of_worlds {",
        "inline constexpr std::uint32_t kHealthRuntimeKind=0x80804B8AU;",
        "struct HealthBinding { coo::Asset source; std::uint32_t entity,config; std::uint64_t offset; };",
        "struct HealthReceipt { coo::Generation generation{}; coo::Asset source{}; std::uintptr_t sourcePointer{}; std::uint32_t entity{},serial{},health{}; };",
        "inline constexpr HealthBinding kHealthBindings[]{",
    ]
    for value in data["bindings"]:
        lines.append(
            f"    {{{{{value['registry']}U,{value['source']}U,4,{value['slot']}}},"
            f"{value['entity']}U,{value['config']}U,{value['offset']}ULL}},")
    lines += [
        "};",
        "constexpr std::size_t health_index(coo::Asset source) noexcept {",
        "    for(std::size_t i=0;i<std::size(kHealthBindings);++i) if(kHealthBindings[i].source==source) return i;",
        "    return std::size(kHealthBindings);",
        "}",
        "} // namespace sunrise::state::activity::eater_of_worlds", "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = recover()
    evidence = json.dumps(data, indent=2) + "\n"
    header = render_header(data)
    if args.check:
        if not EVIDENCE.is_file() or EVIDENCE.read_text() != evidence:
            raise SystemExit(f"stale generated evidence: {EVIDENCE}")
        if not HEADER.is_file() or HEADER.read_text() != header:
            raise SystemExit(f"stale generated header: {HEADER}")
        print(f"PASS: {len(data['bindings'])} exact Eater health bindings")
        return
    EVIDENCE.write_text(evidence)
    HEADER.write_text(header)
    print(f"wrote {EVIDENCE} and {HEADER}")


if __name__ == "__main__":
    main()
