"""Recover the runtime roster and Scene cast from the installed Beyond Infinity package.

No story order is generated here. Scene target arrays include actors AND native
device/monitor references. Dropping the latter changes the authored scene.
"""
import argparse
import json
import struct
from pathlib import Path
from extract_gateway_bindings import array, u32, i64
from package_read import read

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'Dawn/src/state/activity/beyond_infinity/native_catalog.h'


def playback(graph_tag,data):
    _,graph=read(graph_tag)
    events=[]
    for entry in array(graph,0xE8,0xC0):
        assert u32(graph,entry)==graph_tag and u32(graph,entry+4)==0x8080638A
        definition=i64(graph,entry+8)
        assert u32(graph,definition+4)==0x8080637D
        event=u32(graph,definition+0x10)
        if event!=0x385838EC: events.append(event)
    assert len(events)<=32 and len(events)==len(set(events)),(graph_tag,events)
    speeches=[]
    for entry in array(graph,0xC8,0x30):
        prototype=entry+0x20+i64(graph,entry+0x20)
        if u32(graph,prototype+4)!=0x808062F6: continue
        definition=i64(graph,prototype+8)
        assert u32(graph,definition+4)==0x808062F5
        selector,bank=struct.unpack_from('<II',graph,definition+0x78)
        if bank!=0x80F1FDF7: continue
        row=next(row['row'] for row in data['dialogue'] if row['selector']==selector)
        speeches.append((row,prototype-0x90,definition,u32(graph,definition+0x48)))
    return events,speeches



def cues(graph_tag):
    """Native action nodes with an authenticated start input; no inferred timer endpoints."""
    _,g=read(graph_tag)
    event_nodes={entry:u32(g,i64(g,entry+8)+0x10) for entry in array(g,0xE8,0xC0)}
    inputs=array(g,0xF8,16)
    result=[]
    for index,entry in enumerate(array(g,0xC8,0x30)):
        p=entry+0x20+i64(g,entry+0x20);d=i64(g,p+8)
        if u32(g,d+0x38)!=graph_tag or u32(g,d+0x3C)!=0x80806388: continue
        signal=i64(g,d+0x40)
        assert p<signal<p+0x400 and index<64
        emitted=[]
        if u32(g,p+4)==0x808062E4:
            for output in array(g,d+0x68,4):
                ref=inputs[u32(g,output)]
                assert u32(g,ref)==graph_tag and u32(g,ref+4)==0x80806388
                event=event_nodes[i64(g,ref+8)-0x50]
                emitted.append(event)
        result.append((index,p-0x90,u32(g,p+4),d,signal-0x90,u32(g,signal+4),i64(g,signal+8),emitted))
    return result


def render():
    data = json.loads((ROOT / 'build/coo/beyond-infinity-research/native-bindings.json').read_text())
    slots = {(g['registry'], s['slotTypes'], s['slotIndices']): s for g in data['groups'] for s in g['slots']}
    def asset(key):
        s = slots.get(key, {'descriptorTags': 0})
        return f'{{0x{key[0]:08X}U,0x{s["descriptorTags"]:08X}U,{key[1]},{key[2]}}}'
    lines = ['// Generated by generate_beyond_infinity_runtime.py; package facts only.',
             '#pragma once', '#include "catalog.h"',
             'namespace dawn::state::activity::beyond_infinity {',
             'struct Slot { std::uint8_t type,flags; std::uint16_t index; std::uint32_t tag,offset,component,sense,auth; };',
             'struct Group { std::uint32_t key,tag; std::size_t hint; bool topLevel; std::uint8_t bubble; std::span<const Slot> slots; };']
    for i,g in enumerate(data['groups']):
        lines.append(f'inline constexpr Slot kSlots{i}[]{{')
        for s in g['slots']:
            lines.append('    {' + ','.join(str(s[k])+'U' for k in ('slotTypes','slotFlags','slotIndices','descriptorTags','descriptorOffsets','componentClasses','senseSchemas','authSchemas')) + '},')
        lines.append('};')
    lines.append('inline constexpr Group kGroups[]{')
    for i,g in enumerate(data['groups']):
        memberships=[(r['bubble'],o['array']) for r in data['regions'] for o in r['objects'] if o['registry']==g['registry']]
        assert memberships
        top=all(a==0 for _,a in memberships)
        assert top or len(memberships)==1, (g['registry'],memberships)
        lines.append(f'    {{0x{g["registry"]:08X}U,0x{g["objectTag"]:08X}U,{g["cacheIndex"]},{str(top).lower()},{memberships[0][0]},kSlots{i}}},')
    lines += ['};', 'struct SceneSpeech { std::uint8_t row; std::uint32_t offset,definition,input; };', 'struct SceneCue { std::uint8_t id; std::uint32_t offset,kind,definition,signal,signalKind,signalDefinition; };', 'struct SceneBinding { coo::Asset asset; std::uint32_t selector; std::span<const coo::Asset> cast; std::uint32_t selectorGraph; std::int64_t selectorOffset; std::span<const std::uint32_t> inputs; std::span<const SceneSpeech> speech; std::span<const SceneCue> cues; };']
    scenes=[]
    for key,s in slots.items():
        if key[1]!=43: continue
        _,b=read(s['descriptorTags']); offset=s['descriptorOffsets']
        assert s['componentClasses']==0x80806382 and s['authSchemas']==0x8080626B
        assert struct.unpack_from('<IHH',b,offset+0x30)==key
        targets=[]
        for ref in array(b,offset+0x68,8,0x80806268):
            target=ref+i64(b,ref)
            assert u32(b,target-4) in (0x80806262,0x80806264)
            target_key=struct.unpack_from('<IHH',b,target+8)
            assert target_key[1] in (1,4,30,48), target_key
            targets.append(target_key)
        assert len(targets)<=15
        i=len(scenes)
        lines.append(f'inline constexpr std::array<coo::Asset,{len(targets)}> kCast{i}{{{{'+','.join(asset(t) for t in targets)+'}};')
        selector=u32(b,offset+0x60)
        entity_class,entity=read(selector)
        assert entity_class==0x80809C0F
        graphs=[]
        for resource in array(entity,0x10,12):
            graph_tag=u32(entity,resource)
            graph_class,graph=read(graph_tag)
            if graph_class!=0x80809C36 or len(graph)<0xA0: continue
            if u32(graph,0x94)==0x80806384:
                assert u32(graph,0x90)==graph_tag
                graphs.append((graph_tag,i64(graph,0x98)))
        assert len(graphs)==1,(selector,graphs)
        graph_tag,graph_offset=graphs[0]
        events,speeches=playback(graph_tag,data)
        lines.append(f'inline constexpr std::array<std::uint32_t,{len(events)}> kSceneInputs{i}{{{{'+','.join(f'0x{e:08X}U' for e in events)+'}};')
        lines.append(f'inline constexpr std::array<SceneSpeech,{len(speeches)}> kSceneSpeech{i}{{{{'+','.join('{'+f'{row},0x{o:X}U,0x{d:X}U,{inp}U'+'}' for row,o,d,inp in speeches)+'}};')
        cue_rows=cues(graph_tag) if s['descriptorTags'] in (0x80F461D1,0x80F4608D) else []
        lines.append(f'inline constexpr std::array<SceneCue,{len(cue_rows)}> kSceneCues{i}{{{{'+','.join('{'+f'{idx},0x{o:X}U,0x{k:X}U,0x{d:X}U,0x{signal:X}U,0x{sk:X}U,0x{sd:X}U'+'}' for idx,o,k,d,signal,sk,sd,_ in cue_rows)+'}};')
        scenes.append((key,selector,i,*graphs[0]))
    lines.append('inline constexpr SceneBinding kScenes[]{')
    lines += [f'    {{{asset(key)},0x{selector:08X}U,kCast{i},0x{graph:08X}U,0x{offset:X},kSceneInputs{i},kSceneSpeech{i},kSceneCues{i}}},' for key,selector,i,graph,offset in scenes]
    lines += ['};', 'struct SourceBinding { coo::Asset asset; std::uint16_t rule; std::uint8_t categories; bool sceneOwned,hasRule; };',
              'inline constexpr SourceBinding kSources[]{']
    cast_sources=set()
    # Only actor references require scene-owned source authority.
    for key,_,_,_,_ in scenes:
        s=slots[key]; _,b=read(s['descriptorTags'])
        for ref in array(b,s['descriptorOffsets']+0x68,8,0x80806268):
            target=ref+i64(b,ref)
            if u32(b,target-4)==0x80806262:
                cast_sources.add(struct.unpack_from('<IHH',b,target+8))
    for s in data['sources']:
        key=(s['registry'],1,s['slot'])
        assert len(s['categories']) in (1,2)
        has_rule=s['ruleRegistry']==s['registry'] and s['ruleType']==66
        lines.append(f'    {{{asset(key)},{s["ruleSlot"] if has_rule else 0},{len(s["categories"])},{str(key in cast_sources).lower()},{str(has_rule).lower()}}},')
    lines += ['};', '// The package table structurally names activity 294 and the mission root.',
              'inline constexpr std::int16_t kActivity=294;',
              'inline constexpr std::uint32_t kInvestment=0x3E9433BDU,kActivityTag=0x80F46000U,kLaunchTag=0x80F9FDD2U;', '}','']
    _,b=read(0x81327CD8)
    joined=[]
    for row in array(b,8,72,0x80807A35):
        for item in array(b,row+56,80,0x80807A3A):
            if u32(b,item+24)==0x03632571:
                joined.append(struct.unpack_from('<h',b,item+18)[0])
    assert joined==[294], joined
    _,b=read(0x81327CF0)
    public=array(b,8,16)[294]
    assert u32(b,public)==0x3E9433BD
    return '\n'.join(lines)


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    content=render()
    if args.check:
        assert OUT.read_text()==content, 'Runtime catalog differs from installed package'
        print('PASS: runtime Scene casts, roster, and activity identity match installed packages')
    else:
        OUT.write_text(content,encoding='utf-8')
        print(OUT)
