"""Generate package facts only; this catalog grants no runtime capabilities."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
INPUT = ROOT / 'build/coo/beyond-infinity-research/native-bindings.json'
OUTPUT = ROOT / 'Dawn/src/state/activity/beyond_infinity/catalog.h'


def cpp(value):
    return json.dumps(value, ensure_ascii=True)


def floating(value):
    text = format(value, '.9g')
    if '.' not in text and 'e' not in text:
        text += '.0'
    return text + 'F'


def point(values):
    return '{' + ','.join(floating(value) for value in values) + '}'


def render(data, digest):
    lines = [
        '// Generated by tools/coo/generate_beyond_infinity_catalog.py.',
        '// Package facts, not a playable profile. Native controls/receipts remain unverified.',
        '#pragma once', '#include <array>', '#include <span>', '#include <string_view>',
        '#include "../coo/executor.h"',
        'namespace dawn::state::activity::beyond_infinity {',
        f'inline constexpr std::string_view kEvidenceSha256={cpp(digest)};',
        'inline constexpr std::uint32_t kScenario=0x80F46015U, kRoot=0x03632571U, kBank=0x80F1FDF7U;',
        'inline constexpr std::string_view kPackage="adventure_vod";',
        'struct AssetBinding final { std::string_view name; coo::Asset asset; std::uint32_t offset,component,sense,authority; };',
        'inline constexpr AssetBinding kAssets[]{',
    ]
    for group in data['groups']:
        for slot in group['slots']:
            lines.append(f'    {{{cpp(slot.get("name", ""))},'
                         f'{{0x{group["registry"]:08X}U,0x{slot["descriptorTags"]:08X}U,{slot["slotTypes"]},{slot["slotIndices"]}}},'
                         f'{slot["descriptorOffsets"]}U,0x{slot["componentClasses"]:08X}U,0x{slot["senseSchemas"]:08X}U,0x{slot["authSchemas"]:08X}U}},')
    lines += ['};', 'struct Objective final { std::uint32_t event; std::string_view title,description; };',
              'inline constexpr std::array<Objective,11> kObjectives{{']
    for row in data['objectives']:
        text = row['texts'][0]
        lines.append(f'    {{0x{row["event"]:08X}U,{cpp(text[0])},{cpp(text[1])}}},')
    lines += ['}};', '// Bank rows can contain compound or scene-owned speech. Ownership is not inferred here.',
              'struct DialogueMetadata final { std::uint32_t selector,durationMs; };',
              'inline constexpr std::array<DialogueMetadata,49> kDialogue{{']
    for row in data['dialogue']:
        lines.append(f'    {{0x{row["selector"]:08X}U,{row["durationMs"]}U}}, // row {row["row"]}')
    lines += ['}};', 'struct Point final { float x,y,z; };',
              'struct Volume final { std::string_view name; coo::Asset asset; Point min,max; std::span<const Point> vertices; };']
    for index, volume in enumerate(data['volumes']):
        lines.append(f'inline constexpr Point kVertices{index}[]{{' + ','.join(point(v) for v in volume['vertices']) + '};')
    lines += ['inline constexpr Volume kVolumes[]{']
    for index, volume in enumerate(data['volumes']):
        lines.append(f'    {{{cpp(volume["name"])},{{0x{volume["registry"]:08X}U,0x{volume["tag"]:08X}U,60,{volume["slot"]}}},'
                     f'{point(volume["min"])},{point(volume["max"])},kVertices{index}}},')
    lines += ['};',
              '[[nodiscard]] constexpr const AssetBinding* find(std::uint32_t registry,std::uint16_t type,std::uint16_t slot) noexcept {',
              '    for(const auto& item:kAssets) { if(item.asset.registry==registry && item.asset.type==type && item.asset.slot==slot) { return &item; } }',
              '    return nullptr;', '}',
              '[[nodiscard]] constexpr const Objective* objective(std::uint32_t event) noexcept {',
              '    for(const auto& item:kObjectives) { if(item.event==event) { return &item; } }',
              '    return nullptr;', '}',
              '} // namespace dawn::state::activity::beyond_infinity', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    blob = INPUT.read_bytes()
    data = json.loads(blob)
    assert data['scenario'] == 0x80F46015 and data['packageHash'] == 0x03632571
    rendered = render(data, hashlib.sha256(blob).hexdigest())
    if args.check:
        assert OUTPUT.read_text(encoding='utf-8') == rendered, 'Catalog differs from extracted package evidence.'
        print('PASS: C++ catalog matches extraction')
        return
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding='utf-8')
    print(OUTPUT)


if __name__ == '__main__':
    main()
