"""Generate A Deadly Trial bindings from the locally recovered native archive.
One actor per native category and nearest authored tactical row are reconstruction
policy, not recovered retail wave counts. No alternate waterfront/coastroad waves.
"""
import json,struct,hashlib,sys
from pathlib import Path
from package_read import read,ROOT
from extract_gateway_bindings import array
D=ROOT/'Sunrise/src/state/activity/deadly_trial'
R=ROOT/'build/coo/deadly-trial-research/native-bindings.json'
def emit(path,text):
 if '--check' in sys.argv:
  assert path.read_text()==text,f'Generated file differs: {path}'
 else:path.write_bytes(text.encode())
j=json.loads(R.read_text()); D.mkdir(parents=True,exist_ok=True)
A=0xEB7AF018;B=0xEB7AF01B;ROOTKEY=0xC9BC773A
hx=lambda n:f'0x{n:08X}U'
f=lambda n:format(n,'.9g')+('F' if '.' in format(n,'.9g') or 'e' in format(n,'.9g') else '.F')
pt=lambda p:'{'+','.join(map(f,p))+'}'
groups=[g for g in j['groups'] if g['cacheIndex']>=649]
slots={(g['registry'],s['slotTypes'],s['slotIndices']):s for g in groups for s in g['slots']}
H=['// Generated by tools/coo/generate_deadly_trial.py.','#pragma once','#include <array>','#include <span>','#include <string_view>','#include "../coo/dialogue_service.h"','#include "../coo/native_combatant_authority.h"','namespace sunrise::state::activity::deadly_trial {',f'inline constexpr std::uint32_t kScenario=0x80B2E043U,kRoot={hx(ROOTKEY)},kBank=0x80F1F086U,kAlleysA={hx(A)},kAlleysB={hx(B)};',f'inline constexpr std::string_view kEvidenceSha256="{hashlib.sha256(R.read_bytes()).hexdigest()}";', 'struct Slot { std::uint8_t type,flags;std::uint16_t index;std::uint32_t tag,offset,component,sense,auth; };','struct Group { std::uint32_t key,tag;std::size_t hint;bool topLevel;std::uint8_t bubble;std::span<const Slot> slots; };']
for i,g in enumerate(groups):
 H += [f'inline constexpr Slot kSlots{i}[]{{']
 for s in g['slots']: H += ['    {'+','.join(str(s[k]) if k in ('slotTypes','slotFlags','slotIndices') else hx(s[k]) for k in ('slotTypes','slotFlags','slotIndices','descriptorTags','descriptorOffsets','componentClasses','senseSchemas','authSchemas'))+'}, // '+s['name']]
 H+=['};']
H+=['inline constexpr Group kGroups[]{']
for i,g in enumerate(groups):
 refs=[r for r in j['regions'] if any(o['registry']==g['registry'] and o['array']==2 for o in r['objects'])]
 top=not refs; bubble=0 if top else refs[0]['bubble']
 assert top== (g['registry']==ROOTKEY)
 H += [f'    {{{hx(g["registry"])},{hx(g["objectTag"])},{g["cacheIndex"]},{str(top).lower()},{bubble},kSlots{i}}},']
H+=['};','struct Point { float x,y,z; };','struct Volume { std::uint32_t registry,tag;std::uint16_t slot;std::string_view name;Point min,max;std::span<const Point> vertices; };']
regs={o['registry'] for r in j['regions'] for o in r['objects']}
volumes=[v for v in j['volumes'] if v['registry'] in regs]
for i,v in enumerate(volumes):H += [f'inline constexpr Point kVertices{i}[]{{'+','.join(pt(p) for p in v['vertices'])+'};']
H+=['inline constexpr Volume kVolumes[]{']
for i,v in enumerate(volumes):H += [f'    {{{hx(v["registry"])},{hx(v["tag"])},{v["slot"]},"{v["name"]}",{pt(v["min"])},{pt(v["max"])},kVertices{i}}},']
H+=['};','inline constexpr coo::DialogueRow kDialogueRows[]{']
for r in j['dialogue']:H += [f'    {{{hx(r["selector"])},{r["durationMs"]},0,{str(r["row"] in (9,10)).lower()}}},']
H += ['};','inline constexpr coo::DialogueDefinition kDialogue{kBank,kDialogueRows,{}};','inline constexpr std::uint32_t kObjectives[]{'+','.join(hx(o['event']) for o in j['objectives'] if o['event'])+'};']
# Cohorts 1 square; 2 streets; 3 choke; 4 Walker; 5 support; 6 cliff;
# 7 tunnel; 8 tower; 9 lair. Required cohorts 1,4,8,9 use real deaths.
choose={A:{1:[1,2,3],2:[12,13,14,15,16],3:[17,18,19,20],4:[23],5:[25,26,27,28,31]},B:{6:list(range(1,8)),7:[15,16,17],8:list(range(25,40)),9:[53,55,57,58]}}
sources=[]
for reg,cohorts in choose.items():
 for cohort,indices in cohorts.items():
  for index in indices:
   s=next(s for s in j['sources'] if s['registry']==reg and s['slot']==index)
   assert 1<=len(s['categories'])<=2 and s['ruleRegistry']==reg and s['ruleType']==66
   sources.append(dict(s,cohort=cohort))
# Native encounter maps contain provider tables. Source placement selects among
# their authored tactical rows; those rows remain native combat tasks.
providers={}
for tag in (0x80B2E29A,0x80B2EA48):
 _,b=read(tag)
 try:
  areas={struct.unpack_from('<Q',b,p)[0]:{'min':struct.unpack_from('<3f',b,p+32),'max':struct.unpack_from('<3f',b,p+48)} for p in array(b,0x200,128,0x80808354)}
  rows=array(b,0x210,32,0x80808350)
 except (AssertionError,ValueError,struct.error):continue
 if areas:
  reg= A if tag==0x80B2E29A else B
  providers[reg]={struct.unpack_from('<I',b,p+12)[0]:[areas[struct.unpack_from('<Q',b,q)[0]] for q in array(b,p+16,16)] for p in rows}
assert set(providers)=={A,B},providers.keys()
H+=['struct Spawn { std::uint16_t source;std::uint32_t registry,definition,offset;std::uint16_t rule;std::uint8_t count,categories,cohort;coo::native_combatant::TacticalGroup tactical;bool required; };',f'inline constexpr std::array<Spawn,{len(sources)}> kSpawns{{{{']
joins=[]
for s in sources:
 reg=s['registry'];gslot={1:0,2:7,3:7,4:21,5:21,6:0,7:13,8:18,9:52}[s['cohort']]
 t=slots[reg,3,gslot];_,b=read(t['descriptorTags']);rows=[]
 for index,p in enumerate(array(b,t['descriptorOffsets']+0x88,40)):
  areas=[]
  for q in array(b,p+16,40):
   rr,kind,slot=struct.unpack_from('<IHH',b,q+32);assert rr==reg and kind==45
   areas+=providers[reg][slot]
  if areas:rows.append((index,areas))
 rule=slots[reg,66,s['ruleSlot']];_,rb=read(rule['descriptorTags']);guid=struct.unpack_from('<Q',rb,0x3C0)[0]
 points=[p['position'] for p in j['placements'] if p['guid']==guid];assert points,(s['name'],hex(guid))
 xyz=[sum(p[i] for p in points)/len(points) for i in range(3)]
 def rank(row):
  idx,areas=row
  return min((sum(max(lo-x,0,x-hi)**2 for x,lo,hi in zip(xyz,a['min'],a['max'])),sum((x-(lo+hi)/2)**2 for x,lo,hi in zip(xyz,a['min'],a['max'])),idx) for a in areas)
 row=min(rows,key=rank)[0];assert row<24
 H += [f'    {{{s["slot"]},{hx(reg)},{hx(s["tag"])},{hx(s["offset"])},{s["ruleSlot"]},{len(s["categories"])},{len(s["categories"])},{s["cohort"]},{{{hx(reg)},{gslot},{row}}},{str(s["cohort"] in (1,4,8,9)).lower()}}}, // {s["name"]}']
 joins.append({'registry':reg,'source':s['slot'],'group':gslot,'row':row,'guid':hex(guid),'points':points})
H+=['}};','constexpr const Spawn* spawn(std::uint32_t registry,std::uint16_t slot) noexcept { for(const auto& s:kSpawns) { if(s.registry==registry && s.source==slot) { return &s; } } return nullptr; }','struct EnemyReceipt { std::uint64_t run{};std::uint32_t actor{},owner{},generation{};std::uint16_t source{};std::uint32_t registry{};bool valid() const noexcept { return run && generation && actor!=UINT32_MAX && owner!=UINT32_MAX && spawn(registry,source); } bool operator==(const EnemyReceipt&) const noexcept=default; };','}']
emit(D/'catalog.h','\n'.join(H)+'\n')
emit(R.parent/'tactical-joins.json',json.dumps(joins,indent=2)+'\n')
# Executable authoring contract; immutable capability identities and dependencies.
assets={'module':(ROOTKEY,0x80B2E043,0,0),'facts':(0,0,0,0),'objective':(ROOTKEY,0x80B2E706,68,0),'dialogue':(ROOTKEY,0x80B2E709,53,2),'revive':(B,0x80B2EBA7,4,59),'scene':(0x27660927,0x80B2E6D7,65,0),'barrier':(A,0x80B2E3AD,23,46)}
def volume(alias,reg,slot):
 v=next(v for v in volumes if v['registry']==reg and v['slot']==slot);assets[alias]=(reg,v['tag'],60,slot)
volume('landing',0x3A62993F,2);volume('square',0x40ADE010,3);volume('followers',0x38C174BB,2);volume('streets',A,214);volume('choke',A,229);volume('overpass',A,131);volume('trial',0x4DDB8242,2);volume('cliff',B,157);volume('tunnel',B,223);volume('tower',0xBC1C972B,2);volume('lair',B,195);volume('bodies',0x9F8CA248,2)
bindings={};steps={'opening':[],'ending':[]};caps=[]
def cap(domain,id,op,asset,arg=0,wait='requested'):
 bindings[id]={'capability':id,'operation':op,'asset':asset,'argument':arg,'wait':wait};caps.append((id,domain,op,asset,arg,wait));return id
for id,op,asset,arg,wait in [('opening.module','mechanic','module',1,'requested'),('opening.checked','observation','facts',0,'observed')]:cap('composition',id,op,asset,arg,wait)
def step(domain,id,cmds,after=None):
 seq=steps[domain];deps=([seq[-1]['id']] if seq else []) if after is None else after
 seq.append({'id':id,'after':deps,'commands':[{'id':c,'binding':cap(domain,*cdata)} for cdata in cmds for c in [cdata[0]]]})
def obs(id):return(id+'.entered','observation',id,0,'observed')
def obj(id,n):return(id,'objective','objective',j['objectives'][n]['event'],'requested')
def dia(n):return('dialogue.'+str(n),'dialogue','dialogue',n,'nativeReady')
def pop(id,n,wait='requested'):return(id,'population','module',n,wait)
step('opening','arrival',[obs('landing')])
step('opening','coordinates',[obj('objective.coordinates',0),dia(0)])
step('opening','square',[obs('square')])
step('opening','square_fallen',[pop('square.fallen',1,'completed')])
step('opening','pikes',[obj('objective.pike',2),('square.pikes','device','module',1,'requested')])
step('opening','followers',[obs('followers')])
step('opening','faith',[dia(1),obj('objective.path',3)])
step('opening','streets',[obs('streets')])
step('opening','street_resistance',[pop('streets.fallen',2)])
step('opening','choke',[obs('choke')])
step('opening','choke_resistance',[pop('choke.fallen',3)])
step('opening','overpass',[obs('overpass')])
step('opening','roadblock',[obj('objective.walker',4),pop('overpass.support',5),pop('walker.dead',4,'completed')])
step('opening','barrier',[('barrier.open','device','barrier',0,'requested'),obj('objective.temple',5),('overpass.pikes','device','module',2,'requested')])
step('opening','trial',[obs('trial')])
step('opening','survival',[dia(2)])
step('opening','cliff',[obs('cliff')])
step('opening','cliff_resistance',[pop('cliff.fallen',6)])
step('opening','tunnel',[obs('tunnel')])
step('opening','tunnel_resistance',[pop('tunnel.fallen',7)])
step('opening','tower',[obs('tower')])
step('opening','tower_resistance',[dia(4),pop('tower.fallen',8,'completed')])
step('opening','search',[obj('objective.search',6)])
step('ending','lair',[obs('lair')])
step('ending','ambush',[pop('lair.marauders',9,'completed')])
step('ending','bodies',[obs('bodies')])
step('ending','followers_dead',[dia(7),obj('objective.revive',7),('revive.enable','device','revive',1,'requested')])
step('ending','interact',[('revive.accepted','observation','revive',1,'observed')])
step('ending','prelude_finished',[('prelude.finished','eventAfter','dialogue',7,'observed')])
step('ending','revival',[('revive.scene','scene','scene',1,'nativeReady')])
step('ending','revival_finished',[('revive.scene_finished','observation','scene',2,'observed'),('revive.audio_finished','eventAfter','scene',3,'observed')])
step('ending','finish',[('mission.finish','complete','module',6,'requested')])
root={'name':'A Deadly Trial','domain':'composition','steps':[{'id':'mission','after':[],'commands':[{'id':x,'binding':x} for x in ['opening.module','opening.checked']]}],'receipts':{'opening.checked':'opening.checked'}}
graphs={'composition':root}
for domain,seq in steps.items():graphs[domain]={'name':'A Deadly Trial '+domain,'domain':domain,'steps':seq,'receipts':{c['id']:c['id'] for step in seq for c in step['commands'] if bindings[c['binding']]['wait']!='requested'}}
script={'format_version':2,'mission':'deadly_trial','profile':'deadly_trial.native.v1','authority_schema':'otherMissions','assets':{k:{'registry':f'0x{v[0]:08X}','definition':f'0x{v[1]:08X}','type':v[2],'slot':v[3]} for k,v in assets.items()},'bindings':bindings,'graphs':graphs,'roles':{'mission':'composition','opening':'opening','ending':'ending'},'entry':'composition','modules':['opening'],'observations':[{'fact':'opening.checked','receipt':'opening.checked'}],'presentation':{'dialogue':{'bank':'0x80F1F086','rows':[{'row':r['row'],'selector':f'0x{r["selector"]:08X}','duration_ms':r['durationMs'],'native_delay_ms':0,'scene_owned':r['row'] in (9,10)} for r in j['dialogue']],'objective_cues':[],'dispatch_timeout_ms':15000,'spacing_ms':250},'cue_sets':{},'action_sets':{},'binding_tables':{},'markers':[]}}
emit(ROOT/'Sunrise/scripts/deadly_trial.json',json.dumps(script,indent=2)+'\n')
asset=lambda key:'{'+','.join([hx(assets[key][0]),hx(assets[key][1]),str(assets[key][2]),str(assets[key][3])])+'}'
H=['// Generated by tools/coo/generate_deadly_trial.py.','#pragma once','#include "catalog.h"','#include "../coo/mission_script.h"','namespace sunrise::state::activity::deadly_trial {',f'inline constexpr coo::Asset kModule{asset("module")},kRevive{asset("revive")},kScene{asset("scene")},kBarrier{asset("barrier")};','inline constexpr coo::script::Capability kCapabilities[]{']
for id,dom,op,a,arg,w in caps:H += [f'    {{"{id}","{dom}",{{coo::Operation::{op},{asset(a)},{arg}U,coo::Wait::{w}}}}},']
H+=['};','inline constexpr coo::script::ModuleCapability kModules[]{{"opening",{kModule,1}}};','inline constexpr coo::script::FactCapability kFacts[]{{"opening.checked",0}};','inline constexpr coo::script::Profile kProfile{"deadly_trial.native.v1","otherMissions",coo::Schema::otherMissions,kCapabilities,kModules,kFacts,kDialogue,kObjectives,{},{},{}};','struct ContractStep { std::uint32_t dependencies;std::span<const std::string_view> commands; };']
for dom,seq in steps.items():
 for i,s in enumerate(seq):H += [f'inline constexpr std::string_view k_{dom}_{i}[]{{'+','.join('"'+c['binding']+'"' for c in s['commands'])+'};']
 H += [f'inline constexpr ContractStep k{dom.title()}Contract[]{{']
 for i,s in enumerate(seq):H += ['    {'+str(sum(1<<next(n for n,x in enumerate(seq) if x['id']==d) for d in s['after']))+f'U,k_{dom}_{i}'+'},']
 H+=['};']
H+=['inline constexpr coo::ObjectiveMarker kNativeMarkers[]{',
'    {0xEC217779U,{{0x40ADE010U,0x80B2E62BU,47,1},{0x29930BA4U,0xC6905B77U,0x40ADE010U,0xBA2B60FDU}}},',
'    {0xDA95AE49U,{{0xECC3696FU,0x80B2E6E9U,47,1},{0x29930BA4U,0xC6905B77U,0xECC3696FU,0x24A5314AU}}},',
'    {0x183F9715U,{{0x38C174BBU,0x80B2E66BU,47,7},{0x29930BA4U,0xC6905B77U,0x38C174BBU,0xC704236EU}}},',
'    {0x6FB8A85AU,{{0xE4BA2E54U,0x80B2E68DU,47,0},{0x29930BA4U,0xC6905B77U,0xE4BA2E54U,0xE58495E9U}}},',
'    {0xE58BB2F6U,{{0xC91BDFF0U,0x80B2EC47U,47,4},{0x29930BA4U,0xC6905B74U,0xC91BDFF0U,0x69AEC903U}}},',
'    {0x882DD31EU,{{0xBC1C972BU,0x80B2EC53U,47,10},{0x29930BA4U,0xC6905B74U,0xBC1C972BU,0x69AEC903U}}},',
'    {0x708B9351U,{{0x27660927U,0x80B2EC62U,47,4},{0x29930BA4U,0xC6905B74U,0x27660927U,0x9BEEEAA2U}}},',
'};','bool valid_document(const coo::script::Views&) noexcept;','}']
emit(D/'profile.h','\n'.join(H)+'\n')
print(f'Generated {len(groups)} groups, {len(volumes)} volumes, {len(sources)} combat sources, {sum(len(s["categories"]) for s in sources)} actors, and both mission graphs.')
