"""Generate Hijacked's exact source-to-placement catalog from installed packages."""
import argparse, json, struct
from pathlib import Path
import package_read as packages
ROOT=packages.ROOT
OUT=ROOT/'Dawn/src/state/activity/hijacked/placement_catalog.h'
p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');args=p.parse_args()
report=json.loads((ROOT/'build/coo/hijacked-research/tactical-joins.json').read_text())
# These are the recovered entity tables, including the shared Nessus point used by Mists source7.
tables=(0x80B420E0,0x80B42549,0x80B427F3,0x81582ABD)
placements={}
for table in tables:
 cls,b=packages.read(table);assert cls==0x808099D6
 count=struct.unpack_from('<I',b,8)[0];start=0x20+struct.unpack_from('<q',b,0x10)[0]
 assert 0<count<4096 and start>=0x20 and start+count*0x90<=len(b)
 for row in range(count):
  offset=start+row*0x90;raw=b[offset:offset+0x90];guid=struct.unpack_from('<Q',raw,0x70)[0]
  if guid in (0,0xffffffffffffffff):continue
  h=0xcbf29ce484222325
  for byte in raw:h=((h^byte)*0x100000001b3)&0xffffffffffffffff
  placements.setdefault(guid,[]).append((table,row,offset,struct.unpack_from('<I',raw)[0],guid,h))
data=json.loads((ROOT/'build/coo/hijacked-research/native-bindings.json').read_text())
slots={(g['registry'],s['slotTypes'],s['slotIndices']):s for g in data['groups'] for s in g['slots']}
rows=[]
for source in report['joins']:
 registry,slot=source['registry'],source['source'];rule=slots[registry,66,source['rule']]
 _,b=packages.read(rule['descriptorTags']);needle=struct.pack('<I',0x80809845)
 starts=[i for i in range(0,len(b)-4,4) if b[i:i+4]==needle];assert len(starts)==1
 at=starts[0];count=struct.unpack_from('<Q',b,at-8)[0];assert 0<count<=8
 guids=[struct.unpack_from('<Q',b,at+8+8*i)[0] for i in range(count)]
 for guid in guids:
  found=placements.get(guid,[]);assert len(found)==1,(registry,slot,hex(guid),found)
  rows.append((registry,slot,{0x153E22CD:33,0x3E9B74F3:37,0xD997395E:40}[registry],*found[0]))
assert len({(x[0],x[1]) for x in rows})==56
lines=['// Generated by tools/coo/generate_hijacked_placements.py from installed package tables.',
 '#pragma once','#include <array>','#include <cstddef>','#include <cstdint>','#include <span>',
 'namespace dawn::state::activity::hijacked {',
 'struct Placement { std::uint32_t registry;std::uint16_t source,bubble;std::uint32_t table,record,offset,entity;std::uint64_t guid,descriptorHash; };',
 f'inline constexpr std::array<Placement,{len(rows)}> kPlacements{{{{']
for reg,src,bubble,table,row,off,entity,guid,h in rows:
 lines.append(f'    {{0x{reg:08X}U,{src},{bubble},0x{table:08X}U,{row},0x{off:X}U,0x{entity:08X}U,0x{guid:016X}ULL,0x{h:016X}ULL}},')
lines+=['}};','inline std::uint64_t placement_hash(std::span<const std::byte> bytes) noexcept {',
 '    std::uint64_t h=0xCBF29CE484222325ULL;for(const auto b:bytes) { h=(h^std::to_integer<std::uint8_t>(b))*0x100000001B3ULL; }return h;',
 '}','}']
text='\n'.join(lines)+'\n'
if args.check:assert OUT.read_text()==text,'Placement catalog changed'
else:OUT.write_text(text)
print(('Verified' if args.check else 'Generated'),len(rows),'authored placements for56source bindings; native tables and original descriptors preserved')
