"""Join native Future ambush sources to authored tactical areas by placement.
Area identities and bounds are package facts. Nearest bounds, then center, then
row is the same explicit reconstruction policy used by Gateway.
"""
import argparse,json,math,re,struct
from package_read import read,ROOT
from extract_gateway_bindings import array
OUT=ROOT/'build/coo/beyond-infinity-final-polish'
TARGET=ROOT/'Sunrise/src/state/activity/beyond_infinity/ai_bindings.h'
u32=lambda b,o:struct.unpack_from('<I',b,o)[0]
u64=lambda b,o:struct.unpack_from('<Q',b,o)[0]
def generate():
 data=json.loads((ROOT/'build/coo/beyond-infinity-research/native-bindings.json').read_text())
 registry=0x0FF26BCC
 group=next(g for g in data['groups'] if g['registry']==registry)
 slots={(s['slotTypes'],s['slotIndices']):s for s in group['slots']}
 _,b=read(0x80F46039)
 areas={u64(b,p):{'slot':u32(b,p+16),'min':struct.unpack_from('<3f',b,p+32),'max':struct.unpack_from('<3f',b,p+48)} for p in array(b,0x200,128,0x80808354)}
 providers={u32(b,p+12):[areas[u64(b,q)] for q in array(b,p+16,16)] for p in array(b,0x210,32,0x80808350)}
 task=slots[3,0];assert task['authSchemas']==0x80807F0C
 _,b=read(task['descriptorTags']);rows=[]
 for idx,p in enumerate(array(b,task['descriptorOffsets']+0x88,40)):
  ps=[]
  for q in array(b,p+16,40):
   reg,kind,slot=struct.unpack_from('<IHH',b,q+32)
   assert (reg,kind)==(registry,45)
   ps.append({'slot':slot,'areas':providers[slot]})
  assert ps;rows.append({'row':idx,'providers':ps})
 assert len(rows)==7
 points={}
 for tag in range(0x80F46000,0x80F460E1):
  try:_,b=read(tag)
  except (KeyError,ValueError,AssertionError):continue
  for m in re.finditer(re.escape(struct.pack('<II',0x304,0)),b):
   p=m.start()-0x68
   if p<0 or p%16 or p+0x78>len(b):continue
   xyz=struct.unpack_from('<3f',b,p+0x20)
   if u32(b,p+0x2C)!=0x3F800000 or not all(math.isfinite(x) and abs(x)<10000 for x in xyz):continue
   points.setdefault(u64(b,p+0x70),[]).append({'tag':tag,'offset':p,'position':xyz})
 joins=[]
 for source in data['sources']:
  if source['registry']!=registry or not 6<=source['slot']<=14:continue
  rule=slots[66,source['ruleSlot']];_,b=read(rule['descriptorTags'])
  guid=u64(b,0x3C0);placements=points.get(guid,[])
  assert placements,(source,hex(guid))
  unique=sorted(set(tuple(p['position']) for p in placements))
  xyz=tuple(sum(p[i] for p in unique)/len(unique) for i in range(3))
  ranked=[]
  for row in rows:
   choices=[]
   for provider in row['providers']:
    for a in provider['areas']:
     d=sum(max(lo-x,0,x-hi)**2 for x,lo,hi in zip(xyz,a['min'],a['max']))
     c=sum((x-(lo+hi)/2)**2 for x,lo,hi in zip(xyz,a['min'],a['max']))
     choices.append((d,c))
   ranked.append((*min(choices),row['row']))
  ranked.sort()
  joins.append({'source':source['slot'],'row':ranked[0][2],'placements':placements,'rankedRows':ranked})
 assert len(joins)==9
 lines=['// Generated by generate_beyond_infinity_ai.py; native areas, placement policy.','#pragma once','#include "../coo/native_combatant_authority.h"','namespace sunrise::state::activity::beyond_infinity {','constexpr coo::native_combatant::TacticalGroup tactical_group(coo::Asset source) noexcept {','    if(source.registry!=0x0FF26BCCU || source.type!=1) { return {}; }','    switch(source.slot) {']
 for j in joins:lines.append('    case %d: return {0x0FF26BCCU,0,%d};'%(j['source'],j['row']))
 lines+=['    default: return {};','    }','}','}','']
 return '\n'.join(lines),{'policy':__doc__,'task':task,'rows':rows,'joins':joins}
if __name__=='__main__':
 parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
 header,report=generate()
 if args.check:assert TARGET.read_text()==header
 else:
  TARGET.write_text(header);OUT.mkdir(exist_ok=True,parents=True);(OUT/'tactical-joins.json').write_text(json.dumps(report,indent=2))
 print('PASS: nine native ambush tactical assignments',[(j['source'],j['row']) for j in report['joins']])
