"""Generate A Deadly Trial bindings from the locally recovered native archive.
One actor per native category and nearest authored tactical row are reconstruction
policy, not recovered retail wave counts. No alternate waterfront/coastroad waves.
"""
import json,struct,hashlib,sys
from pathlib import Path
from package_read import read,ROOT
from extract_gateway_bindings import array
D=ROOT/'Sunrise/src/state/activity/deadly_trial'
R=ROOT/'build/coo/deadly-trial-research/native-bindings.json'
def emit(path,text):
 if '--check' in sys.argv:
  assert path.read_text()==text,f'Generated file differs: {path}'
 else:path.write_bytes(text.encode())
j=json.loads(R.read_text()); D.mkdir(parents=True,exist_ok=True)
A=0xEB7AF018;B=0xEB7AF01B;ROOTKEY=0xC9BC773A
hx=lambda n:f'0x{n:08X}U'
f=lambda n:format(n,'.9g')+('F' if '.' in format(n,'.9g') or 'e' in format(n,'.9g') else '.F')
pt=lambda p:'{'+','.join(map(f,p))+'}'
groups=[g for g in j['groups'] if g['cacheIndex']>=649]
slots={(g['registry'],s['slotTypes'],s['slotIndices']):s for g in groups for s in g['slots']}
H=['// Generated by tools/coo/generate_deadly_trial.py.','#pragma once','#include <array>','#include <span>','#include <string_view>','#include "../coo/dialogue_service.h"','#include "../coo/native_combatant_authority.h"','namespace sunrise::state::activity::deadly_trial {',f'inline constexpr std::uint32_t kScenario=0x80B2E043U,kRoot={hx(ROOTKEY)},kBank=0x80F1F086U,kAlleysA={hx(A)},kAlleysB={hx(B)};',f'inline constexpr std::string_view kEvidenceSha256="{hashlib.sha256(R.read_bytes()).hexdigest()}";', 'struct Slot { std::uint8_t type,flags;std::uint16_t index;std::uint32_t tag,offset,component,sense,auth; };','struct Group { std::uint32_t key,tag;std::size_t hint;bool topLevel;std::uint8_t bubble;std::span<const Slot> slots; };']
for i,g in enumerate(groups):
 H += [f'inline constexpr Slot kSlots{i}[]{{']
 for s in g['slots']: H += ['    {'+','.join(str(s[k]) if k in ('slotTypes','slotFlags','slotIndices') else hx(s[k]) for k in ('slotTypes','slotFlags','slotIndices','descriptorTags','descriptorOffsets','componentClasses','senseSchemas','authSchemas'))+'}, // '+s['name']]
 H+=['};']
H+=['inline constexpr Group kGroups[]{']
for i,g in enumerate(groups):
 refs=[r for r in j['regions'] if any(o['registry']==g['registry'] and o['array']==2 for o in r['objects'])]
 top=not refs; bubble=0 if top else refs[0]['bubble']
 assert top== (g['registry']==ROOTKEY)
 H += [f'    {{{hx(g["registry"])},{hx(g["objectTag"])},{g["cacheIndex"]},{str(top).lower()},{bubble},kSlots{i}}},']
H+=['};','struct Point { float x,y,z; };','struct Volume { std::uint32_t registry,tag;std::uint16_t slot;std::string_view name;Point min,max;std::span<const Point> vertices; };']
regs={o['registry'] for r in j['regions'] for o in r['objects']}
volumes=[v for v in j['volumes'] if v['registry'] in regs]
for i,v in enumerate(volumes):H += [f'inline constexpr Point kVertices{i}[]{{'+','.join(pt(p) for p in v['vertices'])+'};']
H+=['inline constexpr Volume kVolumes[]{']
for i,v in enumerate(volumes):H += [f'    {{{hx(v["registry"])},{hx(v["tag"])},{v["slot"]},"{v["name"]}",{pt(v["min"])},{pt(v["max"])},kVertices{i}}},']
H+=['};','inline constexpr coo::DialogueRow kDialogueRows[]{']
for r in j['dialogue']:H += [f'    {{{hx(r["selector"])},{r["durationMs"]},0,{str(r["row"] in (9,10)).lower()}}},']
H += ['};','inline constexpr coo::DialogueDefinition kDialogue{kBank,kDialogueRows,{}};','inline constexpr std::uint32_t kObjectives[]{'+','.join(hx(o['event']) for o in j['objectives'] if o['event'])+'};']
# Cohorts 1 square; 2 streets; 3 choke; 4 Walker; 5 support; 6 cliff;
# 7 tunnel; 8 tower; 9 lair. Required cohorts 1,4,8,9 use real deaths.
choose={A:{1:[1,2,3],2:[12,13,14,15,16],3:[17,18,19,20],4:[23],5:[25,26,27,28,31]},B:{6:list(range(1,8)),7:[15,16,17],8:list(range(25,40)),9:[53,55,57,58]}}
sources=[]
for reg,cohorts in choose.items():
 for cohort,indices in cohorts.items():
  for index in indices:
   s=next(s for s in j['sources'] if s['registry']==reg and s['slot']==index)
   assert 1<=len(s['categories'])<=2 and s['ruleRegistry']==reg and s['ruleType']==66
   sources.append(dict(s,cohort=cohort))
# Native encounter maps contain provider tables. Source placement selects among
# their authored tactical rows; those rows remain native combat tasks.
providers={}
for tag in (0x80B2E29A,0x80B2EA48):
 _,b=read(tag)
 try:
  areas={struct.unpack_from('<Q',b,p)[0]:{'min':struct.unpack_from('<3f',b,p+32),'max':struct.unpack_from('<3f',b,p+48)} for p in array(b,0x200,128,0x80808354)}
  rows=array(b,0x210,32,0x80808350)
 except (AssertionError,ValueError,struct.error):continue
 if areas:
  reg= A if tag==0x80B2E29A else B
  providers[reg]={struct.unpack_from('<I',b,p+12)[0]:[areas[struct.unpack_from('<Q',b,q)[0]] for q in array(b,p+16,16)] for p in rows}
assert set(providers)=={A,B},providers.keys()
H+=['struct Spawn { std::uint16_t source;std::uint32_t registry,definition,offset;std::uint16_t rule;std::uint8_t count,categories,cohort;coo::native_combatant::TacticalGroup tactical;bool required; };',f'inline constexpr std::array<Spawn,{len(sources)}> kSpawns{{{{']
joins=[]
for s in sources:
 reg=s['registry'];gslot={1:0,2:7,3:7,4:21,5:21,6:0,7:13,8:18,9:52}[s['cohort']]
 t=slots[reg,3,gslot];_,b=read(t['descriptorTags']);rows=[]
 for index,p in enumerate(array(b,t['descriptorOffsets']+0x88,40)):
  areas=[]
  for q in array(b,p+16,40):
   rr,kind,slot=struct.unpack_from('<IHH',b,q+32);assert rr==reg and kind==45
   areas+=providers[reg][slot]
  if areas:rows.append((index,areas))
 rule=slots[reg,66,s['ruleSlot']];_,rb=read(rule['descriptorTags']);guid=struct.unpack_from('<Q',rb,0x3C0)[0]
 points=[p['position'] for p in j['placements'] if p['guid']==guid];assert points,(s['name'],hex(guid))
 xyz=[sum(p[i] for p in points)/len(points) for i in range(3)]
 def rank(row):
  idx,areas=row
  return min((sum(max(lo-x,0,x-hi)**2 for x,lo,hi in zip(xyz,a['min'],a['max'])),sum((x-(lo+hi)/2)**2 for x,lo,hi in zip(xyz,a['min'],a['max'])),idx) for a in areas)
 row=min(rows,key=rank)[0];assert row<24
 H += [f'    {{{s["slot"]},{hx(reg)},{hx(s["tag"])},{hx(s["offset"])},{s["ruleSlot"]},{len(s["categories"])},{len(s["categories"])},{s["cohort"]},{{{hx(reg)},{gslot},{row}}},{str(s["cohort"] in (1,4,8,9)).lower()}}}, // {s["name"]}']
 joins.append({'registry':reg,'source':s['slot'],'group':gslot,'row':row,'guid':hex(guid),'points':points})
H+=['}};','constexpr const Spawn* spawn(std::uint32_t registry,std::uint16_t slot) noexcept { for(const auto& s:kSpawns) { if(s.registry==registry && s.source==slot) { return &s; } } return nullptr; }','struct EnemyReceipt { std::uint64_t run{};std::uint32_t actor{},owner{},generation{};std::uint16_t source{};std::uint32_t registry{};bool valid() const noexcept { return run && generation && actor!=UINT32_MAX && owner!=UINT32_MAX && spawn(registry,source); } bool operator==(const EnemyReceipt&) const noexcept=default; };','}']
emit(D/'catalog.h','\n'.join(H)+'\n')
emit(R.parent/'tactical-joins.json',json.dumps(joins,indent=2)+'\n')
# Native controls are reviewed in deadly_trial/bindings.h. Mission flow is authored
# in scripts/deadly_trial.lua; regeneration must never overwrite either file.
print(f'Generated {len(groups)} groups, {len(volumes)} volumes, {len(sources)} combat sources and {sum(len(s["categories"]) for s in sources)} actors. Mission bindings and Lua are unchanged.')
