"""Generate the pinned Gateway catalog from decoded package/cache evidence.
The catalog grants roster and presentation identity only, not enemy spawn requests.
"""
import argparse, hashlib, json
from pathlib import Path
import extract_gateway_bindings as e
ROOT=e.ROOT
TARGET=ROOT/'Dawn/src/state/activity/gateway/catalog.h'

def generate():
 g=e.groups(); volumes=e.volumes(); dialogue=e.dialogue(); objectives=e.objectives()
 payload={'groups':g,'volumes':volumes,'dialogue':dialogue,'objectives':objectives,'sources':e.sources(g)}
 sha=hashlib.sha256(json.dumps(payload,sort_keys=True,separators=(',',':')).encode()).hexdigest()
 lines=['// Generated by tools/coo/generate_gateway_catalog.py; do not edit.', '#pragma once',
 '#include <array>', '#include <cstdint>', '#include <span>', '#include <string_view>',
 '#include "../coo/dialogue_service.h"',
 'namespace dawn::state::activity::gateway {',
 'inline constexpr std::string_view kEvidenceSha256="'+sha+'";',
 'inline constexpr std::uint32_t kScenario=0x80F46DB0U, kRoot=0x986985D0U, kBubbleHash=0xA83A9175U, kBank=0x80F1FC9EU;',
 'inline constexpr int kRegion=120;',
 'struct Slot final { std::uint8_t type,flags; std::uint16_t index; std::uint32_t tag,offset,component,sense,auth; };',
 'struct Group final { std::uint32_t key,tag; std::size_t hint; bool topLevel; std::span<const Slot> slots; };']
 for i,group in enumerate(g):
  lines.append('inline constexpr Slot kSlots'+str(i)+'[]{')
  for a in group['slots']:
   lines.append('    {%d,%d,%d,%s}, // %s'%(a['slotTypes'],a['slotFlags'],a['slotIndices'],','.join('0x%08XU'%a[k] for k in ['descriptorTags','descriptorOffsets','componentClasses','senseSchemas','authSchemas']),a['name'] if 'name' in a else ''))
  lines.append('};')
 lines.append('inline constexpr Group kGroups[]{')
 for i,group in enumerate(g): lines.append('    {0x%08XU,0x%08XU,%d,%s,kSlots%d},'%(group['registry'],group['objectTag'],group['cacheIndex'],str(group['topLevel']).lower(),i))
 lines.extend(['};','struct Point final { float x,y,z; };','struct Volume final { std::uint32_t registry; std::uint16_t slot; std::string_view name; Point min,max; std::span<const Point> vertices; };'])
 def pt(v):return '{'+','.join(format(x,'.9f')+'F' for x in v)+'}'
 for i,v in enumerate(volumes):lines.append('inline constexpr Point kVertices%d[]{%s};'%(i,','.join(pt(p) for p in v['vertices'])))
 lines.append('inline constexpr Volume kVolumes[]{')
 for i,v in enumerate(volumes):lines.append('    {0x%08XU,%d,"%s",%s,%s,kVertices%d},'%(v['registry'],v['slot'],v['name'],pt(v['min']),pt(v['max']),i))
 lines.extend(['};','inline constexpr coo::DialogueRow kDialogueRows[]{'])
 for r in dialogue:lines.append('    {0x%sU,%d,0,%s}, // row %d'%(r['selector'],r['durationMs'],str(r['row']==0 or r['row']>=11).lower(),r['row']))
 lines.extend(['};','inline constexpr std::uint32_t kObjectives[]{'+','.join('0x'+r['event']+'U' for r in objectives)+'};','inline constexpr coo::DialogueDefinition kDialogue{kBank,kDialogueRows,{}};','} // namespace dawn::state::activity::gateway',''])
 return '\n'.join(lines),payload

def main():
 parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
 content,data=generate()
 if args.check:
  assert TARGET.read_bytes()==content.encode(), 'Generated Gateway catalog differs from package evidence'
 else:
  TARGET.parent.mkdir(parents=True,exist_ok=True);TARGET.write_bytes(content.encode())
  (e.OUT/'gateway-authored-bindings.json').write_text(json.dumps(data,indent=2)+'\n')
 print('Gateway catalog:',len(data['groups']),'groups,',len(data['volumes']),'volumes,',len(data['sources']),'unactivated source definitions')
if __name__=='__main__':main()
