// Generated by tools/coo/generate_deadly_trial.py.
#pragma once
#include "catalog.h"
#include "../coo/mission_script.h"
namespace sunrise::state::activity::deadly_trial {
inline constexpr coo::Asset kModule{0xC9BC773AU,0x80B2E043U,0,0},kRevive{0xEB7AF01BU,0x80B2EBA7U,4,59},kScene{0x27660927U,0x80B2E6D7U,65,0},kBarrier{0xEB7AF018U,0x80B2E3ADU,23,46};
inline constexpr coo::script::Capability kCapabilities[]{
    {"opening.module","composition",{coo::Operation::mechanic,{0xC9BC773AU,0x80B2E043U,0,0},1U,coo::Wait::requested}},
    {"opening.checked","composition",{coo::Operation::observation,{0x00000000U,0x00000000U,0,0},0U,coo::Wait::observed}},
    {"landing.entered","opening",{coo::Operation::observation,{0x3A62993FU,0x80B2E6F3U,60,2},0U,coo::Wait::observed}},
    {"objective.coordinates","opening",{coo::Operation::objective,{0xC9BC773AU,0x80B2E706U,68,0},3961616249U,coo::Wait::requested}},
    {"dialogue.0","opening",{coo::Operation::dialogue,{0xC9BC773AU,0x80B2E709U,53,2},0U,coo::Wait::nativeReady}},
    {"square.entered","opening",{coo::Operation::observation,{0x40ADE010U,0x80B2E485U,60,3},0U,coo::Wait::observed}},
    {"square.fallen","opening",{coo::Operation::population,{0xC9BC773AU,0x80B2E043U,0,0},1U,coo::Wait::completed}},
    {"objective.pike","opening",{coo::Operation::objective,{0xC9BC773AU,0x80B2E706U,68,0},3667242569U,coo::Wait::requested}},
    {"square.pikes","opening",{coo::Operation::device,{0xC9BC773AU,0x80B2E043U,0,0},1U,coo::Wait::requested}},
    {"followers.entered","opening",{coo::Operation::observation,{0x38C174BBU,0x80B2E491U,60,2},0U,coo::Wait::observed}},
    {"dialogue.1","opening",{coo::Operation::dialogue,{0xC9BC773AU,0x80B2E709U,53,2},1U,coo::Wait::nativeReady}},
    {"objective.path","opening",{coo::Operation::objective,{0xC9BC773AU,0x80B2E706U,68,0},406820629U,coo::Wait::requested}},
    {"streets.entered","opening",{coo::Operation::observation,{0xEB7AF018U,0x80B2E2B5U,60,214},0U,coo::Wait::observed}},
    {"streets.fallen","opening",{coo::Operation::population,{0xC9BC773AU,0x80B2E043U,0,0},2U,coo::Wait::requested}},
    {"choke.entered","opening",{coo::Operation::observation,{0xEB7AF018U,0x80B2E2B5U,60,229},0U,coo::Wait::observed}},
    {"choke.fallen","opening",{coo::Operation::population,{0xC9BC773AU,0x80B2E043U,0,0},3U,coo::Wait::requested}},
    {"overpass.entered","opening",{coo::Operation::observation,{0xEB7AF018U,0x80B2E2B5U,60,131},0U,coo::Wait::observed}},
    {"objective.walker","opening",{coo::Operation::objective,{0xC9BC773AU,0x80B2E706U,68,0},1874372698U,coo::Wait::requested}},
    {"overpass.support","opening",{coo::Operation::population,{0xC9BC773AU,0x80B2E043U,0,0},5U,coo::Wait::requested}},
    {"walker.dead","opening",{coo::Operation::population,{0xC9BC773AU,0x80B2E043U,0,0},4U,coo::Wait::completed}},
    {"barrier.open","opening",{coo::Operation::device,{0xEB7AF018U,0x80B2E3ADU,23,46},0U,coo::Wait::requested}},
    {"objective.temple","opening",{coo::Operation::objective,{0xC9BC773AU,0x80B2E706U,68,0},3851137782U,coo::Wait::requested}},
    {"overpass.pikes","opening",{coo::Operation::device,{0xC9BC773AU,0x80B2E043U,0,0},2U,coo::Wait::requested}},
    {"trial.entered","opening",{coo::Operation::observation,{0x4DDB8242U,0x80B2E47DU,60,2},0U,coo::Wait::observed}},
    {"dialogue.2","opening",{coo::Operation::dialogue,{0xC9BC773AU,0x80B2E709U,53,2},2U,coo::Wait::nativeReady}},
    {"cliff.entered","opening",{coo::Operation::observation,{0xEB7AF01BU,0x80B2E575U,60,157},0U,coo::Wait::observed}},
    {"cliff.fallen","opening",{coo::Operation::population,{0xC9BC773AU,0x80B2E043U,0,0},6U,coo::Wait::requested}},
    {"tunnel.entered","opening",{coo::Operation::observation,{0xEB7AF01BU,0x80B2E575U,60,223},0U,coo::Wait::observed}},
    {"tunnel.fallen","opening",{coo::Operation::population,{0xC9BC773AU,0x80B2E043U,0,0},7U,coo::Wait::requested}},
    {"tower.entered","opening",{coo::Operation::observation,{0xBC1C972BU,0x80B2E6CEU,60,2},0U,coo::Wait::observed}},
    {"dialogue.4","opening",{coo::Operation::dialogue,{0xC9BC773AU,0x80B2E709U,53,2},4U,coo::Wait::nativeReady}},
    {"tower.fallen","opening",{coo::Operation::population,{0xC9BC773AU,0x80B2E043U,0,0},8U,coo::Wait::completed}},
    {"objective.search","opening",{coo::Operation::objective,{0xC9BC773AU,0x80B2E706U,68,0},2284704542U,coo::Wait::requested}},
    {"lair.entered","ending",{coo::Operation::observation,{0xEB7AF01BU,0x80B2E575U,60,195},0U,coo::Wait::observed}},
    {"lair.marauders","ending",{coo::Operation::population,{0xC9BC773AU,0x80B2E043U,0,0},9U,coo::Wait::completed}},
    {"bodies.entered","ending",{coo::Operation::observation,{0x9F8CA248U,0x80B2E6C0U,60,2},0U,coo::Wait::observed}},
    {"dialogue.7","ending",{coo::Operation::dialogue,{0xC9BC773AU,0x80B2E709U,53,2},7U,coo::Wait::nativeReady}},
    {"objective.revive","ending",{coo::Operation::objective,{0xC9BC773AU,0x80B2E706U,68,0},1888195409U,coo::Wait::requested}},
    {"revive.enable","ending",{coo::Operation::device,{0xEB7AF01BU,0x80B2EBA7U,4,59},1U,coo::Wait::requested}},
    {"revive.accepted","ending",{coo::Operation::observation,{0xEB7AF01BU,0x80B2EBA7U,4,59},1U,coo::Wait::observed}},
    {"prelude.finished","ending",{coo::Operation::eventAfter,{0xC9BC773AU,0x80B2E709U,53,2},7U,coo::Wait::observed}},
    {"revive.scene","ending",{coo::Operation::scene,{0x27660927U,0x80B2E6D7U,65,0},1U,coo::Wait::nativeReady}},
    {"revive.scene_finished","ending",{coo::Operation::observation,{0x27660927U,0x80B2E6D7U,65,0},2U,coo::Wait::observed}},
    {"revive.audio_finished","ending",{coo::Operation::eventAfter,{0x27660927U,0x80B2E6D7U,65,0},3U,coo::Wait::observed}},
    {"mission.finish","ending",{coo::Operation::complete,{0xC9BC773AU,0x80B2E043U,0,0},6U,coo::Wait::requested}},
};
inline constexpr coo::script::ModuleCapability kModules[]{{"opening",{kModule,1}}};
inline constexpr coo::script::FactCapability kFacts[]{{"opening.checked",0}};
inline constexpr coo::script::Profile kProfile{"deadly_trial.native.v1","otherMissions",coo::Schema::otherMissions,kCapabilities,kModules,kFacts,kDialogue,kObjectives,{},{},{}};
struct ContractStep { std::uint32_t dependencies;std::span<const std::string_view> commands; };
inline constexpr std::string_view k_opening_0[]{"landing.entered"};
inline constexpr std::string_view k_opening_1[]{"objective.coordinates","dialogue.0"};
inline constexpr std::string_view k_opening_2[]{"square.entered"};
inline constexpr std::string_view k_opening_3[]{"square.fallen"};
inline constexpr std::string_view k_opening_4[]{"objective.pike","square.pikes"};
inline constexpr std::string_view k_opening_5[]{"followers.entered"};
inline constexpr std::string_view k_opening_6[]{"dialogue.1","objective.path"};
inline constexpr std::string_view k_opening_7[]{"streets.entered"};
inline constexpr std::string_view k_opening_8[]{"streets.fallen"};
inline constexpr std::string_view k_opening_9[]{"choke.entered"};
inline constexpr std::string_view k_opening_10[]{"choke.fallen"};
inline constexpr std::string_view k_opening_11[]{"overpass.entered"};
inline constexpr std::string_view k_opening_12[]{"objective.walker","overpass.support","walker.dead"};
inline constexpr std::string_view k_opening_13[]{"barrier.open","objective.temple","overpass.pikes"};
inline constexpr std::string_view k_opening_14[]{"trial.entered"};
inline constexpr std::string_view k_opening_15[]{"dialogue.2"};
inline constexpr std::string_view k_opening_16[]{"cliff.entered"};
inline constexpr std::string_view k_opening_17[]{"cliff.fallen"};
inline constexpr std::string_view k_opening_18[]{"tunnel.entered"};
inline constexpr std::string_view k_opening_19[]{"tunnel.fallen"};
inline constexpr std::string_view k_opening_20[]{"tower.entered"};
inline constexpr std::string_view k_opening_21[]{"dialogue.4","tower.fallen"};
inline constexpr std::string_view k_opening_22[]{"objective.search"};
inline constexpr ContractStep kOpeningContract[]{
    {0U,k_opening_0},
    {1U,k_opening_1},
    {2U,k_opening_2},
    {4U,k_opening_3},
    {8U,k_opening_4},
    {16U,k_opening_5},
    {32U,k_opening_6},
    {64U,k_opening_7},
    {128U,k_opening_8},
    {256U,k_opening_9},
    {512U,k_opening_10},
    {1024U,k_opening_11},
    {2048U,k_opening_12},
    {4096U,k_opening_13},
    {8192U,k_opening_14},
    {16384U,k_opening_15},
    {32768U,k_opening_16},
    {65536U,k_opening_17},
    {131072U,k_opening_18},
    {262144U,k_opening_19},
    {524288U,k_opening_20},
    {1048576U,k_opening_21},
    {2097152U,k_opening_22},
};
inline constexpr std::string_view k_ending_0[]{"lair.entered"};
inline constexpr std::string_view k_ending_1[]{"lair.marauders"};
inline constexpr std::string_view k_ending_2[]{"bodies.entered"};
inline constexpr std::string_view k_ending_3[]{"dialogue.7","objective.revive","revive.enable"};
inline constexpr std::string_view k_ending_4[]{"revive.accepted"};
inline constexpr std::string_view k_ending_5[]{"prelude.finished"};
inline constexpr std::string_view k_ending_6[]{"revive.scene"};
inline constexpr std::string_view k_ending_7[]{"revive.scene_finished","revive.audio_finished"};
inline constexpr std::string_view k_ending_8[]{"mission.finish"};
inline constexpr ContractStep kEndingContract[]{
    {0U,k_ending_0},
    {1U,k_ending_1},
    {2U,k_ending_2},
    {4U,k_ending_3},
    {8U,k_ending_4},
    {16U,k_ending_5},
    {32U,k_ending_6},
    {64U,k_ending_7},
    {128U,k_ending_8},
};
inline constexpr coo::ObjectiveMarker kNativeMarkers[]{
    {0xEC217779U,{{0x40ADE010U,0x80B2E62BU,47,1},{0x29930BA4U,0xC6905B77U,0x40ADE010U,0xBA2B60FDU}}},
    {0xDA95AE49U,{{0xECC3696FU,0x80B2E6E9U,47,1},{0x29930BA4U,0xC6905B77U,0xECC3696FU,0x24A5314AU}}},
    {0x183F9715U,{{0x38C174BBU,0x80B2E66BU,47,7},{0x29930BA4U,0xC6905B77U,0x38C174BBU,0xC704236EU}}},
    {0x6FB8A85AU,{{0xE4BA2E54U,0x80B2E68DU,47,0},{0x29930BA4U,0xC6905B77U,0xE4BA2E54U,0xE58495E9U}}},
    {0xE58BB2F6U,{{0xC91BDFF0U,0x80B2EC47U,47,4},{0x29930BA4U,0xC6905B74U,0xC91BDFF0U,0x69AEC903U}}},
    {0x882DD31EU,{{0xBC1C972BU,0x80B2EC53U,47,10},{0x29930BA4U,0xC6905B74U,0xBC1C972BU,0x69AEC903U}}},
    {0x708B9351U,{{0x27660927U,0x80B2EC62U,47,4},{0x29930BA4U,0xC6905B74U,0x27660927U,0x9BEEEAA2U}}},
};
bool valid_document(const coo::script::Views&) noexcept;
}
